// app/src/components/CommandPalatte.vue
<script setup>
import { computed, nextTick, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { useDocuments } from "#composeables/useDocuments.ts";
import { useSpace } from "#composeables/useSpace.ts";
import { Actions } from "#utils/actions.ts";
import { propertyValueToText } from "#utils/documentProperties.ts";
import { history } from "#utils/history.ts";
import { formatRelativeTime, spacePath } from "#utils/utils.ts";
import {
  boltIcon,
  chevronRightThinIcon,
  documentIcon,
  searchMagnifierIcon,
} from "~/src/assets/icons.ts";

const router = useRouter();
const { documents } = useDocuments();
const { currentSpace } = useSpace();

const isOpen = ref(false);
const searchQuery = ref("");
const selectedIndex = ref(0);
const searchInput = ref(null);
const resultsContainer = ref(null);
const historyEntries = ref([]);

const documentTitle = (doc) => {
  const title = doc.properties?.title;
  return title ? propertyValueToText(title) : "Untitled Document";
};

const getLastVisited = (doc) => {
  const url = `/doc/${doc.slug}`;
  const entry = historyEntries.value.find((h) => h.url === url);
  return entry ? entry.lastVisited : null;
};

const filteredResults = computed(() => {
  const query = searchQuery.value.toLowerCase().trim();
  const results = [];

  let docs = documents.value;
  if (query) {
    docs = docs.filter((doc) => {
      const titleValue = doc.properties?.title;
      const title = titleValue
        ? propertyValueToText(titleValue).toLowerCase()
        : "untitled";
      const slug = doc.slug?.toLowerCase() || "";
      return title.includes(query) || slug.includes(query);
    });
  }

  const sortedDocs = [...docs].sort((a, b) => {
    const aUrl = `/doc/${a.slug}`;
    const bUrl = `/doc/${b.slug}`;
    const aHistory = historyEntries.value.find((entry) => entry.url === aUrl);
    const bHistory = historyEntries.value.find((entry) => entry.url === bUrl);
    if (aHistory && bHistory) return bHistory.lastVisited - aHistory.lastVisited;
    if (aHistory) return -1;
    if (bHistory) return 1;
    return 0;
  });

  for (const doc of sortedDocs) {
    results.push({ type: "document", data: doc });
  }

  for (const [id, action] of Actions.entries()) {
    if (id === "ui:toggle:palatte") continue;
    const matchesQuery = !query || Actions.rank(id, query) > 0;
    if (matchesQuery) {
      results.push({ type: "action", id, data: action });
    }
  }

  return results;
});

// First index of each section (for section headers)
const firstActionIndex = computed(() =>
  filteredResults.value.findIndex((r) => r.type === "action"),
);
const hasDocuments = computed(() =>
  filteredResults.value.some((r) => r.type === "document"),
);
const hasActions = computed(() => filteredResults.value.some((r) => r.type === "action"));

const loadHistory = async () => {
  try {
    historyEntries.value = await history.getAll();
  } catch (error) {
    console.error("Failed to load history:", error);
    historyEntries.value = [];
  }
};

const togglePalette = async () => {
  isOpen.value = !isOpen.value;
  if (isOpen.value) {
    loadHistory();
    nextTick(() => searchInput.value?.focus());
  }
};

const closePalette = () => {
  isOpen.value = false;
  searchQuery.value = "";
  selectedIndex.value = 0;
};

const handleArrowDown = () => {
  if (selectedIndex.value < filteredResults.value.length - 1) {
    selectedIndex.value++;
    scrollToSelected();
  }
};

const handleArrowUp = () => {
  if (selectedIndex.value > 0) {
    selectedIndex.value--;
    scrollToSelected();
  }
};

const handleEnter = () => {
  const selected = filteredResults.value[selectedIndex.value];
  if (selected) {
    if (selected.type === "document") {
      navigateToDocument(selected.data);
    } else if (selected.type === "action") {
      executeAction(selected.id);
    }
  }
};

const scrollToSelected = () => {
  nextTick(() => {
    const el = resultsContainer.value?.querySelector(
      `[data-result-index="${selectedIndex.value}"]`,
    );
    if (el) el.scrollIntoView({ block: "nearest" });
  });
};

const navigateToDocument = async (doc) => {
  if (doc?.slug) {
    const url = `/doc/${doc.slug}`;
    const title = documentTitle(doc);
    try {
      await history.log(url, title);
    } catch (error) {
      console.error("Failed to log history:", error);
    }
    if (url.startsWith("/") && !url.startsWith("//")) {
      router.push(url);
    } else {
      window.location.href = url;
    }
  }
  closePalette();
};

const executeAction = (actionId) => {
  closePalette();
  Actions.run(actionId);
};

const handleKeydown = (event) => {
  if (event.key === "ArrowDown") {
    event.preventDefault();
    handleArrowDown();
  } else if (event.key === "ArrowUp") {
    event.preventDefault();
    handleArrowUp();
  } else if (event.key === "Enter") {
    event.preventDefault();
    handleEnter();
  }
};

watch(searchQuery, () => {
  selectedIndex.value = 0;
});

Actions.register("ui:toggle:palatte", {
  title: "Toggle Command Palatte",
  description: "Open or close the command menu",
  group: "navigation",
  run: async () => {
    togglePalette();
  },
});
</script>

<template>
  <div>
    <Transition name="fade">
      <a-blur
        v-if="isOpen"
        enabled
        class="fixed inset-0 bg-black/30 z-50 flex items-start justify-center pt-[15vh]"
        @click="closePalette"
        @exit="closePalette"
      >
        <div
          class="bg-background border border-neutral-100 rounded-xl shadow-2xl w-full max-w-[640px] mx-4 overflow-hidden"
          @click.stop
        >
          <!-- Search input -->
          <div class="flex items-center gap-3 px-4 py-3 border-b border-neutral-100">
            <div class="svg-icon w-4 h-4 text-neutral flex-none" v-html="searchMagnifierIcon" />
            <input
              ref="searchInput"
              v-model="searchQuery"
              type="text"
              placeholder="Search documents and actions…"
              class="flex-1 outline-none bg-transparent text-neutral-900 text-size-medium placeholder:text-neutral"
              @keydown="handleKeydown"
            />
            <kbd class="hidden sm:inline-block px-1.5 py-0.5 text-[11px] text-neutral border border-neutral-100 rounded-sm font-mono">
              ESC
            </kbd>
          </div>

          <!-- Results -->
          <div ref="resultsContainer" class="overflow-y-auto max-h-[400px] py-1">
            <!-- Empty state -->
            <div v-if="filteredResults.length === 0" class="px-4 py-10 text-center">
              <p class="text-size-medium text-neutral">No results found</p>
            </div>

            <template v-for="(result, index) in filteredResults" :key="result.type === 'document' ? 'doc-' + result.data.id : 'action-' + result.id">
              <!-- Section header -->
              <div
                v-if="(index === 0 && result.type === 'document') || (result.type === 'action' && index === firstActionIndex)"
                class="px-3 pt-2 pb-0.5"
              >
                <span class="text-[11px] font-medium text-neutral uppercase tracking-wider">
                  {{ result.type === "document" ? "Documents" : "Actions" }}
                </span>
              </div>

              <!-- Item -->
              <component
                :is="result.type === 'document' ? 'page-target' : 'div'"
                v-bind="result.type === 'document' ? {
                  'data-document-id': result.data.id,
                  'data-space-id': currentSpace?.id,
                  'data-document-url': spacePath(currentSpace?.slug, `/doc/${result.data.slug}`),
                } : {}"
                class="block px-1 [&[data-dragging]]:opacity-50"
                @document-drag-start="closePalette"
              >
                <button
                  :data-result-index="index"
                  class="w-full text-left px-3xs rounded-md min-h-[36px] flex items-center gap-2.5 text-neutral-800"
                  :class="[
                    index === selectedIndex ? 'bg-primary-100 text-primary-700' : 'hover:bg-primary-50',
                    result.type === 'document' ? 'cursor-grab active:cursor-grabbing' : '',
                  ]"
                  @click="result.type === 'document' ? navigateToDocument(result.data) : executeAction(result.id)"
                  @mouseenter="selectedIndex = index"
                >
                  <div
                    class="svg-icon icon w-4 h-4 flex-none"
                    :class="index === selectedIndex ? 'text-primary-600' : 'text-neutral-400'"
                    v-html="result.type === 'document' ? documentIcon : boltIcon"
                  />
                  <div class="flex-1 min-w-0 flex flex-col py-1.5 gap-2">
                    <span class="text-size-medium truncate font-normal">
                      {{ result.type === "document"
                        ? documentTitle(result.data)
                        : (result.data.title || result.id) }}
                    </span>
                    <span
                      v-if="result.type === 'document' && getLastVisited(result.data)"
                      class="text-size-small text-neutral flex-none opacity-50"
                    >
                      {{ formatRelativeTime(getLastVisited(result.data)) }}
                    </span>
                    <span
                      v-if="result.type === 'action' && result.data.description"
                      class="text-size-small text-neutral truncate opacity-50"
                    >
                      {{ result.data.description }}
                    </span>
                  </div>
                  <div class="flex items-center gap-1 flex-none">
                    <kbd
                      v-for="shortcut in Actions.getShortcutsForAction(result.id)"
                      :key="shortcut"
                      class="px-1.5 py-0.5 bg-neutral-100 border border-neutral-100 rounded-sm font-mono text-[10px] capitalize"
                    >
                      {{ shortcut }}
                    </kbd>
                  </div>
                  <div
                    class="svg-icon w-3.5 h-3.5 text-neutral flex-none transition-opacity"
                    :class="index === selectedIndex ? 'opacity-100' : 'opacity-0'"
                    v-html="chevronRightThinIcon"
                  />
                </button>
              </component>
            </template>
          </div>

          <!-- Footer -->
          <div class="px-4 py-2 bg-neutral-50 border-t border-neutral-100 flex items-center justify-between text-[11px] text-neutral rounded-b-xl">
            <div class="flex items-center gap-3">
              <span class="flex items-center gap-1">
                <kbd class="px-1.5 py-0.5 bg-background border border-neutral-100 rounded-sm font-mono">↑↓</kbd>
                Navigate
              </span>
              <span class="flex items-center gap-1">
                <kbd class="px-1.5 py-0.5 bg-background border border-neutral-100 rounded-sm font-mono">↵</kbd>
                Select
              </span>
            </div>
            <span class="flex items-center gap-1">
              <kbd class="px-1.5 py-0.5 bg-background border border-neutral-100 rounded-sm font-mono">⌘K</kbd>
              Toggle
            </span>
          </div>
        </div>
      </a-blur>
    </Transition>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.15s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
kbd {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
</style>

// server/src/components/CommandPalatte.tsx
import { useNavigate } from "@solidjs/router";
import { createEffect, createMemo, createSignal, For, on, Show } from "solid-js";
import { Dynamic } from "solid-js/web";
import { twMerge } from "tailwind-merge";
import { useDocumentContext } from "#composeables/useDocument.ts";
import { useDocuments } from "#composeables/useDocuments.ts";
import { useSpace } from "#composeables/useSpace.ts";
import { useLocale, useTranslation } from "#composeables/useTranslation.ts";
import {
  useVisualViewport,
  viewportLayerStyle,
} from "#composeables/useVisualViewport.ts";
import { documentTypeIcon } from "#documents/icons.ts";
import { propertyValueToText } from "#documents/properties.ts";
import { documentTitle } from "#documents/title.ts";
import { Actions } from "#utils/actions.ts";
import { formatRelativeTime } from "#utils/dateFormat.ts";
import { history } from "#utils/history.ts";
import { t } from "#utils/lang.ts";
import { spacePath } from "#utils/utils.ts";
import { Icon, type IconName } from "./Icon.tsx";

type HistoryEntry = { url: string; lastVisited: number };
// biome-ignore lint/suspicious/noExplicitAny: documents are untyped at this layer.
type Doc = any;
type Result =
  | { type: "document"; data: Doc; id?: undefined }
  | { type: "action"; id: string; data: { title?: string; description?: string } }
  | { type: "search"; title: string; space: string; id?: undefined }
  | { type: "create"; title: string; id?: undefined };

function sectionLabel(type: Result["type"], lang: string): string {
  if (type === "document") return t("Documents", lang);
  if (type === "action") return t("Actions", lang);
  if (type === "search") return t("Search", lang);
  return t("Create", lang);
}

const RESULT_ICONS: Record<Exclude<Result["type"], "document">, IconName> = {
  action: "bolt",
  search: "search",
  create: "new-document",
};

function resultIcon(result: Result): IconName {
  if (result.type === "document") return documentTypeIcon(result.data.type);
  return RESULT_ICONS[result.type];
}

const MAX_DOCUMENT_RESULTS = 50;

function resultLabel(result: Result, lang: string): string {
  if (result.type === "document") return documentTitle(result.data, lang);
  if (result.type === "action") return result.data.title || result.id;
  if (result.type === "search")
    return t('Search "{query}" in {space}', lang)
      .replace("{query}", result.title)
      .replace("{space}", result.space);
  return t('Create Document with title "{title}"', lang).replace("{title}", result.title);
}

function resultDescription(result: Result, lang: string): string | undefined {
  if (result.type === "action") return result.data.description;
  if (result.type === "search") return t("Search the full text of every document", lang);
  if (result.type === "create") return t("Open a new document with this title", lang);
  return undefined;
}

export function CommandPalatte() {
  const t = useTranslation();
  const lang = useLocale();
  const viewport = useVisualViewport();

  const navigate = useNavigate();
  const { documents } = useDocuments();
  const { documentContext } = useDocumentContext();
  const { currentSpace } = useSpace();

  const [isOpen, setIsOpen] = createSignal(false);
  const [searchQuery, setSearchQuery] = createSignal("");
  const [selectedIndex, setSelectedIndex] = createSignal(0);
  const [historyEntries, setHistoryEntries] = createSignal<HistoryEntry[]>([]);
  let searchInput: HTMLInputElement | undefined;
  let resultsContainer: HTMLDivElement | undefined;

  const lastVisitedByUrl = createMemo(
    () => new Map(historyEntries().map((entry) => [entry.url, entry.lastVisited])),
  );

  const getLastVisited = (doc: Doc) => lastVisitedByUrl().get(`/doc/${doc.slug}`) ?? null;

  const filteredResults = createMemo<Result[]>(() => {
    if (!isOpen()) return [];

    const typed = searchQuery().trim();
    const query = typed.toLowerCase();
    const results: Result[] = [];

    let docs: Doc[] = documents();
    if (query) {
      docs = docs.filter((doc: Doc) => {
        const titleValue = doc.properties?.title;
        const title = titleValue
          ? propertyValueToText(titleValue).toLowerCase()
          : "untitled";
        return title.includes(query) || (doc.slug?.toLowerCase() || "").includes(query);
      });
    }

    const visited = lastVisitedByUrl();
    const sorted = [...docs].sort((a: Doc, b: Doc) => {
      const aVisited = visited.get(`/doc/${a.slug}`);
      const bVisited = visited.get(`/doc/${b.slug}`);
      if (aVisited !== undefined && bVisited !== undefined) return bVisited - aVisited;
      if (aVisited !== undefined) return -1;
      if (bVisited !== undefined) return 1;
      return 0;
    });

    for (const doc of sorted.slice(0, MAX_DOCUMENT_RESULTS))
      results.push({ type: "document", data: doc });

    for (const [id, action] of Actions.entries()) {
      if (id === "ui:toggle:palatte") continue;
      if (!query || Actions.rank(id, query) > 0) {
        results.push({ type: "action", id, data: action });
      }
    }

    const space = currentSpace();
    if (typed && space) {
      results.push({ type: "search", title: typed, space: space.name || "this space" });
    }

    if (typed && space) results.push({ type: "create", title: typed });

    return results;
  });

  const sectionStarts = createMemo(() => {
    const starts = new Map<Result["type"], number>();
    filteredResults().forEach((result, index) => {
      if (!starts.has(result.type)) starts.set(result.type, index);
    });
    return starts;
  });

  async function loadHistory() {
    try {
      setHistoryEntries((await history.getAll()) as HistoryEntry[]);
    } catch (error) {
      console.error("Failed to load history:", error);
      setHistoryEntries([]);
    }
  }

  function closePalette() {
    setIsOpen(false);
    setSearchQuery("");
    setSelectedIndex(0);
  }

  function togglePalette() {
    setIsOpen((open) => !open);
  }

  createEffect(
    on(isOpen, (open) => {
      if (open) {
        void loadHistory();
        requestAnimationFrame(() => searchInput?.focus());
      } else if (searchInput && document.activeElement === searchInput) {
        searchInput.blur();
      }
    }),
  );

  function scrollToSelected() {
    resultsContainer
      ?.querySelector(`[data-result-index="${selectedIndex()}"]`)
      ?.scrollIntoView({ block: "nearest" });
  }

  async function navigateToDocument(doc: Doc) {
    if (doc?.slug) {
      const url = `/doc/${doc.slug}`;
      try {
        await history.log(url, documentTitle(doc, lang));
      } catch (error) {
        console.error("Failed to log history:", error);
      }
      if (url.startsWith("/") && !url.startsWith("//")) navigate(url);
      else window.location.href = url;
    }
    closePalette();
  }

  function executeAction(actionId: string) {
    closePalette();
    Actions.run(actionId);
  }

  function createDocumentWithTitle(title: string) {
    closePalette();
    const query = new URLSearchParams({ title });
    // The draft lands where the user already is: under the open document, or in
    // the space root from anywhere without one.
    const parentId = documentContext().documentId;
    if (parentId) query.set("parent", parentId);
    navigate(`/new?${query.toString()}`);
  }

  function searchSpace(query: string) {
    closePalette();
    const trimmed = query.trim();
    navigate(trimmed ? `/search?q=${encodeURIComponent(trimmed)}` : "/search");
  }

  function runResult(result: Result) {
    if (result.type === "document") void navigateToDocument(result.data);
    else if (result.type === "action") executeAction(result.id);
    else if (result.type === "search") searchSpace(result.title);
    else createDocumentWithTitle(result.title);
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      if (selectedIndex() < filteredResults().length - 1) {
        setSelectedIndex((index) => index + 1);
        scrollToSelected();
      }
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      if (selectedIndex() > 0) {
        setSelectedIndex((index) => index - 1);
        scrollToSelected();
      }
    } else if (event.key === "Enter") {
      event.preventDefault();
      const selected = filteredResults()[selectedIndex()];
      if (selected) runResult(selected);
    }
  }

  createEffect(on(searchQuery, () => setSelectedIndex(0), { defer: true }));

  Actions.register("ui:toggle:palatte", {
    title: t("Toggle Command Palatte"),
    description: t("Open or close the command menu"),
    group: "navigation",
    run: async () => togglePalette(),
  });

  return (
    <div>
      <a-blur
        attr:hidden={isOpen() ? undefined : ""}
        attr:enabled={isOpen() ? "" : undefined}
        class="overlay-fade fixed z-50 flex items-start justify-center overflow-hidden bg-black/30"
        style={{
          ...viewportLayerStyle(viewport()),
          "padding-top": `${Math.round(viewport().height * 0.15)}px`,
        }}
        onClick={closePalette}
        on:exit={closePalette}
      >
        {/* biome-ignore lint/a11y/noStaticElementInteractions: stops the click reaching the dismissal layer. */}
        {/* biome-ignore lint/a11y/useKeyWithClickEvents: keyboard handling lives on the input below. */}
        <div
          class="mx-4 flex max-h-full w-full max-w-[640px] flex-col overflow-hidden rounded-xl border border-neutral-100 bg-background shadow-2xl"
          onClick={(event) => event.stopPropagation()}
        >
          <div class="flex flex-none items-center gap-3 border-neutral-100 border-b px-4 py-3">
            <Icon class="h-4 w-4 flex-none text-neutral" name="search" />
            <input
              ref={searchInput}
              type="text"
              placeholder={t("Search documents and actions…")}
              class="flex-1 bg-transparent text-neutral-900 text-size-medium outline-none placeholder:text-neutral"
              value={searchQuery()}
              onInput={(event) => setSearchQuery(event.currentTarget.value)}
              onKeyDown={handleKeydown}
            />
            <button
              type="button"
              onClick={() => searchSpace(searchQuery())}
              class="flex flex-none items-center gap-1 rounded-md px-2 py-1 font-medium text-neutral text-size-small transition-colors hover:bg-neutral-100 hover:text-neutral-800"
              title={t("Open the full search page")}
            >
              {t("Full search")}
              <Icon class="h-3 w-3" name="chevron-right-small" />
            </button>

            <a-shortcut class="hidden sm:flex" attr:data-shortcut="esc" />
          </div>

          <div
            ref={resultsContainer}
            class="min-h-0 flex-1 overflow-y-auto py-1 md:max-h-[400px]"
          >
            <Show when={isOpen() && filteredResults().length === 0}>
              <div class="px-4 py-10 text-center">
                <p class="text-neutral text-size-medium">{t("No results found")}</p>
              </div>
            </Show>

            <For each={filteredResults()}>
              {(result, index) => (
                <>
                  <Show when={sectionStarts().get(result.type) === index()}>
                    <div class="px-3 pt-2 pb-0.5">
                      <span class="font-medium text-neutral text-size-extra-small uppercase tracking-wider">
                        {sectionLabel(result.type, lang)}
                      </span>
                    </div>
                  </Show>

                  <Dynamic
                    component={result.type === "document" ? "page-target" : "div"}
                    {...(result.type === "document"
                      ? {
                          "attr:data-document-id": result.data.id,
                          "attr:data-document-type": result.data.type ?? undefined,
                          "attr:data-space-id": currentSpace()?.id,
                          "attr:data-document-url": spacePath(
                            currentSpace()?.slug,
                            `/doc/${result.data.slug}`,
                          ),
                        }
                      : {})}
                    class="block px-1 [&[data-dragging]]:opacity-50"
                    on:drag={closePalette}
                  >
                    <button
                      type="button"
                      data-result-index={index()}
                      class="flex min-h-[36px] w-full items-center gap-2.5 rounded-md px-3xs text-left text-neutral-800"
                      classList={{
                        "bg-primary-100 text-primary-700": index() === selectedIndex(),
                        "hover:bg-primary-50": index() !== selectedIndex(),
                        "cursor-grab active:cursor-grabbing": result.type === "document",
                      }}
                      onClick={() => runResult(result)}
                      onMouseEnter={() => setSelectedIndex(index())}
                    >
                      <Icon
                        class={twMerge(
                          "h-4 w-4 flex-none",
                          index() === selectedIndex()
                            ? "text-primary-600"
                            : "text-neutral-400",
                        )}
                        name={resultIcon(result)}
                      />
                      <div class="flex min-w-0 flex-1 flex-col py-1.5">
                        <span class="truncate font-normal text-size-medium">
                          {resultLabel(result, lang)}
                        </span>
                        <Show
                          when={result.type === "document" && getLastVisited(result.data)}
                        >
                          {(visited) => (
                            <span class="flex-none text-neutral text-size-small opacity-50">
                              {formatRelativeTime(visited(), lang, { style: "short" })}
                            </span>
                          )}
                        </Show>
                        <Show when={resultDescription(result, lang)}>
                          {(description) => (
                            <span class="truncate text-neutral text-size-small opacity-50">
                              {description()}
                            </span>
                          )}
                        </Show>
                      </div>
                      <div class="flex flex-none items-center gap-1">
                        <Show when={result.type === "action"}>
                          <a-shortcut
                            attr:data-shortcut={
                              result.id
                                ? Actions.getShortcutsForAction(result.id)
                                    ?.values()
                                    .next().value
                                : undefined
                            }
                          />
                        </Show>
                      </div>
                      <Icon
                        class={twMerge(
                          "h-3.5 w-3.5 flex-none text-neutral transition-opacity",
                          index() === selectedIndex() ? "opacity-100" : "opacity-0",
                        )}
                        name="chevron-right-thin"
                      />
                    </button>
                  </Dynamic>
                </>
              )}
            </For>
          </div>

          <div class="flex items-center justify-between rounded-b-xl border-neutral-100 border-t bg-neutral-50 px-4 py-2 text-neutral text-size-extra-small">
            <div class="flex items-center gap-3">
              <span class="flex pointer-coarse:hidden items-center gap-1">
                <a-shortcut attr:data-shortcut="↑-↓" />
                {t("Navigate")}
              </span>
              <span class="flex pointer-coarse:hidden items-center gap-1">
                <a-shortcut attr:data-shortcut="↵" />
                {t("Select")}
              </span>
            </div>
            <span class="flex pointer-coarse:hidden items-center gap-1">
              <a-shortcut
                attr:data-shortcut={
                  Actions.getShortcutsForAction("ui:toggle:palatte")?.values().next()
                    .value
                }
              />
              {t("Toggle")}
            </span>
          </div>
        </div>
      </a-blur>
    </div>
  );
}
