// app/src/components/DocumentActivityFeed.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { AuditLog } from "#api/client.ts";
import { addIcon, confirmationIcon, editEntryIcon } from "#assets/icons.ts";
import {
  type ActivityGroup,
  getAuditEventAction,
  getAuditEventLabel,
  getEntryChangeLabel,
  groupActivityEntries,
  hasPropertyChange,
} from "#utils/auditActivity.ts";
import { t } from "#utils/lang.ts";
import type { DisplayUser } from "#utils/userDisplay.ts";
import { normalizeTimestamp } from "#utils/utils.ts";
import "./AvatarElement.ts";

const props = defineProps<{
  entries: AuditLog[];
  getUserName: (userId?: string | null) => string;
  getUser?: (userId?: string | null) => DisplayUser | undefined;
}>();

const expandedGroups = ref(new Set<string>());

function getGroupAction(items: AuditLog[]): string {
  return items[0] ? getAuditEventAction(items[0].event) : t("updated");
}

function getDocumentActivityIcon(entry: AuditLog): string {
  if (entry.event === "publish") return confirmationIcon;
  return editEntryIcon;
}

function getDocumentEntries(group: ActivityGroup): AuditLog[] {
  const entries = group.items.filter(isVisibleDocumentEntry);
  return isGroupExpanded(group.id) ? entries : entries.slice(0, 3);
}

function getHiddenDocumentEntryCount(items: AuditLog[]): number {
  return Math.max(0, items.filter(isVisibleDocumentEntry).length - 3);
}

function getMoreChangesLabel(count: number): string {
  return `${count} ${count === 1 ? t("more change") : t("more changes")}`;
}

function isVisibleDocumentEntry(entry: AuditLog): boolean {
  return entry.event !== "view";
}

function isGroupExpanded(groupId: string): boolean {
  return expandedGroups.value.has(groupId);
}

function toggleGroup(groupId: string): void {
  const next = new Set(expandedGroups.value);
  if (next.has(groupId)) {
    next.delete(groupId);
  } else {
    next.add(groupId);
  }
  expandedGroups.value = next;
}

function hasDocumentDelta(entry: AuditLog): boolean {
  return (
    hasPropertyChange(entry) &&
    (entry.details?.previousValue !== undefined ||
      entry.details?.newValue !== undefined ||
      entry.event === "property_delete")
  );
}

function activityMinute(entry?: AuditLog): string {
  if (!entry) return "";
  try {
    const date = normalizeTimestamp(entry.createdAt as string);
    date.setSeconds(0, 0);
    return date.toISOString();
  } catch {
    return String(entry.createdAt);
  }
}

function getDocumentBatchKey(entry: AuditLog | undefined, userId: string | null): string {
  if (!entry) return "";
  return [
    userId,
    entry.docId,
    getAuditEventAction(entry.event),
    entry.revisionId ?? activityMinute(entry),
  ].join(":");
}

/** Document entries batch by revision, falling back to the minute. */
function isSameDocumentBatch(entry: AuditLog, group: ActivityGroup): boolean {
  return (
    getDocumentBatchKey(group.items[0], group.userId) ===
    getDocumentBatchKey(entry, entry.userId ?? null)
  );
}

const activityGroups = computed(() =>
  groupActivityEntries(props.entries, isSameDocumentBatch),
);
</script>

<template>
  <div class="@container space-y-4">
    <template v-for="group in activityGroups" :key="group.id">
      <div
        v-if="group.showBucket"
        class="px-1 text-size-small font-medium text-neutral-500"
      >
        {{ group.bucketLabel }}
      </div>

      <article class="rounded-lg border border-neutral-100 bg-neutral-10 px-3 py-3">
        <div class="flex items-start gap-3">
          <vektor-avatar
            size="small"
            :user-id="group.userId ?? undefined"
            :user="props.getUser?.(group.userId)"
          />

          <div class="min-w-0 flex-1">
            <div class="flex min-w-0 items-center gap-2">
              <div
                class="flex min-w-0 flex-1 items-baseline gap-1 text-size-small leading-small"
              >
                <span class="truncate font-semibold text-neutral-900">
                  {{ getUserName(group.userId) }}
                </span>
                <span class="shrink-0 text-neutral-700"
                  >{{ getGroupAction(group.items) }}</span
                >
              </div>
              <slot name="header-actions" :items="group.items" />
            </div>

            <div class="mt-2.5 space-y-2">
              <div
                v-for="entry in getDocumentEntries(group)"
                :key="entry.id"
                class="flex min-w-0 items-center gap-3"
              >
                <div
                  class="svg-icon h-4 w-4 shrink-0 text-neutral-400"
                  v-html="getDocumentActivityIcon(entry)"
                />
                <div
                  class="min-w-0 flex-1 truncate text-size-small font-medium text-neutral-600"
                >
                  {{ getEntryChangeLabel(entry) ?? getAuditEventLabel(entry.event) }}
                </div>

                <div
                  v-if="hasDocumentDelta(entry)"
                  class="flex max-w-[55%] shrink-0 items-center gap-1.5 rounded-md bg-neutral-50 px-2 py-0.5 text-size-small text-neutral-500"
                >
                  <span
                    v-if="entry.details?.previousValue"
                    class="min-w-0 max-w-[16ch] truncate"
                    :title="entry.details.previousValue"
                  >
                    {{ entry.details.previousValue }}
                  </span>
                  <span v-else class="text-neutral-400">—</span>
                  <span class="font-mono text-size-extra-small text-neutral-400">→</span>
                  <span
                    v-if="entry.event === 'property_delete'"
                    class="shrink-0 text-red-500"
                  >
                    {{ t("removed") }}
                  </span>
                  <span
                    v-else-if="entry.details?.newValue"
                    class="min-w-0 max-w-[16ch] truncate text-neutral-700"
                    :title="entry.details.newValue"
                  >
                    {{ entry.details.newValue }}
                  </span>
                  <span v-else class="text-neutral-400">—</span>
                </div>

                <slot name="entry-actions" :entry="entry" />
              </div>

              <button
                v-if="getHiddenDocumentEntryCount(group.items) > 0"
                type="button"
                class="flex items-center gap-3 text-size-small font-medium text-neutral-500 hover:text-neutral-700"
                @click="toggleGroup(group.id)"
              >
                <div
                  class="svg-icon h-4 w-4 shrink-0 text-neutral-400 transition-transform"
                  :class="isGroupExpanded(group.id) ? 'rotate-45' : ''"
                  v-html="addIcon"
                />
                <span>
                  {{ isGroupExpanded(group.id)
                      ? t("Show fewer changes")
                      : getMoreChangesLabel(getHiddenDocumentEntryCount(group.items)) }}
                </span>
              </button>
            </div>
          </div>
        </div>
      </article>
    </template>
  </div>
</template>

// server/src/components/DocumentActivityFeed.tsx
import { createMemo, createSignal, For, type JSX, Show } from "solid-js";
import { twMerge } from "tailwind-merge";
import type { AuditLog } from "#api/client.ts";
import {
  type ActivityGroup,
  activityActorName,
  getAuditEventAction,
  getAuditEventLabel,
  getEntryChangeLabel,
  groupActivityEntries,
  hasPropertyChange,
} from "#utils/auditActivity.ts";
import { normalizeTimestamp } from "#utils/datetime.ts";
import { t } from "#utils/lang.ts";
import type { DisplayUser } from "#utils/userDisplay.ts";
import "./AvatarElement.ts";
import { Icon, type IconName } from "./Icon.tsx";
import { useLocale, useTranslation } from "#composeables/useTranslation.ts";

interface Props {
  entries: AuditLog[];
  getUserName: (userId?: string | null) => string;
  getUser?: (userId?: string | null) => DisplayUser | undefined;
  headerActions?: (items: AuditLog[]) => JSX.Element;
  entryActions?: (entry: AuditLog) => JSX.Element;
}

function getGroupAction(items: AuditLog[], lang: string): string {
  return items[0] ? getAuditEventAction(items[0].event, lang) : t("updated", lang);
}

function getDocumentActivityIcon(entry: AuditLog): IconName {
  if (entry.event === "publish") return "confirmation";
  return "edit-entry";
}

function getMoreChangesLabel(lang: string, count: number): string {
  return `${count} ${count === 1 ? t("more change", lang) : t("more changes", lang)}`;
}

function isVisibleDocumentEntry(entry: AuditLog): boolean {
  return entry.event !== "view";
}

function getHiddenDocumentEntryCount(items: AuditLog[]): number {
  return Math.max(0, items.filter(isVisibleDocumentEntry).length - 3);
}

function hasDocumentDelta(entry: AuditLog): boolean {
  return (
    hasPropertyChange(entry) &&
    (entry.details?.previousValue !== undefined ||
      entry.details?.newValue !== undefined ||
      entry.event === "property_delete")
  );
}

function activityMinute(entry?: AuditLog): string {
  if (!entry) return "";
  try {
    const date = normalizeTimestamp(entry.createdAt as string);
    date.setSeconds(0, 0);
    return date.toISOString();
  } catch {
    return String(entry.createdAt);
  }
}

function getDocumentBatchKey(entry: AuditLog | undefined, lang: string): string {
  if (!entry) return "";
  return [
    entry.docId,
    getAuditEventAction(entry.event, lang),
    entry.revisionId ?? activityMinute(entry),
  ].join(":");
}

function isSameDocumentBatch(
  entry: AuditLog,
  group: ActivityGroup,
  lang: string,
): boolean {
  return getDocumentBatchKey(group.items[0], lang) === getDocumentBatchKey(entry, lang);
}

export function DocumentActivityFeed(props: Props) {
  const t = useTranslation();
  const lang = useLocale();

  const [expandedGroups, setExpandedGroups] = createSignal(new Set<string>());

  function isGroupExpanded(groupId: string): boolean {
    return expandedGroups().has(groupId);
  }

  function toggleGroup(groupId: string): void {
    const next = new Set(expandedGroups());
    if (next.has(groupId)) {
      next.delete(groupId);
    } else {
      next.add(groupId);
    }
    setExpandedGroups(next);
  }

  function getDocumentEntries(group: ActivityGroup): AuditLog[] {
    const entries = group.items.filter(isVisibleDocumentEntry);
    return isGroupExpanded(group.id) ? entries : entries.slice(0, 3);
  }

  const activityGroups = createMemo(() =>
    groupActivityEntries(
      props.entries,
      (entry, group) => isSameDocumentBatch(entry, group, lang),
      lang,
    ),
  );

  return (
    <div class="@container space-y-4">
      <For each={activityGroups()}>
        {(group) => (
          <>
            <Show when={group.showBucket}>
              <div class="px-1 font-medium text-neutral-500 text-size-small">
                {group.bucketLabel}
              </div>
            </Show>

            <article class="rounded-lg border border-neutral-100 bg-neutral-10 px-3 py-3">
              <div class="flex items-start gap-3">
                <vektor-avatar
                  size="small"
                  attr:user-id={group.actor.userId ?? undefined}
                  attr:app={group.actor.app ?? undefined}
                  prop:user={props.getUser?.(group.actor.userId)}
                />

                <div class="min-w-0 flex-1">
                  <div class="flex min-w-0 items-center gap-2">
                    <div class="flex min-w-0 flex-1 items-baseline gap-1 text-size-small leading-small">
                      <span class="truncate font-semibold text-neutral-900">
                        {activityActorName(group.actor, props.getUserName)}
                      </span>
                      <Show when={group.actor.via}>
                        {(via) => (
                          <span class="shrink-0 text-neutral-500">
                            {t("via {app}").replace("{app}", via())}
                          </span>
                        )}
                      </Show>
                      <span class="shrink-0 text-neutral-700">
                        {getGroupAction(group.items, lang)}
                      </span>
                    </div>
                    {props.headerActions?.(group.items)}
                  </div>

                  <div class="mt-2.5 space-y-2">
                    <For each={getDocumentEntries(group)}>
                      {(entry) => (
                        <div class="flex min-w-0 items-center gap-3">
                          <Icon
                            class="h-4 w-4 shrink-0 text-neutral-400"
                            name={getDocumentActivityIcon(entry)}
                          />
                          <div class="min-w-0 flex-1 truncate font-medium text-neutral-600 text-size-small">
                            {getEntryChangeLabel(entry, lang) ??
                              getAuditEventLabel(entry.event, lang)}
                          </div>

                          <Show when={hasDocumentDelta(entry)}>
                            <div class="flex max-w-[55%] shrink-0 items-center gap-1.5 rounded-md bg-neutral-50 px-2 py-0.5 text-neutral-500 text-size-small">
                              <Show
                                when={entry.details?.previousValue}
                                fallback={<span class="text-neutral-400">—</span>}
                              >
                                <span
                                  class="min-w-0 max-w-[16ch] truncate"
                                  title={entry.details?.previousValue}
                                >
                                  {entry.details?.previousValue}
                                </span>
                              </Show>
                              <span class="font-mono text-neutral-400 text-size-extra-small">
                                →
                              </span>
                              <Show
                                when={entry.event === "property_delete"}
                                fallback={
                                  <Show
                                    when={entry.details?.newValue}
                                    fallback={<span class="text-neutral-400">—</span>}
                                  >
                                    <span
                                      class="min-w-0 max-w-[16ch] truncate text-neutral-700"
                                      title={entry.details?.newValue}
                                    >
                                      {entry.details?.newValue}
                                    </span>
                                  </Show>
                                }
                              >
                                <span class="shrink-0 text-red-500">{t("removed")}</span>
                              </Show>
                            </div>
                          </Show>

                          {props.entryActions?.(entry)}
                        </div>
                      )}
                    </For>

                    <Show when={getHiddenDocumentEntryCount(group.items) > 0}>
                      <button
                        type="button"
                        class="flex items-center gap-3 font-medium text-neutral-500 text-size-small hover:text-neutral-700"
                        onClick={() => toggleGroup(group.id)}
                      >
                        <Icon
                          class={twMerge(
                            "h-4 w-4 shrink-0 text-neutral-400 transition-transform",
                            isGroupExpanded(group.id) && "rotate-45",
                          )}
                          name="add"
                        />
                        <span>
                          {isGroupExpanded(group.id)
                            ? t("Show fewer changes")
                            : getMoreChangesLabel(
                                lang,
                                getHiddenDocumentEntryCount(group.items),
                              )}
                        </span>
                      </button>
                    </Show>
                  </div>
                </div>
              </div>
            </article>
          </>
        )}
      </For>
    </div>
  );
}
