// app/src/components/PropertyChip.vue
<script setup lang="ts">
import { twMerge } from "tailwind-merge";
import { computed, onMounted, ref } from "vue";
import type { Property } from "#documents/properties.ts";
import { t } from "#utils/lang.ts";
import Icon from "./Icon.vue";
import type { SelectMenuItem } from "./SelectMenu.vue";
import SelectMenu from "./SelectMenu.vue";
import "@atrium-ui/elements/blur";
import "@atrium-ui/elements/calendar";
import { addIcon } from "#assets/icons.ts";

const inputElement = ref();

const props = defineProps<{
  label?: string;
  nameLabel?: string;
  valueLabels?: string[];
  icon?: string;
  variant?: "default" | "special";
  readonly?: boolean;
  property?: Property | null;
  allowMultiple?: boolean;
  showTooltip?: boolean;
  propertyValues?: (property: Property) => Promise<SelectMenuItem[]>;
}>();

const emit = defineEmits<{
  update: [property: Property & { search: string }];
  delete: [property: Property];
}>();

const valueOptions = ref<SelectMenuItem[]>([]);

const isEditPopoverOpen = ref(false);
const propertyName = ref(props.property?.name || "");
const selectedValue = ref<string | string[] | undefined>(props.property?.value);
const searchInput = ref("");
const dateValue = ref("");

const selectedValues = computed(() => {
  if (Array.isArray(selectedValue.value)) return selectedValue.value;
  return selectedValue.value ? [selectedValue.value] : [];
});

const valueLabels = computed(() => props.valueLabels ?? []);

const handleClick = async () => {
  if (props.readonly || !props.property) return;
  if (props.property) {
    isEditPopoverOpen.value = !isEditPopoverOpen.value;
    propertyName.value = props.property.name;
    selectedValue.value = props.property.value;

    // For date properties, set the date value
    if (
      props.property.type === "date" &&
      props.property.value &&
      !Array.isArray(props.property.value)
    ) {
      dateValue.value = props.property.value;
    }

    await new Promise((resolve) => setTimeout(resolve, 25));

    // Only fetch options for non-date properties
    if (props.property.type !== "date") {
      inputElement.value?.focus();

      props.propertyValues?.(props.property).then((options) => {
        valueOptions.value = options;
      });
    }
  }
};

const filteredValueOptions = computed(() => {
  const searchTerm = searchInput.value.toLowerCase();
  const items = valueOptions.value.filter((item) =>
    item.label?.toLowerCase().includes(searchTerm),
  );
  if (items.length === 0) {
    return [
      {
        id: "__new__",
        label: t("Add {value}").replace("{value}", searchInput.value),
        icon: addIcon,
      },
    ];
  }
  return items;
});

const handleValueSelect = (item: SelectMenuItem) => {
  if (props.property) {
    const itemValue = item.id === "__new__" ? searchInput.value.trim() : item.id;
    if (!itemValue) return;

    if (props.allowMultiple) {
      const nextValue = selectedValues.value.includes(itemValue)
        ? selectedValues.value.filter((value) => value !== itemValue)
        : [...selectedValues.value, itemValue];

      selectedValue.value = nextValue;
      emit("update", {
        ...props.property,
        name: propertyName.value,
        value: nextValue,
        search: searchInput.value,
      });
      searchInput.value = "";
      return;
    }

    selectedValue.value = itemValue;
    emit("update", {
      ...props.property,
      name: propertyName.value,
      value: itemValue,
      search: searchInput.value,
    });
    handleExit();
  }
};

const handleDateChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  if (props.property) {
    emit("update", {
      ...props.property,
      name: propertyName.value,
      value: target.value,
      search: "",
    });
    handleExit();
  }
};

const handleDelete = () => {
  if (props.property) {
    emit("delete", props.property);
    handleExit();
  }
};

const handleExit = () => {
  isEditPopoverOpen.value = false;
  searchInput.value = "";
  dateValue.value = "";
};

onMounted(() => {
  window.addEventListener("pointerdown", (e) => {
    if (!e.target?.closest("a-blur") && isEditPopoverOpen.value === true) {
      handleExit();
    }
  });
});
</script>

<template>
  <div class="relative">
    <button
      v-if="property"
      type="button"
      :data-tooltip="showTooltip === false ? undefined : nameLabel || property.name"
      :class="{
        'text-interactive flex items-center gap-4xs py-6xs px-4xs rounded-lg transition-colors': true,
        'bg-primary-50 hover:bg-primary-100 border border-primary-100': variant === 'special',
        'bg-background hover:bg-primary-10 border border-primary-200': variant === 'default',
        'cursor-pointer': property !== null && !readonly,
        'cursor-default': property === null || readonly,
      }"
      @click="handleClick"
    >
      <div
        v-if="icon"
        v-html="icon"
        class="[&_svg]:w-[18px] [&_svg]:h-[18px] [&_svg]:inline"
        :class="variant === 'special' ? '[&_svg]:text-primary-700' : '[&_svg]:text-primary-600'"
      />
      <div
        v-if="!icon"
        class="w-[18px] h-[18px] rounded-sm flex items-center justify-center bg-primary-500"
      />
      <span
        v-if="valueLabels.length === 0"
        :class="twMerge(
            'max-w-[150px] text-ellipsis overflow-hidden whitespace-nowrap capitalize',
            variant === 'special' && 'text-primary-700',
            variant === 'default' && 'text-primary-600'
          )"
      >
        {{ label }}
      </span>
      <span
        v-else
        class="flex items-center gap-4xs min-w-0 max-w-[260px] overflow-hidden"
      >
        <span
          v-for="valueLabel in valueLabels"
          :key="valueLabel"
          class="max-w-[110px] text-ellipsis overflow-hidden whitespace-nowrap capitalize rounded-md bg-primary-50 px-4xs text-primary-600"
        >
          {{ valueLabel }}
        </span>
      </span>
    </button>

    <button
      v-else
      type="button"
      :class="{
        'text-interactive flex items-center gap-4xs py-6xs px-4xs rounded-lg transition-colors': true,
        'bg-primary-50 hover:bg-primary-100 border border-primary-100': variant === 'special',
        'bg-background hover:bg-primary-10 border border-primary-200': variant === 'default',
        'cursor-pointer': property !== null && !readonly,
        'cursor-default': property === null || readonly,
      }"
      @click="handleClick"
    >
      <div
        v-if="icon"
        v-html="icon"
        class="[&_svg]:w-[18px] [&_svg]:h-[18px] [&_svg]:inline"
        :class="variant === 'special' ? '[&_svg]:text-primary-700' : '[&_svg]:text-primary-600'"
      />
      <span
        :class="{
          'text-primary-700': variant === 'special',
          'text-primary-600': variant === 'default',
        }"
      >
        {{ label }}
      </span>
    </button>

    <!-- Edit Property Popover -->
    <a-blur
      v-if="isEditPopoverOpen && property"
      enabled
      @exit="handleExit"
      class="absolute -top-4xs -left-4xs bg-neutral-10 border border-neutral-100 rounded-lg p-5xs flex flex-col z-50 shadow-large"
    >
      <!-- Property name input with delete button -->
      <div class="flex items-center gap-4xs px-3xs w-full">
        <div
          v-if="icon"
          v-html="icon"
          class="[&_svg]:w-[18px] [&_svg]:h-[18px] [&_svg]:text-neutral-950"
        />
        <div class="flex-1 overflow-hidden py-5xs whitespace-nowrap">
          <input
            v-if="property.type !== 'date'"
            ref="inputElement"
            v-model="searchInput"
            class="bg-transparent border-none outline-none text-interactive w-[150px]"
            :placeholder="nameLabel || property.name || t('Property name')"
          >
          <span v-else class="text-interactive">
            {{ property.name }}
          </span>
        </div>
        <button
          type="button"
          class="shrink-0 transition-opacity hover:opacity-70 cursor-pointer text-neutral-950"
          :aria-label="t('Delete property')"
          @click="handleDelete"
        >
          <Icon name="trash" class="w-[18px] h-[18px]" />
        </button>
      </div>

      <!-- Date Picker for date type -->
      <div v-if="property.type === 'date'">
        <a-calendar :value="dateValue" @change="handleDateChange" class="p-2 w-[250px]" />
      </div>

      <!-- Property Value Selector for other types -->
      <SelectMenu
        v-else
        :items="filteredValueOptions"
        :model-value="selectedValue"
        @select="handleValueSelect"
      />
    </a-blur>
  </div>
</template>

// server/src/components/PropertyChip.tsx
import { createMemo, createSignal, For, onCleanup, onMount, Show } from "solid-js";
import { twMerge } from "tailwind-merge";
import type { Property } from "#documents/properties.ts";
import { CategoryBadge, type CategoryBadgeData } from "./CategoryBadge.tsx";
import { Icon, type IconName } from "./Icon.tsx";
import { SelectMenu, type SelectMenuItem, useSelectMenuKeys } from "./SelectMenu.tsx";
import "@atrium-ui/elements/blur";
import "@atrium-ui/elements/calendar";
import { useTranslation } from "#composeables/useTranslation.ts";

interface Props {
  label?: string;
  nameLabel?: string;
  valueLabels?: string[];
  icon?: IconName;
  iconSvg?: string;
  badge?: CategoryBadgeData;
  variant?: "default" | "special" | "quiet";
  readonly?: boolean;
  property?: Property | null;
  allowMultiple?: boolean;
  showTooltip?: boolean;
  tooltipPos?: "bottom";
  propertyValues?: (property: Property) => Promise<SelectMenuItem[]>;
  onUpdate?: (property: Property & { search: string }) => void;
  onDelete?: (property: Property) => void;
}

export function PropertyChip(props: Props) {
  const t = useTranslation();

  let inputElement: HTMLInputElement | undefined;

  const [valueOptions, setValueOptions] = createSignal<SelectMenuItem[]>([]);
  const [isEditPopoverOpen, setIsEditPopoverOpen] = createSignal(false);
  const [propertyName, setPropertyName] = createSignal(props.property?.name || "");
  const [selectedValue, setSelectedValue] = createSignal<string | string[] | undefined>(
    props.property?.value,
  );
  const [searchInput, setSearchInput] = createSignal("");
  const [dateValue, setDateValue] = createSignal("");

  const selectedValues = createMemo(() => {
    const value = selectedValue();
    if (Array.isArray(value)) return value;
    return value ? [value] : [];
  });

  const valueLabels = createMemo(() => props.valueLabels ?? []);

  const handleClick = async () => {
    const property = props.property; // solid-reactivity-ok: handler, re-reads per call
    if (props.readonly || !property) return;

    setIsEditPopoverOpen(!isEditPopoverOpen());
    setPropertyName(property.name);
    setSelectedValue(property.value);

    if (property.type === "date" && property.value && !Array.isArray(property.value)) {
      setDateValue(property.value);
    }

    await new Promise((resolve) => setTimeout(resolve, 25));

    if (property.type !== "date") {
      inputElement?.focus();

      props.propertyValues?.(property).then(setValueOptions);
    }
  };

  const filteredValueOptions = createMemo<SelectMenuItem[]>(() => {
    const searchTerm = searchInput().toLowerCase();
    const items = valueOptions().filter((item) =>
      item.label?.toLowerCase().includes(searchTerm),
    );
    if (items.length === 0) {
      return [
        {
          id: "__new__",
          label: t("Add {value}").replace("{value}", searchInput()),
          icon: "add",
        },
      ];
    }
    return items;
  });

  const handleExit = () => {
    setIsEditPopoverOpen(false);
    setSearchInput("");
    setDateValue("");
  };

  const handleValueSelect = (item: SelectMenuItem) => {
    const property = props.property; // solid-reactivity-ok: handler, re-reads per call
    if (!property) return;

    const itemValue = item.id === "__new__" ? searchInput().trim() : item.id;
    if (!itemValue) return;

    if (props.allowMultiple) {
      const nextValue = selectedValues().includes(itemValue)
        ? selectedValues().filter((value) => value !== itemValue)
        : [...selectedValues(), itemValue];

      setSelectedValue(nextValue);
      props.onUpdate?.({
        ...property,
        name: propertyName(),
        value: nextValue,
        search: searchInput(),
      });
      setSearchInput("");
      return;
    }

    // Picking the value the property already has is a no-op, not an edit: it
    // would patch the document and bump its revision for nothing.
    if (itemValue !== selectedValue()) {
      setSelectedValue(itemValue);
      props.onUpdate?.({
        ...property,
        name: propertyName(),
        value: itemValue,
        search: searchInput(),
      });
    }

    handleExit();
  };

  const valueKeys = useSelectMenuKeys(filteredValueOptions, handleValueSelect);

  const handleDateChange = (event: Event) => {
    const target = event.target as HTMLInputElement;
    const property = props.property; // solid-reactivity-ok: handler, re-reads per call
    if (!property) return;
    props.onUpdate?.({
      ...property,
      name: propertyName(),
      value: target.value,
      search: "",
    });
    handleExit();
  };

  const handleDelete = () => {
    const property = props.property; // solid-reactivity-ok: handler, re-reads per call
    if (!property) return;
    props.onDelete?.(property);
    handleExit();
  };

  onMount(() => {
    const onPointerDown = (e: PointerEvent) => {
      if (!(e.target as Element | null)?.closest("a-blur") && isEditPopoverOpen()) {
        handleExit();
      }
    };
    window.addEventListener("pointerdown", onPointerDown);
    onCleanup(() => window.removeEventListener("pointerdown", onPointerDown));
  });

  const chipClass = () => ({
    "text-interactive flex items-center gap-4xs py-7xs pl-5xs pr-4xs rounded-md border transition-colors": true,
    "bg-primary-50 hover:bg-primary-100 border-primary-100": props.variant === "special",
    "bg-background hover:bg-primary-10 border-primary-200": props.variant === "default",
    "h-7 border-transparent hover:bg-neutral-100": props.variant === "quiet",
    "cursor-pointer": !!props.property && !props.readonly,
    "cursor-default": !props.property || !!props.readonly,
  });

  const textClass = () =>
    props.variant === "quiet"
      ? "text-neutral-900"
      : props.variant === "special"
        ? "text-primary-700"
        : "text-primary-600";

  const iconClass = () =>
    props.variant === "quiet"
      ? "[&_svg]:text-neutral-700"
      : props.variant === "special"
        ? "[&_svg]:text-primary-700"
        : "[&_svg]:text-primary-600";

  return (
    <div class="relative">
      <Show
        when={props.property}
        fallback={
          <button
            type="button"
            classList={chipClass()}
            onClick={() => void handleClick()}
          >
            <Show when={props.icon}>
              <Icon
                class={`[&_svg]:inline [&_svg]:h-[18px] [&_svg]:w-[18px] ${iconClass()}`}
                name={props.icon}
              />
            </Show>
            <span class={textClass()}>
              {props.label}
            </span>
          </button>
        }
      >
        {(property) => (
          <button
            type="button"
            data-tooltip={
              props.showTooltip === false ? undefined : props.nameLabel || property().name
            }
            data-tooltip-pos={props.tooltipPos}
            classList={chipClass()}
            onClick={() => void handleClick()}
          >
            <Show
              when={props.badge}
              fallback={
                <Show
                  when={props.icon}
                  fallback={
                    <div class="flex h-[18px] w-[18px] items-center justify-center rounded-sm bg-primary-500" />
                  }
                >
                  <Icon
                    class={`[&_svg]:inline [&_svg]:h-[18px] [&_svg]:w-[18px] ${iconClass()}`}
                    name={props.icon}
                  />
                </Show>
              }
            >
              {(badge) => <CategoryBadge category={badge()} />}
            </Show>
            <Show
              when={valueLabels().length > 0}
              fallback={
                <span
                  class={twMerge(
                    "max-w-[150px] overflow-hidden text-ellipsis whitespace-nowrap capitalize",
                    textClass(),
                  )}
                >
                  {props.label}
                </span>
              }
            >
              <span class="flex min-w-0 max-w-[260px] items-center gap-5xs overflow-hidden">
                <For each={valueLabels()}>
                  {(valueLabel) => (
                    <span class="max-w-[110px] overflow-hidden text-ellipsis whitespace-nowrap rounded-sm bg-primary-50 px-5xs py-5xs text-primary-600 capitalize leading-none">
                      {valueLabel}
                    </span>
                  )}
                </For>
              </span>
            </Show>
          </button>
        )}
      </Show>

      <Show when={isEditPopoverOpen() && props.property}>
        {(property) => (
          <a-blur
            enabled
            on:exit={handleExit}
            class="absolute -top-4xs -left-4xs z-50 flex flex-col rounded-lg border border-neutral-100 bg-neutral-10 p-5xs shadow-large"
          >
            <div class="flex w-full items-center gap-4xs px-3xs">
              <Show when={props.badge}>
                {(badge) => <CategoryBadge category={badge()} />}
              </Show>
              <Show when={!props.badge && props.icon}>
                <Icon
                  class="h-[18px] w-[18px] text-neutral-950"
                  name={props.icon}
                  svg={props.iconSvg}
                />
              </Show>
              <div class="flex-1 overflow-hidden whitespace-nowrap py-5xs">
                <Show
                  when={property().type !== "date"}
                  fallback={<span class="text-interactive">{property().name}</span>}
                >
                  <input
                    ref={inputElement}
                    value={searchInput()}
                    onInput={(e) => setSearchInput(e.currentTarget.value)}
                    onKeyDown={valueKeys.onKeyDown}
                    class="w-[150px] border-none bg-transparent text-interactive outline-none"
                    placeholder={props.nameLabel || property().name || t("Property name")}
                  />
                </Show>
              </div>
              <button
                type="button"
                class="shrink-0 cursor-pointer text-neutral-950 transition-opacity hover:opacity-70"
                aria-label={t("Delete property")}
                onClick={handleDelete}
              >
                <Icon name="delete-element" class="h-[18px] w-[18px]" />
              </button>
            </div>

            <Show
              when={property().type === "date"}
              fallback={
                <SelectMenu
                  items={filteredValueOptions()}
                  value={selectedValue() ?? null}
                  activeIndex={valueKeys.activeIndex()}
                  onSelect={handleValueSelect}
                />
              }
            >
              <div>
                <a-calendar
                  attr:value={dateValue()}
                  on:change={handleDateChange}
                  class="w-[250px] p-2"
                />
              </div>
            </Show>
          </a-blur>
        )}
      </Show>
    </div>
  );
}
