// app/src/components/PropertyPopover.vue
<script setup lang="ts">
import { computed, onMounted, ref, watchEffect } from "vue";
import ButtonPrimary from "./ButtonPrimary.vue";
import SelectMenu from "./SelectMenu.vue";
import "@atrium-ui/elements/blur";
import { plusIcon } from "~/src/assets/icons.ts";
import type { SelectMenuItem } from "./SelectMenu.vue";

export type PropertyType = "text" | "select" | "date" | "user";

export interface Property {
  id: string;
  name: string;
  type: PropertyType;
  value?: string;
}

export interface SpaceProperty {
  name: string;
  type: string | null;
  values: string[];
}

interface Props {
  property?: Property | null;
  propertyTypes?: SelectMenuItem[];
  propertyValues?: SelectMenuItem[];
  spaceProperties?: SpaceProperty[];
  isOpen?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  property: null,
  propertyTypes: () => [],
  propertyValues: () => [],
  spaceProperties: () => [],
  isOpen: false,
});

const emit = defineEmits<{
  "update:isOpen": [value: boolean];
  create: [property: { name: string; type: string; value?: string }];
  update: [property: Property];
  delete: [propertyId: string];
  close: [];
}>();

type Mode = "select" | "create";

const mode = ref<Mode>("select");
const inputElement = ref();
const propertyName = ref("");
const selectedType = ref("");
const selectedPropertyName = ref("");

const spacePropertyItems = computed<SelectMenuItem[]>(() => {
  return [
    ...props.spaceProperties
      .filter((p) => {
        return !["title"].includes(p.name);
      })
      .map((sp) => ({
        id: sp.name,
        label: sp.name,
        icon: "",
      })),
    { id: "__new__", label: "New Property", icon: plusIcon },
  ];
});

const handleSpacePropertySelect = (item: SelectMenuItem) => {
  if (item.id === "__new__") {
    mode.value = "create";
    propertyName.value = "";
    selectedType.value = "";
  } else {
    selectedPropertyName.value = item.id;
    const spaceProperty = props.spaceProperties.find((sp) => sp.name === item.id);
    if (spaceProperty) {
      emit("create", {
        name: spaceProperty.name,
        type: spaceProperty.type || "text",
      });
    }
  }
};

const handleTypeSelect = (item: SelectMenuItem) => {
  selectedType.value = item.id;
};

const handleCreate = () => {
  if (!propertyName.value.trim() || !selectedType.value) {
    return;
  }

  emit("create", {
    name: propertyName.value.trim(),
    type: selectedType.value,
  });

  propertyName.value = "";
  selectedType.value = "";
  mode.value = "select";
};

const handleBack = () => {
  mode.value = "select";
  propertyName.value = "";
  selectedType.value = "";
};

watchEffect(async () => {
  if (props.isOpen === true) {
    mode.value = "select";
    propertyName.value = "";
    selectedType.value = "";
    selectedPropertyName.value = "";
  }
});

watchEffect(async () => {
  if (props.isOpen === true && mode.value === "create") {
    await new Promise((resolve) => setTimeout(resolve, 25));
    inputElement.value?.focus();
  }
});

const handleExit = () => {
  emit("update:isOpen", false);
};

onMounted(() => {
  window.addEventListener("pointerdown", (e) => {
    if (!e.target?.closest("a-blur") && props.isOpen === true) {
      handleExit();
    }
  });
});
</script>

<template>
  <a-blur v-if="isOpen" enabled @exit="handleExit" class="absolute -top-4xs -left-5xs bg-neutral-10 border border-neutral-100 rounded-lg p-5xs flex flex-col gap-4xs z-50 shadow-large min-w-[200px]">
    <!-- Select Mode: Choose existing property or create new -->
    <template v-if="mode === 'select'">
      <div class="text-size-small font-medium text-neutral-600 px-4xs mt-4xs">
        Add Property
      </div>
      <SelectMenu
        :items="spacePropertyItems"
        :model-value="selectedPropertyName"
        @select="handleSpacePropertySelect"
      />
    </template>

    <!-- Create Mode: Property name input and type selection -->
    <template v-else-if="mode === 'create'">
      <div class="flex items-center justify-between px-4xs mt-4xs">
        <div class="text-size-small font-medium text-neutral-600">
          New Property
        </div>
        <button @click="handleBack" class="text-size-small text-neutral-500 hover:text-neutral-700">
          Back
        </button>
      </div>

      <div class="flex flex-col gap-2.5 px-4xs w-full mt-4xs">
        <div class="flex-1 overflow-hidden">
          <input v-model="propertyName" ref="inputElement" class="bg-transparent border-none outline-none text-interactive w-full px-5xs" placeholder="Property name" />
        </div>
      </div>

      <SelectMenu
        :items="propertyTypes"
        :model-value="selectedType"
        @select="handleTypeSelect"
      />

      <ButtonPrimary
        text="Create"
        class="justify-center"
        :disabled="!propertyName.trim() || !selectedType"
        @click="handleCreate"
      />
    </template>
  </a-blur>
</template>

<style scoped>
button :deep(svg) {
  width: 18px;
  height: 18px;
  color: var(--color-neutral-950);
}
</style>

// server/src/components/PropertyPopover.tsx
import {
  createEffect,
  createMemo,
  createSignal,
  Match,
  onCleanup,
  onMount,
  Show,
  Switch,
} from "solid-js";
import { Button } from "./Button.tsx";
import { SelectMenu, type SelectMenuItem, useSelectMenuKeys } from "./SelectMenu.tsx";
import "@atrium-ui/elements/blur";
import type { Property, SpaceProperty } from "#documents/properties.ts";
import { useTranslation } from "#composeables/useTranslation.ts";

interface Props {
  property?: Property | null;
  propertyTypes?: SelectMenuItem[];
  propertyValues?: SelectMenuItem[];
  spaceProperties?: SpaceProperty[];
  isOpen?: boolean;
  onUpdateIsOpen?: (value: boolean) => void;
  onCreate?: (property: {
    name: string;
    type: string;
    value?: string | string[];
  }) => void;
  onUpdate?: (property: Property) => void;
  onDelete?: (propertyId: string) => void;
  onClose?: () => void;
}

type Mode = "select" | "create";

export function PropertyPopover(props: Props) {
  const t = useTranslation();

  const [mode, setMode] = createSignal<Mode>("select");
  let inputElement: HTMLInputElement | undefined;
  let searchElement: HTMLInputElement | undefined;
  const [search, setSearch] = createSignal("");
  const [propertyName, setPropertyName] = createSignal("");
  const [selectedType, setSelectedType] = createSignal("");
  const [selectedPropertyName, setSelectedPropertyName] = createSignal("");

  const spacePropertyItems = createMemo<SelectMenuItem[]>(() => [
    ...(props.spaceProperties ?? [])
      .filter(
        (p) =>
          p.name !== "title" && p.name.toLowerCase().includes(search().trim().toLowerCase()),
      )
      .map((sp) => ({
        id: sp.name,
        label: sp.name,
      })),
    { id: "__new__", label: t("New Property"), icon: "add" },
  ]);

  const handleSpacePropertySelect = (item: SelectMenuItem) => {
    if (item.id === "__new__") {
      setMode("create");
      setPropertyName(search().trim());
      setSelectedType("");
      return;
    }
    setSelectedPropertyName(item.id);
    const spaceProperty = (props.spaceProperties ?? []).find((sp) => sp.name === item.id);
    if (spaceProperty) {
      props.onCreate?.({
        name: spaceProperty.name,
        type: spaceProperty.type || "text",
      });
    }
  };

  const searchKeys = useSelectMenuKeys(spacePropertyItems, handleSpacePropertySelect);

  const handleCreate = () => {
    if (!propertyName().trim() || !selectedType()) return;

    props.onCreate?.({
      name: propertyName().trim(),
      type: selectedType(),
    });

    setPropertyName("");
    setSelectedType("");
    setMode("select");
  };

  const handleBack = () => {
    setMode("select");
    setPropertyName("");
    setSelectedType("");
  };

  createEffect(() => {
    if (props.isOpen === true) {
      setMode("select");
      setSearch("");
      setPropertyName("");
      setSelectedType("");
      setSelectedPropertyName("");
    }
  });

  createEffect(() => {
    if (props.isOpen === true) {
      const target = mode() === "create" ? inputElement : searchElement;
      const handle = setTimeout(() => target?.focus(), 25);
      onCleanup(() => clearTimeout(handle));
    }
  });

  const handleExit = () => {
    props.onUpdateIsOpen?.(false);
  };

  onMount(() => {
    const onPointerDown = (e: PointerEvent) => {
      if (!(e.target as Element | null)?.closest("a-blur") && props.isOpen === true) {
        handleExit();
      }
    };
    window.addEventListener("pointerdown", onPointerDown);
    onCleanup(() => window.removeEventListener("pointerdown", onPointerDown));
  });

  return (
    <Show when={props.isOpen}>
      <a-blur
        enabled
        on:exit={handleExit}
        class="absolute -top-4xs -left-5xs z-50 flex min-w-[200px] flex-col gap-4xs rounded-lg border border-neutral-100 bg-neutral-10 p-5xs shadow-large"
      >
        <Switch>
          <Match when={mode() === "select"}>
            <input
              ref={searchElement}
              value={search()}
              onInput={(e) => setSearch(e.currentTarget.value)}
              onKeyDown={searchKeys.onKeyDown}
              class="mt-4xs w-full border-none bg-transparent px-4xs text-interactive outline-none"
              placeholder={t("Search properties")}
            />
            <SelectMenu
              items={spacePropertyItems()}
              value={selectedPropertyName()}
              activeIndex={searchKeys.activeIndex()}
              onSelect={handleSpacePropertySelect}
            />
          </Match>

          <Match when={mode() === "create"}>
            <div class="mt-4xs flex items-center justify-between px-4xs">
              <div class="font-medium text-neutral-600 text-size-small">
                {t("New Property")}
              </div>
              <button
                type="button"
                onClick={handleBack}
                class="text-neutral-500 text-size-small hover:text-neutral-700"
              >
                {t("Back")}
              </button>
            </div>

            <div class="mt-4xs flex w-full flex-col gap-2.5 px-4xs">
              <div class="flex-1 overflow-hidden">
                <input
                  value={propertyName()}
                  onInput={(e) => setPropertyName(e.currentTarget.value)}
                  ref={inputElement}
                  class="w-full border-none bg-transparent px-5xs text-interactive outline-none"
                  placeholder={t("Property name")}
                />
              </div>
            </div>

            <SelectMenu
              items={props.propertyTypes ?? []}
              value={selectedType()}
              onSelect={(item) => setSelectedType(item.id)}
            />

            <Button
              text={t("Create")}
              class="justify-center"
              disabled={!propertyName().trim() || !selectedType()}
              onClick={handleCreate}
            />
          </Match>
        </Switch>
      </a-blur>
    </Show>
  );
}
