// app/src/components/SpaceSelector.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import homeIcon from "../assets/icons/home.svg?raw";
import settingsIcon from "../assets/icons/settings.svg?raw";
import ButtonPrimary from "./ButtonPrimary.vue";
import ButtonSecondary from "./ButtonSecondary.vue";
import Icon from "./Icon.vue";
import "@atrium-ui/elements/popover";
import { computed } from "vue";

// UI-specific Space interface for the selector
interface Space {
  id: string;
  name: string;
  members?: number;
  color?: string;
  logoSvg?: string;
}

interface Props {
  spaces?: Space[];
  spaceName?: string;
  modelValue?: string | null;
  canAccessSettings?: boolean;
  canCreateDocs?: boolean;
  loading?: boolean;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  "update:modelValue": [value: string];
  select: [space: Space];
  settings: [];
  create: [data: { name: string; slug: string; brandColor: string }];
  createDoc: [];
}>();

const currentSpace = computed(() => {
  if (props.modelValue) {
    return (
      props.spaces?.find((s) => s.id === props.modelValue) || props.spaces?.[0] || null
    );
  }
  return props.spaces?.[0] || null;
});

const handleSpaceSelect = (space: Space, event: MouseEvent) => {
  emit("update:modelValue", space.id);
  emit("select", space);
  (event.target as Element)?.dispatchEvent(new CustomEvent("exit", { bubbles: true }));
};

const handleSettings = (event: Event) => {
  event.stopPropagation();
  emit("settings");
};

const handleCreateClick = (e: Event) => {
  emit("create", {
    name: "",
    slug: "",
    brandColor: "",
  });
  e.target?.dispatchEvent(new CustomEvent("exit", { bubbles: true }));
};

const handleCreateDoc = (event: Event) => {
  event.stopPropagation();
  emit("createDoc");
};
</script>

<template>
  <div class="w-full flex gap-4">
    <div v-if="loading" class="flex items-start gap-3xs w-full px-4xs py-4xs">
      <div class="flex-none w-[2.375rem] aspect-square bg-neutral-200 rounded-md animate-pulse" />
      <div class="flex-1 flex flex-col gap-1">
        <div class="h-4 bg-neutral-200 rounded-sm animate-pulse w-25" />
        <div class="h-3 bg-neutral-100 rounded-sm animate-pulse w-16" />
      </div>
    </div>
    
    <a-popover-trigger v-else class="block w-full group relative z-10 overflow-hidden">
      <button slot="trigger" class="w-full">
        <div class="flex items-center gap-3xs px-4xs py-4xs rounded-md transition-colors hover:bg-primary-100 group-[[opened]]:bg-primary-50">
          <div class="flex w-full gap-3xs cursor-pointer">
            <!-- Space Icon -->
            <div class="flex-none w-[2.375rem] aspect-square rounded-md flex items-center justify-center bg-primary-500 overflow-hidden" :style="{ background: currentSpace?.color }">
              <div v-if="currentSpace?.logoSvg && currentSpace.logoSvg.startsWith('<')" v-html="currentSpace.logoSvg" class="text-white" />
              <img v-else-if="currentSpace?.logoSvg" :src="currentSpace.logoSvg" class="w-full h-full object-cover" />
              <div v-else v-html="homeIcon" class="text-white" />
            </div>
  
            <!-- Space Info -->
            <div class="relative h-9 flex-1 text-left">
              <div class="left-0 w-full h-full">
                <div class="whitespace-nowrap text-base leading-[1.35em] font-normal text-foreground overflow-hidden text-ellipsis">
                  {{ currentSpace?.name || spaceName || 'Select Space' }}
                </div>
                <div class="whitespace-nowrap text-label leading-[1.35em] text-neutral-600 overflow-hidden text-ellipsis">
                  {{ currentSpace?.members || 0 }} Members
                </div>
              </div>
            </div>
          </div>
        </div>
      </button>
  
      <a-popover class="group" placements="bottom-start">
        <div class="w-max opacity-0 transition-opacity duration-100 group-[[enabled]]:opacity-100 min-w-(--trigger-width)">
          <div class="bg-neutral-50 border border-neutral-100 rounded-lg origin-top scale-95 transition-all shadow-xl duration-150 group-[[enabled]]:scale-100 max-h-[500px] overflow-y-auto">
            <div class="p-[4px] flex flex-col gap-[4px]">
              <!-- Space List -->
              <button
                v-for="space in spaces"
                :key="space.id"
                type="button"
                @click="handleSpaceSelect(space, $event)"
                class="flex items-center gap-2.5 px-4xs py-4xs w-full rounded-md transition-colors hover:bg-neutral-100 text-left"
                :class="{
                  'bg-primary-100': space.id === modelValue,
                }"
              >
                <div class="w-6 h-6 rounded-sm overflow-hidden flex items-center justify-center" :style="{ background: space.color || '#6366f1' }">
                  <div v-if="space.logoSvg && space.logoSvg.startsWith('<')" v-html="space.logoSvg" class="block text-white" />
                  <img v-else-if="space.logoSvg" :src="space.logoSvg" class="block object-contain" />
                  <div v-else v-html="homeIcon" class="text-white [&>svg]:w-4 [&>svg]:h-4 [&>svg]:object-contain" />
                </div>
                <div class="flex-1 min-w-0">
                  <div class="text-interactive font-medium text-foreground truncate">
                    {{ space.name }}
                  </div>
                </div>
              </button>
  
              <!-- Create Space Button -->
              <div class="border-t border-neutral-100 pt-[4px] mt-[4px]">
                <button
                  type="button"
                  @click="handleCreateClick"
                  class="flex items-center gap-2.5 px-3xs py-4xs w-full rounded-md transition-colors hover:bg-neutral-100 text-neutral-500"
                >
                  <Icon name="plus" />
                  <span class="text-interactive leading-none font-medium">
                    Create new space
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </a-popover>
    </a-popover-trigger>
    
    <!-- Action Buttons -->
    <div class="@max-sm:hidden flex items-center gap-2xs flex-none py-5xs pr-3xs">
      <ButtonSecondary v-if="props.canCreateDocs" aria-label="New document" @click="handleCreateDoc">
        <Icon name="plus" class="-mx-1" />
      </ButtonSecondary>
    </div>
  </div>
</template>

// server/src/components/SpaceSelector.tsx
import { Index, Show } from "solid-js";
import { memberCountLabel } from "#utils/utils.ts";
import { Icon } from "./Icon.tsx";
import { SpaceLogo } from "./SpaceLogo.tsx";
import "@atrium-ui/elements/popover";
import { useLocale, useTranslation } from "#composeables/useTranslation.ts";

export interface SelectorSpace {
  id: string;
  name: string;
  members?: number;
  color?: string;
  logoSvg?: string;
  pinned?: boolean;
}

interface Props {
  /**
   * The spaces to list, already chosen by `spaceSelectorSlots` — the dropdown
   * shows what it is given and links to the overview for the rest.
   */
  spaces?: SelectorSpace[];
  /** The space the trigger names, which need not be one of the listed ones. */
  current?: SelectorSpace | null;
  allSpacesHref?: string;
  canCreateSpaces?: boolean;
  loading?: boolean;
  onSelect?: (space: SelectorSpace) => void;
  onCreate?: () => void;
}

function dismissPopover(target: EventTarget | null) {
  (target as Element | null)?.dispatchEvent(new CustomEvent("exit", { bubbles: true }));
}

export function SpaceSelector(props: Props) {
  const t = useTranslation();
  const lang = useLocale();

  return (
    <div class="flex w-full gap-4">
      <Show
        when={!props.loading}
        fallback={
          <div class="flex w-full items-start gap-3xs px-4xs py-4xs">
            <div class="aspect-square w-[2.375rem] flex-none animate-pulse rounded-md bg-skeleton-strong" />
            <div class="flex flex-1 flex-col gap-1">
              <div class="h-4 w-25 animate-pulse rounded-sm bg-skeleton-strong" />
              <div class="h-3 w-16 animate-pulse rounded-sm bg-skeleton" />
            </div>
          </div>
        }
      >
        <a-popover-trigger class="group relative z-10 block w-full overflow-hidden">
          <button
            type="button"
            slot="trigger"
            class="w-full"
            attr:aria-label={t("Select Space")}
          >
            <div class="flex items-center gap-3xs rounded-md px-4xs py-4xs transition-colors hover:bg-primary-100 group-[[opened]]:bg-primary-50">
              <div class="flex w-full cursor-pointer gap-3xs">
                <div
                  class="flex aspect-square w-[2.375rem] flex-none items-center justify-center overflow-hidden rounded-md bg-primary-500"
                  // `background-color`, not the `background` shorthand: the
                  // shorthand also accepts `url()`, which turns a stored brand
                  // colour into a request to whatever host it names.
                  style={{ "background-color": props.current?.color }}
                >
                  <SpaceLogo
                    logoSvg={props.current?.logoSvg}
                    class="h-full w-full object-cover"
                  />
                </div>

                <div class="relative h-9 flex-1 text-left">
                  <div class="left-0 h-full w-full">
                    <div class="overflow-hidden text-ellipsis whitespace-nowrap font-normal text-foreground text-size-medium leading-[1.35em]">
                      {props.current?.name || t("Select Space")}
                    </div>
                    <div class="overflow-hidden text-ellipsis whitespace-nowrap text-neutral-600 text-size-normal leading-[1.35em]">
                      {memberCountLabel(props.current?.members, lang)}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </button>

          <a-popover class="group" placements="bottom-start">
            <div class="w-max min-w-(--trigger-width) opacity-0 transition-opacity duration-100 group-[[enabled]]:opacity-100">
              <div class="max-h-[500px] origin-top scale-95 overflow-y-auto rounded-lg border border-neutral-100 bg-neutral-50 shadow-xl transition-all duration-150 group-[[enabled]]:scale-100">
                <div class="flex flex-col gap-[4px] p-[4px]">
                  <Index each={props.spaces}>
                    {(space) => (
                      <button
                        type="button"
                        onClick={(event) => {
                          props.onSelect?.(space());
                          dismissPopover(event.target);
                        }}
                        class="flex w-full items-center gap-2.5 rounded-md px-4xs py-4xs text-left transition-colors hover:bg-neutral-100"
                        classList={{
                          "bg-primary-100": space().id === props.current?.id,
                        }}
                      >
                        <div
                          class="flex h-6 w-6 items-center justify-center overflow-hidden rounded-sm"
                          style={{ "background-color": space().color || "#6366f1" }}
                        >
                          <SpaceLogo
                            logoSvg={space().logoSvg}
                            class="block object-contain"
                            fallbackClass="text-white [&>svg]:w-4 [&>svg]:h-4 [&>svg]:object-contain"
                          />
                        </div>
                        <div class="min-w-0 flex-1">
                          <div class="truncate font-medium text-foreground text-size-small">
                            {space().name}
                          </div>
                        </div>
                        <Show when={space().pinned}>
                          <Icon
                            name="pin-to-home"
                            class="h-3.5 w-3.5 flex-none text-neutral-500"
                          />
                        </Show>
                      </button>
                    )}
                  </Index>

                  <div class="mt-[4px] flex flex-col gap-[4px] border-neutral-100 border-t pt-[4px]">
                    <Show when={props.allSpacesHref}>
                      {(href) => (
                        <a
                          href={href()}
                          class="flex w-full items-center gap-2.5 rounded-md px-3xs py-4xs text-neutral-500 transition-colors hover:bg-neutral-100"
                        >
                          <Icon name="grid-grid" />
                          <span class="font-medium text-size-small leading-none">
                            {t("All spaces")}
                          </span>
                        </a>
                      )}
                    </Show>

                    <Show when={props.canCreateSpaces}>
                      <button
                        type="button"
                        onClick={(event) => {
                          props.onCreate?.();
                          dismissPopover(event.target);
                        }}
                        class="flex w-full items-center gap-2.5 rounded-md px-3xs py-4xs text-neutral-500 transition-colors hover:bg-neutral-100"
                      >
                        <Icon name="add" />
                        <span class="font-medium text-size-small leading-none">
                          {t("Create new Space")}
                        </span>
                      </button>
                    </Show>
                  </div>
                </div>
              </div>
            </div>
          </a-popover>
        </a-popover-trigger>
      </Show>
    </div>
  );
}
