// app/src/components/SpaceActivityFeed.vue
<script setup lang="ts">
import { computed } from "vue";
import { type AuditLog, api } from "#api/client.ts";
import { chevronRightThinIcon, documentIcon, usersIcon } from "#assets/icons.ts";
import { useQuery } from "#composeables/query.ts";
import { useSpace } from "#composeables/useSpace.ts";
import {
  getActivityBucketLabel,
  getActivityDate,
  getAuditEventAction,
  getEntryChangeLabel,
  isPermissionEvent,
} from "#utils/auditActivity.ts";
import { t } from "#utils/lang.ts";
import { userDisplayName } from "#utils/userDisplay.ts";
import { normalizeTimestamp, spacePath } from "#utils/utils.ts";
import "./AvatarElement.ts";

interface User {
  id: string;
  name: string;
  email?: string;
  image?: string | null;
}

interface Document {
  id: string;
  slug: string;
  type?: string;
}

interface CompactActivityGroup {
  id: string;
  userId: string | null;
  time: string | Date;
  items: AuditLog[];
  date: string;
}

interface CompactActivityBatch {
  id: string;
  docId: string;
  action: string;
  /** Permission batches describe membership, not a document. */
  isPermission: boolean;
  entries: AuditLog[];
}

const props = withDefaults(
  defineProps<{
    spaceId: string;
    limit?: number;
  }>(),
  {
    limit: 10,
  },
);

const { currentSpace } = useSpace();

const {
  data,
  isPending: isLoading,
  error: queryError,
} = useQuery({
  queryKey: computed(() => ["space_activity", props.spaceId, props.limit]),
  queryFn: async () => {
    const [logsData, membersData] = await Promise.all([
      api.auditLogs.get(props.spaceId, { limit: props.limit }),
      api.spaceMembers.get(props.spaceId),
    ]);

    const activities = logsData.auditLogs;

    const usersMap = new Map<string, User>();
    for (const member of membersData) {
      if (member.user) usersMap.set(member.user.id, member.user);
    }

    const docIds = new Set<string>();
    for (const activity of activities) {
      if (activity.docId && activity.docId !== props.spaceId) {
        docIds.add(activity.docId);
      }
    }

    const docsMap = new Map<string, Document>();
    await Promise.all(
      Array.from(docIds).map(async (docId) => {
        try {
          const doc = await api.document.get(props.spaceId, docId);
          docsMap.set(docId, doc);
        } catch {
          // best-effort
        }
      }),
    );

    return { activities, usersMap, docsMap };
  },
});

const activities = computed(() => data.value?.activities ?? []);
const error = computed(() => queryError.value?.message ?? null);

function getUser(userId?: string | null): User | undefined {
  if (!userId) return undefined;
  return data.value?.usersMap.get(userId);
}

function getUserName(userId?: string | null): string {
  return userDisplayName(getUser(userId), userId);
}

function getDocumentName(docId: string): string {
  if (docId === props.spaceId) return t("Home");
  return data.value?.docsMap.get(docId)?.slug ?? t("Unknown document");
}

function getDocumentHref(docId: string): string | undefined {
  if (docId === props.spaceId) return spacePath(currentSpace.value?.slug, "/");
  const doc = data.value?.docsMap.get(docId);
  if (!doc?.slug) return undefined;
  return spacePath(currentSpace.value?.slug, `/doc/${doc.slug}`);
}

function getEntryAction(entry: AuditLog): string {
  return getAuditEventAction(entry.event);
}

function getCompactActivityBatches(items: AuditLog[]): CompactActivityBatch[] {
  const batches: CompactActivityBatch[] = [];
  const batchMap = new Map<string, CompactActivityBatch>();

  for (const entry of items) {
    if (entry.event === "view") continue;

    const action = getEntryAction(entry);
    const isPermission = isPermissionEvent(entry.event);
    const key = `${isPermission ? "permissions" : entry.docId}:${action}`;
    let batch = batchMap.get(key);

    if (!batch) {
      batch = { id: key, docId: entry.docId, action, isPermission, entries: [] };
      batchMap.set(key, batch);
      batches.push(batch);
    }

    batch.entries.push(entry);
  }

  return batches;
}

function getBatchChanges(batch: CompactActivityBatch): string[] {
  const labels: string[] = [];
  const seen = new Set<string>();

  for (const entry of batch.entries) {
    const label = getEntryChangeLabel(entry);
    if (!label || seen.has(label)) continue;
    seen.add(label);
    labels.push(label);
  }

  return labels;
}

function getBatchChangeCount(batch: CompactActivityBatch): number {
  return Math.max(getBatchChanges(batch).length, batch.entries.length);
}

function getChangeCountLabel(count: number): string {
  return `${count} ${count === 1 ? t("change") : t("changes")}`;
}

/**
 * Secondary line of a card: a change count for document work, and the actual
 * membership changes ("Invited: Jane (editor)") for permission entries.
 */
function getBatchSummary(batch: CompactActivityBatch): string {
  if (batch.isPermission) {
    const changes = getBatchChanges(batch);
    if (changes.length) return changes.join(", ");
  }
  return getChangeCountLabel(getBatchChangeCount(batch));
}

function activityTimeMs(dateString: string | Date): number {
  try {
    return normalizeTimestamp(dateString as string).getTime();
  } catch {
    return 0;
  }
}

const activityGroups = computed((): CompactActivityGroup[] => {
  const groups: CompactActivityGroup[] = [];
  let groupIndex = 0;

  for (const entry of activities.value) {
    const date = getActivityDate(entry.createdAt as string);
    const last = groups[groups.length - 1];
    const userId = entry.userId ?? null;
    const sameUser = last && last.userId === userId;
    const sameDate = last && last.date === date;
    const sameActivityWindow =
      last &&
      Math.abs(activityTimeMs(last.time) - activityTimeMs(entry.createdAt)) <= 900000;

    if (sameUser && sameDate && sameActivityWindow) {
      last.items.push(entry);
    } else {
      groups.push({
        id: `group-${groupIndex++}`,
        userId,
        time: entry.createdAt,
        items: [entry],
        date,
      });
    }
  }

  return groups;
});
</script>

<template>
  <div class="space-y-4">
    <div class="flex items-center justify-between">
      <h2 class="text-size-label">{{ t("Space Activity") }}</h2>
    </div>

    <div v-if="error" class="text-red-600 p-4 border border-red-200 rounded-sm bg-red-50">
      {{ error }}
    </div>

    <div v-else-if="isLoading" class="@container space-y-4 animate-pulse">
      <template v-for="i in 3" :key="`skeleton-${i}`">
        <div
          v-if="i === 1 || i === 2"
          class="h-4 rounded-sm bg-neutral-100 px-1"
          :class="i === 1 ? 'w-24' : 'w-20'"
        />

        <div class="rounded-lg border border-neutral-100 bg-neutral-10 px-3.5 py-3">
          <div
            class="grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-center gap-x-4 gap-y-3 @md:grid-cols-[minmax(0,1fr)_minmax(10rem,42%)_auto]"
          >
            <div class="flex min-w-0 items-center gap-3">
              <div class="h-10 w-10 shrink-0 rounded-full bg-neutral-200" />

              <div class="min-w-0 space-y-2">
                <div class="flex items-center gap-2">
                  <div class="h-4 w-20 rounded-sm bg-neutral-200" />
                  <div class="h-4 w-16 rounded-sm bg-neutral-100" />
                </div>
                <div class="h-3.5 w-16 rounded-sm bg-neutral-100" />
              </div>
            </div>

            <div
              class="col-start-1 row-start-2 flex min-w-0 items-center gap-3 @md:col-auto @md:row-auto"
            >
              <div
                class="svg-icon flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-neutral-100 p-2 text-neutral-500"
                v-html="documentIcon"
              />
              <div class="h-4 w-32 rounded-sm bg-neutral-100" />
            </div>

            <div
              class="svg-icon col-start-2 row-span-2 h-5 w-5 shrink-0 text-neutral-400 @md:col-auto @md:row-auto"
              v-html="chevronRightThinIcon"
            />
          </div>
        </div>
      </template>
    </div>

    <div v-else-if="activities.length === 0" class="text-center py-8 text-neutral-400">
      {{ t("No recent activity") }}
    </div>

    <div v-else class="@container space-y-4">
      <template v-for="(group, index) in activityGroups" :key="group.id">
        <div
          v-if="index === 0 || getActivityBucketLabel(activityGroups[index - 1].time) !== getActivityBucketLabel(group.time)"
          class="px-1 text-size-small font-medium text-neutral-500"
        >
          {{ getActivityBucketLabel(group.time) }}
        </div>

        <!-- biome-ignore lint/a11y/useValidAnchor: href is supplied by Vue's dynamic binding. -->
        <a
          v-for="batch in getCompactActivityBatches(group.items)"
          :key="batch.id"
          :href="batch.isPermission ? undefined : getDocumentHref(batch.docId)"
          class="block rounded-lg border border-neutral-100 bg-neutral-10 px-3.5 py-3 transition-colors hover:bg-neutral-50"
        >
          <div
            class="grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-center gap-x-4 gap-y-3 @md:grid-cols-[minmax(0,1fr)_minmax(10rem,42%)_auto]"
          >
            <div class="flex min-w-0 items-center gap-3">
              <vektor-avatar
                size="medium"
                :user-id="group.userId ?? undefined"
                :user="getUser(group.userId)"
              />

              <div class="min-w-0">
                <div
                  class="flex min-w-0 items-baseline gap-1 text-size-medium leading-medium"
                >
                  <span class="font-semibold text-neutral-900">
                    {{ getUserName(group.userId) }}
                  </span>
                  <span class="shrink-0 text-neutral-700">{{ batch.action }}</span>
                </div>
                <div class="mt-0.5 text-size-small font-medium text-neutral-500">
                  {{ getBatchSummary(batch) }}
                </div>
              </div>
            </div>

            <div
              class="col-start-1 row-start-2 flex min-w-0 items-center gap-3 @md:col-auto @md:row-auto"
            >
              <div
                class="svg-icon flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-neutral-100 p-2 text-neutral-500"
                v-html="batch.isPermission ? usersIcon : documentIcon"
              />
              <div class="min-w-0 truncate text-size-medium text-neutral-700">
                {{ batch.isPermission ? t("Members") : getDocumentName(batch.docId) }}
              </div>
            </div>

            <!-- Permission cards are not links, but keep the column so the
                 middle column stays aligned with the document cards. -->
            <div
              class="svg-icon col-start-2 row-span-2 h-5 w-5 shrink-0 text-neutral-400 @md:col-auto @md:row-auto"
              :class="{ invisible: batch.isPermission }"
              v-html="chevronRightThinIcon"
            />
          </div>
        </a>
      </template>
    </div>
  </div>
</template>

// server/src/components/SpaceActivityFeed.tsx
import { createMemo, For, Index, mergeProps, Show } from "solid-js";
import { twMerge } from "tailwind-merge";
import type { AuditLog } from "#api/client.ts";
import { useSpaceActivity } from "#composeables/useSpaceActivity.ts";
import {
  type ActivityGroup,
  getAuditEventAction,
  getEntryChangeLabel,
  groupActivityEntries,
  isPermissionEvent,
} from "#utils/auditActivity.ts";
import { normalizeTimestamp } from "#utils/datetime.ts";
import { t } from "#utils/lang.ts";
import "./AvatarElement.ts";
import { useLocale, useTranslation } from "#composeables/useTranslation.ts";
import { Icon } from "./Icon.tsx";

interface CompactActivityBatch {
  id: string;
  docId: string;
  action: string;
  isPermission: boolean;
  entries: AuditLog[];
}

interface Props {
  spaceId: string;
  limit?: number;
}

function getCompactActivityBatches(
  items: AuditLog[],
  lang: string,
): CompactActivityBatch[] {
  const batches: CompactActivityBatch[] = [];
  const batchMap = new Map<string, CompactActivityBatch>();

  for (const entry of items) {
    if (entry.event === "view") continue;

    const action = getAuditEventAction(entry.event, lang);
    const isPermission = isPermissionEvent(entry.event);
    const key = `${isPermission ? "permissions" : entry.docId}:${action}`;
    let batch = batchMap.get(key);

    if (!batch) {
      batch = { id: key, docId: entry.docId, action, isPermission, entries: [] };
      batchMap.set(key, batch);
      batches.push(batch);
    }

    batch.entries.push(entry);
  }

  return batches;
}

function getBatchChanges(batch: CompactActivityBatch, lang: string): string[] {
  const labels: string[] = [];
  const seen = new Set<string>();

  for (const entry of batch.entries) {
    const label = getEntryChangeLabel(entry, lang);
    if (!label || seen.has(label)) continue;
    seen.add(label);
    labels.push(label);
  }

  return labels;
}

function getBatchChangeCount(batch: CompactActivityBatch, lang: string): number {
  return Math.max(getBatchChanges(batch, lang).length, batch.entries.length);
}

function getChangeCountLabel(lang: string, count: number): string {
  return `${count} ${count === 1 ? t("change", lang) : t("changes", lang)}`;
}

function getBatchSummary(batch: CompactActivityBatch, lang: string): string {
  if (batch.isPermission) {
    const changes = getBatchChanges(batch, lang);
    if (changes.length) return changes.join(", ");
  }
  return getChangeCountLabel(lang, getBatchChangeCount(batch, lang));
}

function activityTimeMs(dateString: string | Date): number {
  try {
    return normalizeTimestamp(dateString as string).getTime();
  } catch {
    return 0;
  }
}

function withinActivityWindow(entry: AuditLog, group: ActivityGroup): boolean {
  return Math.abs(activityTimeMs(group.time) - activityTimeMs(entry.createdAt)) <= 900000;
}

export function SpaceActivityFeed(props: Props) {
  const t = useTranslation();
  const lang = useLocale();

  const merged = mergeProps({ limit: 10 }, props);

  const {
    activities,
    isLoading,
    error,
    getUser,
    getUserName,
    getDocumentName,
    getDocumentHref,
  } = useSpaceActivity(
    () => merged.spaceId,
    lang,
    () => merged.limit,
  );

  const activityGroups = createMemo(() =>
    groupActivityEntries(activities(), withinActivityWindow, lang),
  );

  return (
    <div class="space-y-4">
      <div class="flex items-center justify-between">
        <h2 class="text-neutral-500 text-size-large leading-large">
          {t("Space Activity")}
        </h2>
      </div>

      <Show when={error()}>
        <div class="rounded-sm border border-red-200 bg-red-50 p-4 text-red-600">
          {error()}
        </div>
      </Show>

      <Show when={!error() && isLoading()}>
        <div class="@container animate-pulse space-y-4">
          <Index each={[1, 2, 3]}>
            {(i) => (
              <>
                <Show when={i() < 2}>
                  <div
                    class="h-4 rounded-sm bg-neutral-100 px-1"
                    classList={{ "w-24": i() === 0, "w-20": i() === 1 }}
                  />
                </Show>

                <div class="divide-y divide-neutral-100 overflow-hidden rounded-lg border border-neutral-100 bg-neutral-10">
                  <div class="px-3.5 py-3">
                    <div class="grid min-w-0 @md:grid-cols-[minmax(0,1fr)_minmax(10rem,42%)_auto] grid-cols-[minmax(0,1fr)_auto] items-center gap-x-4 gap-y-3">
                      <div class="flex min-w-0 items-center gap-3">
                        <div class="h-10 w-10 shrink-0 rounded-full bg-neutral-200" />

                        <div class="min-w-0 space-y-2">
                          <div class="flex items-center gap-2">
                            <div class="h-4 w-20 rounded-sm bg-neutral-200" />
                            <div class="h-4 w-16 rounded-sm bg-neutral-100" />
                          </div>
                          <div class="h-3.5 w-16 rounded-sm bg-neutral-100" />
                        </div>
                      </div>

                      <div class="@md:col-auto col-start-1 @md:row-auto row-start-2 flex min-w-0 items-center gap-3">
                        <Icon
                          class="h-8 w-8 shrink-0 rounded-md bg-neutral-100 p-2 text-neutral-500"
                          name="document"
                        />
                        <div class="h-4 w-32 rounded-sm bg-neutral-100" />
                      </div>

                      <Icon
                        class="@md:col-auto col-start-2 @md:row-auto row-span-2 h-5 w-5 shrink-0 text-neutral-400"
                        name="chevron-right-thin"
                      />
                    </div>
                  </div>
                </div>
              </>
            )}
          </Index>
        </div>
      </Show>

      <Show when={!error() && !isLoading() && activities().length === 0}>
        <div class="py-8 text-center text-neutral-400">{t("No recent activity")}</div>
      </Show>

      <Show when={!error() && !isLoading() && activities().length > 0}>
        <div class="@container space-y-4">
          <For each={activityGroups()}>
            {(group) => (
              <>
                <Show when={group.showBucket}>
                  <div class="px-1 font-medium text-neutral-500 text-size-small">
                    {group.bucketLabel}
                  </div>
                </Show>

                <div class="divide-y divide-neutral-100 overflow-hidden rounded-lg border border-neutral-100 bg-neutral-10">
                  <For each={getCompactActivityBatches(group.items, lang)}>
                    {(batch) => (
                      <a
                        href={
                          batch.isPermission ? undefined : getDocumentHref(batch.docId)
                        }
                        class="block px-3.5 py-3 transition-colors hover:bg-neutral-50"
                      >
                        <div class="grid min-w-0 @md:grid-cols-[minmax(0,1fr)_minmax(10rem,42%)_auto] grid-cols-[minmax(0,1fr)_auto] items-center gap-x-4 gap-y-3">
                          <div class="flex min-w-0 items-center gap-3">
                            <vektor-avatar
                              size="medium"
                              attr:user-id={group.userId ?? undefined}
                              prop:user={getUser(group.userId)}
                            />

                            <div class="min-w-0">
                              <div class="flex min-w-0 items-baseline gap-1 text-size-medium leading-medium">
                                <span class="font-semibold text-neutral-900">
                                  {getUserName(group.userId)}
                                </span>
                                <span class="shrink-0 text-neutral-700">
                                  {batch.action}
                                </span>
                              </div>
                              <div class="mt-0.5 font-medium text-neutral-500 text-size-small">
                                {getBatchSummary(batch, lang)}
                              </div>
                            </div>
                          </div>

                          <div class="@md:col-auto col-start-1 @md:row-auto row-start-2 flex min-w-0 items-center gap-3">
                            <Icon
                              class="h-8 w-8 shrink-0 rounded-md bg-neutral-100 p-2 text-neutral-500"
                              name={batch.isPermission ? "users" : "document"}
                            />
                            <div class="min-w-0 truncate text-neutral-700 text-size-medium">
                              {batch.isPermission
                                ? t("Members")
                                : getDocumentName(batch.docId)}
                            </div>
                          </div>

                          <Icon
                            class={twMerge(
                              "@md:col-auto col-start-2 @md:row-auto row-span-2 h-5 w-5 shrink-0 text-neutral-400",
                              batch.isPermission && "invisible",
                            )}
                            name="chevron-right-thin"
                          />
                        </div>
                      </a>
                    )}
                  </For>
                </div>
              </>
            )}
          </For>
        </div>
      </Show>
    </div>
  );
}
