// app/src/components/UserPreferencesPanel.vue
<script setup lang="ts">
import { withViewTransition } from "#utils/viewTransition.ts";
import Button from "./Button.vue";
import "@atrium-ui/elements/color-picker";
import "@atrium-ui/elements/popover";
import { computed, nextTick, onMounted, ref, watch } from "vue";
import {
  api,
  type OAuthIntegrationConnection,
  type OAuthIntegrationProvider,
} from "#api/client.ts";
import { chevronLeftLargeIcon } from "#assets/icons.ts";
import { useCanvasCursorColor } from "#composeables/useCanvasCursorColor.ts";
import { useCosmetics } from "#composeables/useCosmetics.ts";
import { useSpace } from "#composeables/useSpace.ts";
import { useUserProfile } from "#composeables/useUserProfile.ts";
import { getAvatarColor } from "#utils/avatarColor.ts";
import { t } from "#utils/lang.ts";
import {
  applyThemePreference,
  getStoredThemePreference,
  THEME_STORAGE_KEY,
  type ThemePreference,
} from "#utils/themePreference.ts";
import CosmeticsPanel from "./cosmetics/CosmeticsPanel.vue";
import SettingsLayout from "./SettingsLayout.vue";
import SwitchToggle from "./SwitchToggle.vue";

const themePreference = ref<ThemePreference>("system");
const currentUser = useUserProfile();
const {
  inventory: cosmeticInventory,
  loadout: cosmeticLoadout,
  appearance: cosmeticAppearance,
  equip: equipCosmetic,
} = useCosmetics();
// `null` means "automatic" — the presence color follows the user's avatar.
const { cursorColorOverride, setCursorColor, clearCursorColor } = useCanvasCursorColor();
const automaticCursorColor = computed(() => getAvatarColor(currentUser.value?.id));
const cursorColor = computed(
  () => cursorColorOverride.value ?? automaticCursorColor.value,
);
const isAutomaticCursorColor = computed(() => cursorColorOverride.value === null);
const integrationProviders: OAuthIntegrationProvider[] = ["gitlab", "youtrack"];
const integrationConnections = ref<OAuthIntegrationConnection[]>([]);
const isLoadingIntegrations = ref(false);
const integrationsError = ref<string | null>(null);
const integrationsMessage = ref<string | null>(null);
const connectingProvider = ref<OAuthIntegrationProvider | null>(null);
const disconnectingProvider = ref<OAuthIntegrationProvider | null>(null);
const spaceNotificationsMuted = ref(false);
const isLoadingNotificationPreference = ref(false);
const isUpdatingNotificationPreference = ref(false);
const notificationPreferenceError = ref<string | null>(null);
const { currentSpace } = useSpace();

const emit = defineEmits<{
  close: [];
}>();

const tabs = [
  { id: "appearance", label: t("Appearance") },
  { id: "cosmetics", label: t("Cosmetics") },
  { id: "notifications", label: t("Notifications") },
  { id: "integrations", label: t("Integrations") },
];
const themeOptions: { value: ThemePreference; label: string; swatchClass: string }[] = [
  {
    value: "system",
    label: t("System"),
    swatchClass:
      "bg-[linear-gradient(135deg,#ffffff_0%,#ffffff_48%,#222222_52%,#222222_100%)]",
  },
  { value: "light", label: t("Light"), swatchClass: "bg-[#fff5b8]" },
  { value: "dark", label: t("Dark"), swatchClass: "bg-[#252525]" },
];

const activeSpaceName = computed(() => currentSpace.value?.name || null);

const integrationProviderDetails: Record<
  OAuthIntegrationProvider,
  { label: string; description: string; initial: string; iconClass: string }
> = {
  gitlab: {
    label: "GitLab",
    description: t("Connect GitLab to work with your projects and issues."),
    initial: "G",
    iconClass: "bg-[#fc6d26]",
  },
  youtrack: {
    label: "YouTrack",
    description: t("Connect YouTrack to work with your issues and projects."),
    initial: "Y",
    iconClass: "bg-[#4c57e8]",
  },
};

const integrationCards = computed(() =>
  integrationProviders.map((provider) => ({
    provider,
    connection:
      integrationConnections.value.find(
        (connection) => connection.provider === provider,
      ) ?? null,
    ...integrationProviderDetails[provider],
  })),
);

const applyThemePreferenceWithTransition = (preference: ThemePreference) => {
  const updateTheme = async () => {
    themePreference.value = preference;
    applyThemePreference(preference);
    await nextTick();
  };
  withViewTransition(updateTheme);
};

const setThemePreference = (preference: ThemePreference) => {
  localStorage.setItem(THEME_STORAGE_KEY, preference);
  applyThemePreferenceWithTransition(preference);
};

const loadIntegrations = async () => {
  if (!currentSpace.value?.id) {
    integrationConnections.value = [];
    return;
  }

  isLoadingIntegrations.value = true;
  integrationsError.value = null;

  try {
    const response = await api.integrations.get(currentSpace.value.id);
    integrationConnections.value = response.connections || [];
  } catch (error) {
    integrationsError.value =
      error instanceof Error ? error.message : t("Failed to load integrations");
    integrationConnections.value = [];
  } finally {
    isLoadingIntegrations.value = false;
  }
};

const loadNotificationPreference = async () => {
  if (!currentSpace.value?.id) {
    spaceNotificationsMuted.value = false;
    return;
  }

  isLoadingNotificationPreference.value = true;
  notificationPreferenceError.value = null;

  try {
    const response = await api.space.getNotificationPreference(currentSpace.value.id);
    spaceNotificationsMuted.value = response.muted;
  } catch (error) {
    notificationPreferenceError.value =
      error instanceof Error
        ? error.message
        : t("Failed to load notification preference");
  } finally {
    isLoadingNotificationPreference.value = false;
  }
};

const setSpaceNotificationsMuted = async (muted: boolean) => {
  if (!currentSpace.value?.id || isUpdatingNotificationPreference.value) return;

  isUpdatingNotificationPreference.value = true;
  notificationPreferenceError.value = null;

  try {
    const response = await api.space.setNotificationMuted(currentSpace.value.id, muted);
    spaceNotificationsMuted.value = response.muted;
  } catch (error) {
    notificationPreferenceError.value =
      error instanceof Error
        ? error.message
        : t("Failed to update notification preference");
  } finally {
    isUpdatingNotificationPreference.value = false;
  }
};

const handleConnectIntegration = async (provider: OAuthIntegrationProvider) => {
  if (!currentSpace.value?.id) return;
  connectingProvider.value = provider;
  integrationsError.value = null;
  integrationsMessage.value = null;

  try {
    const redirectTo = `${window.location.pathname}${window.location.search}`;
    const response = await api.integrations.connect(currentSpace.value.id, provider, {
      redirectTo,
    });
    window.location.href = response.authorizeUrl;
  } catch (error) {
    integrationsError.value =
      error instanceof Error ? error.message : t("Failed to start OAuth flow");
    connectingProvider.value = null;
  }
};

const handleDisconnectIntegration = async (provider: OAuthIntegrationProvider) => {
  if (!currentSpace.value?.id) return;
  if (!confirm(t("Disconnect {provider}?").replace("{provider}", provider))) return;
  disconnectingProvider.value = provider;
  integrationsError.value = null;
  integrationsMessage.value = null;

  try {
    await api.integrations.disconnect(currentSpace.value.id, provider);
    await loadIntegrations();
  } catch (error) {
    integrationsError.value =
      error instanceof Error ? error.message : t("Failed to disconnect integration");
  } finally {
    disconnectingProvider.value = null;
  }
};

onMounted(() => {
  const savedPreference = getStoredThemePreference();
  themePreference.value = savedPreference;
  applyThemePreference(savedPreference);
  const url = new URL(window.location.href);
  const integrationStatus = url.searchParams.get("status");
  const integrationName = url.searchParams.get("integration");
  const integrationMessage = url.searchParams.get("message");
  if (integrationStatus === "connected" && integrationName) {
    integrationsMessage.value = t("{provider} connected successfully").replace(
      "{provider}",
      integrationName,
    );
  } else if (integrationStatus === "error") {
    integrationsError.value = integrationMessage || t("Integration OAuth failed");
  }

  loadIntegrations();
  loadNotificationPreference();
});

watch(
  () => currentSpace.value?.id,
  () => {
    loadIntegrations();
    loadNotificationPreference();
  },
);
</script>

<template>
  <!-- Header -->
  <div class="px-4 py-3 border-b border-neutral-100 flex items-center gap-2">
    <button
      type="button"
      @click="emit('close')"
      class="inline-flex items-center justify-center w-7 h-7 rounded-md text-neutral-500 hover:text-neutral-900 hover:bg-neutral-100 transition-colors"
      :aria-label="t('Back to profile menu')"
    >
      <div class="svg-icon w-4 h-4" v-html="chevronLeftLargeIcon" />
    </button>
    <p class="text-base font-medium text-foreground">{{ t("Preferences") }}</p>
  </div>

  <!-- Tabbed settings layout -->
  <SettingsLayout :tabs="tabs" class="w-[620px] max-w-[calc(100vw-2rem)] min-h-[200px]">
    <!-- Appearance tab -->
    <template #appearance>
      <section>
        <div class="mb-3">
          <h2 class="text-size-medium font-semibold text-foreground">
            {{ t("Interface") }}
          </h2>
          <p class="mt-1 text-size-small text-neutral-500">
            {{ t("Choose how Vektor looks on this device.") }}
          </p>
        </div>
        <div class="rounded-lg border border-neutral-200 bg-background p-3">
          <p class="text-size-small font-medium text-foreground">{{ t("Theme") }}</p>
          <fieldset class="mt-3 grid grid-cols-3 gap-3" :aria-label="t('Theme')">
            <button
              v-for="option in themeOptions"
              :key="option.value"
              type="button"
              :aria-pressed="themePreference === option.value"
              @click="setThemePreference(option.value)"
              class="group flex flex-col items-center gap-1.5 rounded-md px-2 py-1 text-size-small font-medium text-neutral-500 transition-colors hover:text-neutral-900"
            >
              <span
                class="flex h-12 w-12 items-center justify-center rounded-full border border-neutral-200 p-0.5 transition-transform group-hover:scale-105"
                :class="themePreference === option.value ? 'ring-2 ring-primary-500 ring-offset-2' : ''"
              >
                <span
                  class="h-full w-full rounded-full"
                  :class="option.swatchClass"
                ></span>
              </span>
              <span>{{ option.label }}</span>
            </button>
          </fieldset>
        </div>
      </section>

      <section class="mt-6">
        <div class="mb-3">
          <h2 class="text-size-medium font-semibold text-foreground">
            {{ t("Collaboration") }}
          </h2>
          <p class="mt-1 text-size-small text-neutral-500">
            {{ t("Personalize how you appear to collaborators.") }}
          </p>
        </div>
        <div class="rounded-lg border border-neutral-200 bg-background p-3">
          <div class="flex items-start justify-between gap-3">
            <div>
              <p class="text-size-small font-medium text-foreground">
                {{ t("Cursor color") }}
              </p>
              <p class="mt-0.5 text-label text-neutral-500">
                {{ t("Used for your presence in shared documents and canvases.") }}
              </p>
            </div>
            <button
              v-if="!isAutomaticCursorColor"
              type="button"
              @click="clearCursorColor"
              class="shrink-0 text-label font-medium text-neutral-500 transition-colors hover:text-neutral-900"
            >
              {{ t("Reset to automatic") }}
            </button>
          </div>
          <a-popover-trigger>
            <button
              slot="trigger"
              type="button"
              class="mt-3 flex w-full items-center justify-between gap-3 rounded-md border border-neutral-200 bg-background px-3 py-2 text-size-medium text-foreground transition-colors hover:bg-neutral-50"
              :aria-label="t('Cursor color')"
            >
              <span class="flex items-center gap-2">
                <span
                  class="h-5 w-5 rounded-full border-2 border-white shadow-[0_0_0_1px_rgba(15,23,42,0.2),0_1px_2px_rgba(15,23,42,0.18)]"
                  :style="{ background: cursorColor }"
                  aria-hidden="true"
                ></span>
                <span>{{ isAutomaticCursorColor ? t("Automatic") : cursorColor }}</span>
              </span>
              <span class="text-label font-medium text-neutral-500"
                >{{ t("Change") }}</span
              >
            </button>
            <a-popover class="group" placements="top-start">
              <div
                class="w-max py-2 opacity-0 transition-opacity duration-100 group-[&[enabled]]:opacity-100"
              >
                <div
                  class="bg-background border border-neutral-100 rounded-lg p-2 origin-bottom-left scale-95 transition-all shadow-large duration-150 group-[&[enabled]]:scale-100"
                >
                  <a-color-picker
                    class="w-[220px]"
                    :value="cursorColor"
                    @change="setCursorColor(($event.target as HTMLElement & { value: string }).value)"
                  ></a-color-picker>
                </div>
              </div>
            </a-popover>
          </a-popover-trigger>
        </div>
      </section>
    </template>

    <template #cosmetics>
      <CosmeticsPanel
        :inventory="cosmeticInventory"
        :loadout="cosmeticLoadout"
        :appearance="cosmeticAppearance"
        :user="currentUser"
        @equip="equipCosmetic"
      />
    </template>

    <!-- Notifications tab -->
    <template #notifications>
      <section>
        <div class="mb-3">
          <p class="text-size-small text-neutral-500">
            {{ t("Manage notifications for the current space.") }}
          </p>
        </div>

        <div
          v-if="notificationPreferenceError"
          class="mb-3 rounded-md border border-red-200 bg-red-50 p-2.5 text-size-small text-red-600"
        >
          {{ notificationPreferenceError }}
        </div>

        <div
          v-if="!currentSpace?.id"
          class="rounded-lg border border-dashed border-neutral-200 p-5 text-center text-size-small text-neutral-500"
        >
          {{ t("Open a space to manage notifications.") }}
        </div>
        <div
          v-else-if="isLoadingNotificationPreference"
          class="rounded-lg border border-neutral-100 p-5 text-center text-size-small text-neutral-500"
        >
          {{ t("Loading...") }}
        </div>
        <div
          v-else
          class="flex items-center justify-between gap-4 rounded-lg border border-neutral-200 bg-background p-3"
        >
          <div>
            <p class="text-size-small font-medium text-foreground">
              {{ t("Mute space notifications") }}
            </p>
            <p class="mt-0.5 text-label text-neutral-500">
              {{ t("Stop email notifications from this space.") }}
            </p>
          </div>
          <SwitchToggle
            :model-value="spaceNotificationsMuted"
            :disabled="isUpdatingNotificationPreference"
            @update:model-value="setSpaceNotificationsMuted"
          />
        </div>
      </section>
    </template>

    <!-- Integrations tab -->
    <template #integrations>
      <section>
        <div class="mb-4">
          <h2 class="text-size-medium font-semibold text-foreground">
            {{ t("Integrations") }}
          </h2>
          <p class="mt-1 text-size-small text-neutral-500">
            {{ t("Connect tools to make them available in this space.") }}
          </p>
          <p class="mt-2 text-label text-neutral-500">
            {{ t("Space:") }}
            <span class="font-medium text-foreground"
              >{{ activeSpaceName || t("None") }}</span
            >
          </p>
        </div>

        <div
          v-if="integrationsError"
          class="mb-3 rounded-md border border-red-200 bg-red-50 p-2.5 text-size-small text-red-600"
        >
          {{ integrationsError }}
        </div>
        <div
          v-if="integrationsMessage"
          class="mb-3 rounded-md border border-green-200 bg-green-50 p-2.5 text-size-small text-green-700"
        >
          {{ integrationsMessage }}
        </div>

        <div
          v-if="!currentSpace?.id"
          class="rounded-lg border border-dashed border-neutral-200 p-5 text-center text-size-small text-neutral-500"
        >
          {{ t("Open a space to manage integrations.") }}
        </div>
        <div
          v-else-if="isLoadingIntegrations"
          class="rounded-lg border border-neutral-100 p-5 text-center text-size-small text-neutral-500"
        >
          {{ t("Loading...") }}
        </div>
        <div v-else class="grid grid-cols-1 gap-3 min-[560px]:grid-cols-2">
          <div
            v-for="card in integrationCards"
            :key="card.provider"
            class="flex min-h-[254px] flex-col rounded-lg border border-neutral-200 bg-background p-4"
          >
            <div class="flex items-start justify-between gap-3">
              <div
                class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl text-size-large font-semibold text-white"
                :class="card.iconClass"
                aria-hidden="true"
              >
                {{ card.initial }}
              </div>
              <span
                class="inline-flex rounded-full px-2 py-0.5 text-label font-medium"
                :class="
                  card.connection?.connected
                    ? 'bg-green-50 text-green-700'
                    : 'bg-neutral-100 text-neutral-500'
                "
              >
                {{ card.connection?.connected ? t("Connected") : t("Not connected") }}
              </span>
            </div>

            <div class="mt-4">
              <h3 class="text-size-medium font-semibold text-foreground">
                {{ card.connection?.label || card.label }}
              </h3>
              <p class="mt-1 text-size-small leading-5 text-neutral-500">
                {{ card.description }}
              </p>
            </div>

            <div class="mt-3 min-h-10 text-label">
              <p v-if="card.connection?.connected" class="text-neutral-600">
                {{ t("Connected as") }}
                {{ card.connection.externalUsername || card.connection.externalAccountId }}
              </p>
              <p v-else-if="card.connection?.configured === false" class="text-amber-700">
                {{ t("Not configured") }}
              </p>
              <p
                v-else-if="card.connection?.instanceUrl"
                class="truncate text-neutral-500"
              >
                {{ card.connection.instanceUrl }}
              </p>
            </div>

            <div class="mt-auto border-t border-neutral-100 pt-3">
              <button
                v-if="card.connection?.connected"
                type="button"
                :disabled="disconnectingProvider === card.provider"
                @click="handleDisconnectIntegration(card.provider)"
                class="w-full rounded-md border border-red-200 px-3 py-1.5 text-size-small font-medium text-red-600 transition-colors hover:bg-red-50 disabled:opacity-50"
              >
                {{ disconnectingProvider === card.provider
                    ? t("Disconnecting…")
                    : t("Disconnect") }}
              </button>
              <Button
                v-else
                :disabled="
                  connectingProvider === card.provider || card.connection?.configured === false
                "
                @click="handleConnectIntegration(card.provider)"
                class="w-full justify-center text-size-small"
              >
                {{ connectingProvider === card.provider ? t("Redirecting…") : t("Connect") }}
              </Button>
            </div>
          </div>
        </div>
      </section>
    </template>
  </SettingsLayout>
</template>

// server/src/components/UserPreferencesPanel.tsx
import "@atrium-ui/elements/color-picker";
import "@atrium-ui/elements/popover";
import { createEffect, createMemo, createSignal, For, on, onMount, Show } from "solid-js";
import { isPermission } from "#acl/permissions.ts";
import {
  api,
  type OAuthIntegrationConnection,
  type OAuthIntegrationProvider,
} from "#api/client.ts";
import { useCanvasCursorColor } from "#composeables/useCanvasCursorColor.ts";
import { useCosmetics } from "#composeables/useCosmetics.ts";
import { usePersonalAccessTokens } from "#composeables/usePersonalAccessTokens.ts";
import { useSpace } from "#composeables/useSpace.ts";
import { useTranslation } from "#composeables/useTranslation.ts";
import { useUserProfile } from "#composeables/useUserProfile.ts";
import { getAvatarColor } from "#utils/avatarColor.ts";
import type { TranslationKey } from "#utils/lang.ts";
import { nativeApp } from "#utils/nativeApp.ts";
import {
  applyThemePreference,
  getStoredThemePreference,
  storeThemePreference,
  type ThemePreference,
} from "#utils/themePreference.ts";
import { AccessTokensPanel } from "./AccessTokensPanel.tsx";
import { CosmeticsPanel } from "./CosmeticsPanel.tsx";
import { DesktopAppPreferences } from "./DesktopAppPreferences.tsx";
import { Icon } from "./Icon.tsx";
import { SettingsLayout } from "./SettingsLayout.tsx";
import { SwitchToggle } from "./SwitchToggle.tsx";

interface Props {
  onClose?: () => void;
}

type ViewTransitionDocument = Document & {
  startViewTransition?: (updateCallback: () => void | Promise<void>) => void;
};

const tabs = [
  { id: "general", label: "General" },
  // { id: "cosmetics", label: "Profile" },
  { id: "integrations", label: "Integrations" },
  { id: "tokens", label: "Access Tokens" },
] satisfies { id: string; label: TranslationKey }[];

// Only the desktop app announces itself, so the tab is absent in a browser.
const app = nativeApp();
const visibleTabs = app ? [...tabs, { id: "desktop", label: "Desktop App" as const }] : tabs;

const themeOptions: {
  value: ThemePreference;
  label: TranslationKey;
  swatchClass: string;
}[] = [
  {
    value: "system",
    label: "System",
    swatchClass:
      "bg-[linear-gradient(135deg,#ffffff_0%,#ffffff_48%,#222222_52%,#222222_100%)]",
  },
  { value: "light", label: "Light", swatchClass: "bg-[#fff5b8]" },
  { value: "dark", label: "Dark", swatchClass: "bg-[#252525]" },
];

export function UserPreferencesPanel(props: Props) {
  const t = useTranslation();

  const [themePreference, setThemePreference] = createSignal<ThemePreference>("system");
  const currentUser = useUserProfile();
  const {
    inventory: cosmeticInventory,
    loadout: cosmeticLoadout,
    appearance: cosmeticAppearance,
    equip: equipCosmetic,
  } = useCosmetics();
  const { cursorColorOverride, setCursorColor, clearCursorColor } =
    useCanvasCursorColor();
  const automaticCursorColor = createMemo(() => getAvatarColor(currentUser()?.id));
  const cursorColor = createMemo(() => cursorColorOverride() ?? automaticCursorColor());
  const isAutomaticCursorColor = createMemo(() => cursorColorOverride() === null);

  const [integrationConnections, setIntegrationConnections] = createSignal<
    OAuthIntegrationConnection[]
  >([]);
  const [isLoadingIntegrations, setIsLoadingIntegrations] = createSignal(false);
  const [integrationsError, setIntegrationsError] = createSignal<string | null>(null);
  const [integrationsMessage, setIntegrationsMessage] = createSignal<string | null>(null);
  const [connectingProvider, setConnectingProvider] =
    createSignal<OAuthIntegrationProvider | null>(null);
  const [disconnectingProvider, setDisconnectingProvider] =
    createSignal<OAuthIntegrationProvider | null>(null);
  const [spaceNotificationsMuted, setSpaceNotificationsMuted] = createSignal(false);
  const [isLoadingNotificationPreference, setIsLoadingNotificationPreference] =
    createSignal(false);
  const [isUpdatingNotificationPreference, setIsUpdatingNotificationPreference] =
    createSignal(false);
  const [notificationPreferenceError, setNotificationPreferenceError] = createSignal<
    string | null
  >(null);
  const { currentSpace, currentSpaceId, spaces } = useSpace();
  const accessTokens = usePersonalAccessTokens();

  // A token delegates its issuer's role on the space, so a space reached only
  // through a document grant has no role to delegate and cannot mint one.
  const tokenSpaces = createMemo(() =>
    (spaces() ?? []).filter((space) => isPermission(space.userRole)),
  );

  // Providers come from the space's installed extensions, so the cards are
  // whatever the API returned rather than a list the app knows in advance.
  const integrationCards = createMemo(() =>
    integrationConnections().map((connection) => ({
      provider: connection.provider,
      connection,
      label: connection.label,
      description: connection.description,
      initial: connection.label.trim().charAt(0).toUpperCase() || "?",
      iconColor: getAvatarColor(connection.provider),
    })),
  );

  const applyThemePreferenceWithTransition = (preference: ThemePreference) => {
    const updateTheme = () => {
      setThemePreference(preference);
      applyThemePreference(preference);
    };
    const viewTransitionDocument = document as ViewTransitionDocument;

    if (
      !viewTransitionDocument.startViewTransition ||
      window.matchMedia("(prefers-reduced-motion: reduce)").matches
    ) {
      updateTheme();
      return;
    }

    viewTransitionDocument.startViewTransition(updateTheme);
  };

  const chooseThemePreference = (preference: ThemePreference) => {
    storeThemePreference(preference);
    applyThemePreferenceWithTransition(preference);
  };

  const loadIntegrations = async () => {
    const spaceId = currentSpace()?.id;
    if (!spaceId) {
      setIntegrationConnections([]);
      return;
    }

    setIsLoadingIntegrations(true);
    setIntegrationsError(null);

    try {
      const response = await api.integrations.get(spaceId);
      setIntegrationConnections(response.connections || []);
    } catch (error) {
      setIntegrationsError(
        error instanceof Error ? error.message : t("Failed to load integrations"),
      );
      setIntegrationConnections([]);
    } finally {
      setIsLoadingIntegrations(false);
    }
  };

  const loadNotificationPreference = async () => {
    const spaceId = currentSpace()?.id;
    if (!spaceId) {
      setSpaceNotificationsMuted(false);
      return;
    }

    setIsLoadingNotificationPreference(true);
    setNotificationPreferenceError(null);

    try {
      const response = await api.space.getNotificationPreference(spaceId);
      setSpaceNotificationsMuted(response.muted);
    } catch (error) {
      setNotificationPreferenceError(
        error instanceof Error
          ? error.message
          : t("Failed to load notification preference"),
      );
    } finally {
      setIsLoadingNotificationPreference(false);
    }
  };

  const muteSpaceNotifications = async (muted: boolean) => {
    const spaceId = currentSpace()?.id;
    if (!spaceId || isUpdatingNotificationPreference()) return;

    setIsUpdatingNotificationPreference(true);
    setNotificationPreferenceError(null);

    try {
      const response = await api.space.setNotificationMuted(spaceId, muted);
      setSpaceNotificationsMuted(response.muted);
    } catch (error) {
      setNotificationPreferenceError(
        error instanceof Error
          ? error.message
          : t("Failed to update notification preference"),
      );
    } finally {
      setIsUpdatingNotificationPreference(false);
    }
  };

  const revokeToken = (tokenId: string) => {
    if (!confirm(t("Revoke this token? Anything using it stops working immediately.")))
      return;
    void accessTokens.revoke(tokenId);
  };

  const deleteToken = (tokenId: string) => {
    if (!confirm(t("Delete this token permanently?"))) return;
    void accessTokens.remove(tokenId);
  };

  const handleConnectIntegration = async (provider: OAuthIntegrationProvider) => {
    const spaceId = currentSpace()?.id;
    if (!spaceId) return;
    setConnectingProvider(provider);
    setIntegrationsError(null);
    setIntegrationsMessage(null);

    try {
      const redirectTo = `${window.location.pathname}${window.location.search}`;
      const response = await api.integrations.connect(spaceId, provider, { redirectTo });
      window.location.href = response.authorizeUrl;
    } catch (error) {
      setIntegrationsError(
        error instanceof Error ? error.message : t("Failed to start OAuth flow"),
      );
      setConnectingProvider(null);
    }
  };

  const handleDisconnectIntegration = async (provider: OAuthIntegrationProvider) => {
    const spaceId = currentSpace()?.id;
    if (!spaceId) return;
    if (!confirm(t("Disconnect {provider}?").replace("{provider}", provider))) return;
    setDisconnectingProvider(provider);
    setIntegrationsError(null);
    setIntegrationsMessage(null);

    try {
      await api.integrations.disconnect(spaceId, provider);
      await loadIntegrations();
    } catch (error) {
      setIntegrationsError(
        error instanceof Error ? error.message : t("Failed to disconnect integration"),
      );
    } finally {
      setDisconnectingProvider(null);
    }
  };

  onMount(() => {
    const savedPreference = getStoredThemePreference();
    setThemePreference(savedPreference);
    applyThemePreference(savedPreference);

    const url = new URL(window.location.href);
    const integrationStatus = url.searchParams.get("status");
    const integrationName = url.searchParams.get("integration");
    const integrationMessage = url.searchParams.get("message");
    if (integrationStatus === "connected" && integrationName) {
      setIntegrationsMessage(
        t("{provider} connected successfully").replace("{provider}", integrationName),
      );
    } else if (integrationStatus === "error") {
      setIntegrationsError(integrationMessage || t("Integration OAuth failed"));
    }

    void loadIntegrations();
    void loadNotificationPreference();
  });

  createEffect(
    on(
      currentSpaceId,
      () => {
        void loadIntegrations();
        void loadNotificationPreference();
      },
      { defer: true },
    ),
  );

  return (
    <>
      <div class="flex items-center gap-2 border-neutral-100 border-b px-4 py-3">
        <button
          type="button"
          onClick={() => props.onClose?.()}
          class="inline-flex h-7 w-7 items-center justify-center rounded-md text-neutral-500 transition-colors hover:bg-neutral-100 hover:text-neutral-900"
          aria-label={t("Back to profile menu")}
        >
          <Icon class="h-4 w-4" name="chevron-left-large" />
        </button>
        <p class="font-medium text-base text-foreground">{t("Preferences")}</p>
      </div>

      <SettingsLayout
        tabs={visibleTabs.map((tab) => ({ ...tab, label: t(tab.label) }))}
        onTabChange={(id) => {
          if (id === "tokens") void accessTokens.load();
        }}
        class="min-h-[200px] w-[620px] max-w-[calc(100vw-2rem)]"
        panels={{
          general: () => (
            <>
              <section>
                <div class="mb-3">
                  <h2 class="font-semibold text-foreground text-size-medium">
                    {t("Interface")}
                  </h2>
                  <p class="mt-1 text-neutral-500 text-size-small">
                    {t("Choose how Vektor looks on this device.")}
                  </p>
                </div>
                <div class="rounded-lg border border-neutral-200 bg-background p-3">
                  <fieldset class="mt-3 grid grid-cols-3 gap-3">
                    <legend class="sr-only">{t("Theme")}</legend>
                    <For each={themeOptions}>
                      {(option) => (
                        <button
                          type="button"
                          aria-pressed={themePreference() === option.value}
                          onClick={() => chooseThemePreference(option.value)}
                          class="group flex flex-col items-center gap-1.5 rounded-md px-2 py-1 font-medium text-neutral-500 text-size-small transition-colors hover:text-neutral-900"
                        >
                          <span
                            class="flex h-12 w-12 items-center justify-center rounded-full border border-neutral-200 p-0.5 transition-transform group-hover:scale-105"
                            classList={{
                              "ring-2 ring-primary-500 ring-offset-2":
                                themePreference() === option.value,
                            }}
                          >
                            <span
                              class={`h-full w-full rounded-full ${option.swatchClass}`}
                            />
                          </span>
                          <span>{t(option.label)}</span>
                        </button>
                      )}
                    </For>
                  </fieldset>
                </div>
              </section>

              <section class="mt-6">
                <div class="mb-3">
                  <h2 class="font-semibold text-foreground text-size-medium">
                    {t("Collaboration")}
                  </h2>
                  <p class="mt-1 text-neutral-500 text-size-small">
                    {t("Personalize how you appear to collaborators.")}
                  </p>
                </div>
                <div class="rounded-lg border border-neutral-200 bg-background p-3">
                  <div class="flex items-start justify-between gap-3">
                    <div>
                      <p class="font-medium text-foreground text-size-small">
                        {t("Cursor color")}
                      </p>
                      <p class="mt-0.5 text-label text-neutral-500">
                        {t("Used for your presence in shared documents and canvases.")}
                      </p>
                    </div>
                    <Show when={!isAutomaticCursorColor()}>
                      <button
                        type="button"
                        onClick={clearCursorColor}
                        class="shrink-0 font-medium text-label text-neutral-500 transition-colors hover:text-neutral-900"
                      >
                        {t("Reset to automatic")}
                      </button>
                    </Show>
                  </div>
                  <a-popover-trigger>
                    <button
                      slot="trigger"
                      type="button"
                      class="mt-3 flex w-full items-center justify-between gap-3 rounded-md border border-neutral-200 bg-background px-3 py-2 text-foreground text-size-medium transition-colors hover:bg-neutral-50"
                      attr:aria-label={t("Cursor color")}
                    >
                      <span class="flex items-center gap-2">
                        <span
                          class="h-5 w-5 rounded-full border-2 border-white shadow-[0_0_0_1px_rgba(15,23,42,0.2),0_1px_2px_rgba(15,23,42,0.18)]"
                          style={{ background: cursorColor() }}
                          aria-hidden="true"
                        />
                        <span>
                          {isAutomaticCursorColor() ? t("Automatic") : cursorColor()}
                        </span>
                      </span>
                      <span class="font-medium text-label text-neutral-500">
                        {t("Change")}
                      </span>
                    </button>
                    <a-popover class="group" placements="top-start">
                      <div class="w-max py-2 opacity-0 transition-opacity duration-100 group-[&[enabled]]:opacity-100">
                        <div class="origin-bottom-left scale-95 rounded-lg border border-neutral-100 bg-background p-2 shadow-large transition-all duration-150 group-[&[enabled]]:scale-100">
                          <a-color-picker
                            class="w-[220px]"
                            attr:value={cursorColor()}
                            on:change={(event: Event) =>
                              setCursorColor(
                                (event.target as HTMLElement & { value: string }).value,
                              )
                            }
                          />
                        </div>
                      </div>
                    </a-popover>
                  </a-popover-trigger>
                </div>
              </section>

              <section class="mt-6">
                <div class="mb-3">
                  <h2 class="font-semibold text-foreground text-size-medium">
                    {t("Notifications")}
                  </h2>
                  <p class="mt-1 text-neutral-500 text-size-small">
                    {t("Manage notifications for the current space.")}
                  </p>
                </div>

                <Show when={notificationPreferenceError()}>
                  <div class="mb-3 rounded-md border border-red-200 bg-red-50 p-2.5 text-red-600 text-size-small">
                    {notificationPreferenceError()}
                  </div>
                </Show>

                <Show
                  when={currentSpace()?.id}
                  fallback={
                    <div class="rounded-lg border border-neutral-200 border-dashed p-5 text-center text-neutral-500 text-size-small">
                      {t("Open a space to manage notifications.")}
                    </div>
                  }
                >
                  <Show
                    when={!isLoadingNotificationPreference()}
                    fallback={
                      <div class="rounded-lg border border-neutral-100 p-5 text-center text-neutral-500 text-size-small">
                        {t("Loading...")}
                      </div>
                    }
                  >
                    <div class="flex items-center justify-between gap-4 rounded-lg border border-neutral-200 bg-background p-3">
                      <div>
                        <p class="font-medium text-foreground text-size-small">
                          {t("Mute space notifications")}
                        </p>
                        <p class="mt-0.5 text-label text-neutral-500">
                          {t("Stop email notifications from this space.")}
                        </p>
                      </div>
                      <SwitchToggle
                        value={spaceNotificationsMuted()}
                        disabled={isUpdatingNotificationPreference()}
                        onInput={(muted) => void muteSpaceNotifications(muted)}
                      />
                    </div>
                  </Show>
                </Show>
              </section>
            </>
          ),

          // cosmetics: () => (
          //   <CosmeticsPanel
          //     inventory={cosmeticInventory}
          //     loadout={cosmeticLoadout()}
          //     appearance={cosmeticAppearance()}
          //     user={currentUser()}
          //     onEquip={equipCosmetic}
          //   />
          // ),

          desktop: () => (
            <Show when={app}>{(app) => <DesktopAppPreferences app={app()} />}</Show>
          ),

          tokens: () => (
            <AccessTokensPanel
              tokens={accessTokens.tokens()}
              spaces={tokenSpaces()}
              defaultSpaceId={currentSpaceId()}
              isLoading={accessTokens.isLoading()}
              isCreating={accessTokens.isCreating()}
              pendingTokenId={accessTokens.pendingTokenId()}
              createdToken={accessTokens.createdToken()}
              error={accessTokens.error()}
              onCreate={accessTokens.create}
              onDismissCreatedToken={accessTokens.dismissCreatedToken}
              onRevoke={revokeToken}
              onDelete={deleteToken}
            />
          ),

          integrations: () => (
            <section>
              <div class="mb-4">
                <p class="text-neutral-500 text-size-small">
                  {t("Connect tools to make them available in this space.")}
                </p>
              </div>

              <Show when={integrationsError()}>
                <div class="mb-3 rounded-md border border-red-200 bg-red-50 p-2.5 text-red-600 text-size-small">
                  {integrationsError()}
                </div>
              </Show>
              <Show when={integrationsMessage()}>
                <div class="mb-3 rounded-md border border-green-200 bg-green-50 p-2.5 text-green-700 text-size-small">
                  {integrationsMessage()}
                </div>
              </Show>

              <Show
                when={currentSpace()?.id}
                fallback={
                  <div class="flex min-h-[236px] flex-col items-center justify-center rounded-lg border border-neutral-200 border-dashed p-5 text-center text-neutral-500 text-size-small">
                    {t("Open a space to manage integrations.")}
                  </div>
                }
              >
                <Show
                  when={!isLoadingIntegrations()}
                  fallback={
                    <div class="flex min-h-[236px] flex-col items-center justify-center rounded-lg border border-neutral-100 p-5 text-center text-neutral-500 text-size-small">
                      {t("Loading...")}
                    </div>
                  }
                >
                  <Show
                    when={integrationCards().length > 0}
                    fallback={
                      <div class="flex min-h-[236px] flex-col items-center justify-center rounded-lg border border-neutral-200 border-dashed p-5 text-center text-neutral-500 text-size-small">
                        {t("Install an extension that provides an integration.")}
                      </div>
                    }
                  >
                    <div class="grid grid-cols-1 gap-3 min-[560px]:grid-cols-2">
                      <For each={integrationCards()}>
                        {(card) => (
                          <div class="flex min-h-[254px] flex-col rounded-lg border border-neutral-200 bg-background p-4">
                            <div class="flex items-start justify-between gap-3">
                              <div
                                class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl font-semibold text-size-large text-white"
                                style={{ "background-color": card.iconColor }}
                                aria-hidden="true"
                              >
                                {card.initial}
                              </div>
                              <span
                                class="inline-flex rounded-full px-2 py-0.5 font-medium text-label"
                                classList={{
                                  "bg-green-50 text-green-700":
                                    !!card.connection?.connected,
                                  "bg-neutral-100 text-neutral-500":
                                    !card.connection?.connected,
                                }}
                              >
                                {card.connection?.connected
                                  ? t("Connected")
                                  : t("Not connected")}
                              </span>
                            </div>

                            <div class="mt-4">
                              <h3 class="font-semibold text-foreground text-size-medium">
                                {card.label}
                              </h3>
                              <Show when={card.description}>
                                <p class="mt-1 text-neutral-500 text-size-small leading-5">
                                  {card.description}
                                </p>
                              </Show>
                            </div>

                            <div class="mt-3 min-h-10 text-label">
                              <Show when={card.connection?.connected}>
                                <p class="text-neutral-600">
                                  {t("Connected as")}{" "}
                                  {card.connection?.externalUsername ||
                                    card.connection?.externalAccountId}
                                </p>
                              </Show>
                              <Show
                                when={
                                  !card.connection?.connected &&
                                  card.connection?.configured === false
                                }
                              >
                                <p class="text-amber-700">{t("Not configured")}</p>
                              </Show>
                              <Show
                                when={
                                  !card.connection?.connected &&
                                  card.connection?.configured !== false &&
                                  card.connection?.instanceUrl
                                }
                              >
                                <p class="truncate text-neutral-500">
                                  {card.connection?.instanceUrl}
                                </p>
                              </Show>
                            </div>

                            <div class="mt-auto border-neutral-100 border-t pt-3">
                              <Show
                                when={card.connection?.connected}
                                fallback={
                                  <button
                                    type="button"
                                    disabled={
                                      connectingProvider() === card.provider ||
                                      card.connection?.configured === false
                                    }
                                    onClick={() =>
                                      void handleConnectIntegration(card.provider)
                                    }
                                    class="w-full rounded-md bg-blue-600 px-3 py-1.5 font-medium text-size-small text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
                                  >
                                    {connectingProvider() === card.provider
                                      ? t("Redirecting…")
                                      : t("Connect")}
                                  </button>
                                }
                              >
                                <button
                                  type="button"
                                  disabled={disconnectingProvider() === card.provider}
                                  onClick={() =>
                                    void handleDisconnectIntegration(card.provider)
                                  }
                                  class="w-full rounded-md border border-red-200 px-3 py-1.5 font-medium text-red-600 text-size-small transition-colors hover:bg-red-50 disabled:opacity-50"
                                >
                                  {disconnectingProvider() === card.provider
                                    ? t("Disconnecting…")
                                    : t("Disconnect")}
                                </button>
                              </Show>
                            </div>
                          </div>
                        )}
                      </For>
                    </div>
                  </Show>
                </Show>
              </Show>
            </section>
          ),
        }}
      />
    </>
  );
}
