// app/src/components/views/SpaceSettingsView.vue
<script setup lang="ts">
import { computed } from "vue";
import NoAccess from "#components/NoAccess.vue";
import SpaceSettings from "#components/SpaceSettings.vue";
import { usePageTitle } from "#composeables/usePageTitle.ts";
import { canAccessSettings } from "#composeables/usePermissions.ts";
import { useSpace } from "#composeables/useSpace.ts";

const { currentSpace } = useSpace();
const isOwner = computed(() => canAccessSettings(currentSpace.value?.userRole));

usePageTitle("Settings");
</script>

<template>
  <inset-view
    v-if="currentSpace"
    class="block pt-xs pb-20 lg:pb-8 h-full print:px-0 px-xs lg:px-m md:ml-(--inset-left) md:mr-(--inset-right)"
  >
    <SpaceSettings v-if="isOwner" />
    <NoAccess v-else />
  </inset-view>
</template>

// app/src/components/views/SpaceSettingsView.tsx
import { createMemo, Show } from "solid-js";
import { NoAccess } from "#components/NoAccess.tsx";
import { SpaceSettings } from "#components/SpaceSettings.tsx";
import { usePageTitle } from "#composeables/usePageTitle.solid.ts";
import { canAccessSettings } from "#composeables/usePermissions.ts";
import { useSpace } from "#composeables/useSpace.solid.ts";

export function SpaceSettingsView() {
  const { currentSpace } = useSpace();
  const isOwner = createMemo(() => canAccessSettings(currentSpace()?.userRole));

  usePageTitle("Settings");

  return (
    <Show when={currentSpace()}>
      <inset-view class="block h-full px-xs pt-xs pb-20 md:mr-(--inset-right) md:ml-(--inset-left) lg:px-m lg:pb-8 print:px-0">
        <Show when={isOwner()} fallback={<NoAccess />}>
          <SpaceSettings />
        </Show>
      </inset-view>
    </Show>
  );
}
