// server/src/components/Button.tsx
import { type JSX, mergeProps, Show } from "solid-js";
import { Icon, type IconName } from "./Icon.tsx";

interface Props {
  variant?: "primary" | "secondary" | "ghost" | "outline";
  tone?: "default" | "danger";
  size?: "medium" | "small";
  text?: string;
  icon?: IconName;
  ariaLabel?: string;
  disabled?: boolean;
  type?: "button" | "submit" | "reset";
  class?: string;
  form?: string;
  slot?: string;
  onClick?: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent>;
  children?: JSX.Element;
}

const VARIANT_CLASS = {
  primary: "button-primary",
  secondary: "button-secondary",
  ghost: "button-ghost",
  outline: "button-outline",
} as const;

export function Button(props: Props) {
  const merged = mergeProps(
    {
      variant: "primary" as const,
      tone: "default" as const,
      size: "medium" as const,
      type: "button" as const,
    },
    props,
  );

  const classes = () =>
    [
      VARIANT_CLASS[merged.variant],
      merged.tone === "danger" && "button-danger",
      merged.size === "small" && "button-small",
      merged.class,
    ]
      .filter(Boolean)
      .join(" ");

  return (
    <button
      type={merged.type}
      class={classes()}
      disabled={merged.disabled}
      aria-label={merged.ariaLabel}
      title={merged.ariaLabel}
      form={merged.form}
      slot={merged.slot}
      onClick={merged.onClick}
    >
      {merged.children}
      <Show when={merged.icon}>
        <Icon class="icon" name={merged.icon} />
      </Show>
      <Show when={merged.text}>
        <span>{merged.text}</span>
      </Show>
    </button>
  );
}

// app/src/components/Button.vue
<script setup lang="ts">
import { computed } from "vue";

interface Props {
  /** Visual family. Each maps to one `button-*` utility in `styles/theme.css`. */
  variant?: "primary" | "secondary" | "ghost" | "outline";
  /** Colour override layered on top of the variant. */
  tone?: "default" | "danger";
  size?: "medium" | "small";
  text?: string;
  /** Raw SVG markup, rendered inline. Use the default slot for anything richer. */
  icon?: string;
  /** Accessible name and tooltip. Required for icon-only buttons. */
  ariaLabel?: string;
  disabled?: boolean;
  type?: "button" | "submit" | "reset";
}

const props = withDefaults(defineProps<Props>(), {
  variant: "primary",
  tone: "default",
  size: "medium",
  type: "button",
});

// Written out in full: Tailwind scans source text, so an interpolated
// `button-${variant}` would never emit the utility.
const VARIANT_CLASS = {
  primary: "button-primary",
  secondary: "button-secondary",
  ghost: "button-ghost",
  outline: "button-outline",
} as const;

const classes = computed(() => [
  VARIANT_CLASS[props.variant],
  props.tone === "danger" && "button-danger",
  props.size === "small" && "button-small",
]);
</script>

<template>
  <button
    :type="type"
    :class="classes"
    :disabled="disabled"
    :aria-label="ariaLabel"
    :title="ariaLabel"
  >
    <slot />
    <div v-if="icon" v-html="icon" class="icon" />
    <span v-if="text">{{ text }}</span>
  </button>
</template>
