// app/src/components/CommentThread.tsx
import { createEffect, createSignal, For, on, Show } from "solid-js";
import { useMembers } from "#composeables/useMembers.solid.ts";
import { useUserProfile } from "#composeables/useUserProfile.solid.ts";
import { formatRelativeTime } from "#utils/datetime.ts";
import { renderMessageMarkdown } from "#utils/markdown.ts";
import { findMemberUser, userDisplayName } from "#utils/userDisplay.ts";
import "#editor/css/mentions.css";
import { cancelIcon, confirmationIcon, deleteEntryIcon } from "#assets/icons.ts";
import "./AvatarElement.ts";
import { Button } from "./Button.tsx";
import { MessageInput } from "./MessageInput.tsx";

export interface Comment {
  id: string;
  content: string;
  createdAt: string;
  createdBy: string;
  createdByUser?: {
    image?: string | null;
    name?: string | null;
  } | null;
  reference?: string;
  parentId?: string | null;
  resourceType?: string;
  resourceId?: string;
}

interface Props {
  spaceId: string;
  documentId: string;
  comments: Comment[];
  activeReference?: string | null;
  isSubmitting?: boolean;
  isDeletingComment?: boolean;
  onSubmit?: (payload: { content: string; reference: string | null }) => void;
  onDelete?: (commentId: string) => void;
  onResolve?: () => void;
  onClose?: () => void;
}

export function CommentThread(props: Props) {
  const { members } = useMembers();
  const currentUser = useUserProfile();

  const [newCommentContent, setNewCommentContent] = createSignal("");
  let commentListRef: HTMLDivElement | undefined;

  const getUser = (comment: Comment) =>
    comment.createdByUser ?? findMemberUser(members(), comment.createdBy);

  const getUserName = (comment: Comment): string =>
    userDisplayName(getUser(comment), comment.createdBy);

  function getRelativeTime(dateString: string) {
    return formatRelativeTime(dateString, { style: "narrow" });
  }

  function handleSubmit() {
    if (!newCommentContent().trim()) return;

    props.onSubmit?.({
      content: newCommentContent(),
      reference: props.activeReference || null,
    });

    setNewCommentContent("");
  }

  function handleDeleteComment(commentId: string) {
    if (confirm("Are you sure you want to delete this comment?")) {
      props.onDelete?.(commentId);
    }
  }

  const commentCount = createMemo(() => props.comments.length);

  createEffect(
    on(
      commentCount,
      () => {
        // Solid has already rendered the new comment by the time this runs.
        if (commentListRef) commentListRef.scrollTop = commentListRef.scrollHeight;
      },
      { defer: true },
    ),
  );

  return (
    <div class="flex h-full max-h-[600px] w-80 flex-col rounded-lg border border-neutral-100 bg-background shadow-xl">
      {/* Header */}
      <div class="flex items-center justify-between rounded-t-lg border-neutral-100 border-b bg-neutral-50/80 p-3 backdrop-blur-sm">
        <div class="flex items-center gap-2">
          <h3 class="font-semibold text-neutral-800 text-size-medium">Thread</h3>
          <Show when={props.comments.length > 0}>
            <span class="rounded-full bg-neutral-200/50 px-1.5 py-0.5 font-medium text-[10px] text-neutral-500">
              {props.comments.length}
            </span>
          </Show>
        </div>
        <div class="flex items-center gap-1">
          <Show when={props.comments.length > 0}>
            <Button
              variant="ghost"
              onClick={() => props.onResolve?.()}
              class="h-6 w-6 p-1 text-neutral-400 hover:text-green-600"
              ariaLabel="Resolve thread"
            >
              <div class="svg-icon h-4 w-4" innerHTML={confirmationIcon} />
            </Button>
          </Show>
          <Button
            variant="ghost"
            onClick={() => props.onClose?.()}
            class="-mr-1 h-6 w-6 p-1 text-neutral-400 hover:text-neutral-700"
            ariaLabel="Close thread"
          >
            <div class="svg-icon h-4 w-4" innerHTML={cancelIcon} />
          </Button>
        </div>
      </div>

      {/* Comments List */}
      <div ref={commentListRef} class="flex-1 space-y-4 overflow-y-auto p-3">
        <Show when={props.comments.length === 0}>
          <div class="flex h-24 flex-col items-center justify-center text-center text-neutral-400">
            <p class="font-medium text-neutral-500 text-size-medium">No comments yet</p>
            <p class="text-size-small opacity-75">Start the conversation!</p>
          </div>
        </Show>

        <For each={props.comments}>
          {(comment) => (
            <div class="group flex gap-2">
              <vektor-avatar
                size="24"
                attr:user-id={comment.createdBy}
                prop:user={getUser(comment)}
                class="mt-0.5 shrink-0"
              />

              <div class="min-w-0 flex-1">
                <div class="mb-0.5 flex items-baseline gap-2">
                  <span class="truncate font-semibold text-neutral-900 text-size-small">
                    {getUserName(comment)}
                  </span>
                  <span class="whitespace-nowrap text-[10px] text-neutral-400">
                    {getRelativeTime(comment.createdAt)}
                  </span>
                  <Show when={currentUser()?.id === comment.createdBy}>
                    <Button
                      variant="ghost"
                      onClick={() => handleDeleteComment(comment.id)}
                      disabled={props.isDeletingComment}
                      class="ml-auto h-5 w-5 p-0.5 text-neutral-400 opacity-0 transition-opacity hover:text-red-600 group-hover:opacity-100"
                      ariaLabel="Delete comment"
                    >
                      <div class="svg-icon h-3 w-3" innerHTML={deleteEntryIcon} />
                    </Button>
                  </Show>
                </div>

                <div
                  class="comment-markdown break-words text-neutral-700 text-size-medium leading-relaxed"
                  innerHTML={renderMessageMarkdown(comment.content)}
                />
              </div>
            </div>
          )}
        </For>
      </div>

      {/* Input Area */}
      <div class="p-5xs">
        <div class="rounded-lg border border-neutral-100 bg-neutral-50 px-3 py-2">
          <MessageInput
            value={newCommentContent()}
            onInput={setNewCommentContent}
            mentions
            spaceId={props.spaceId}
            documentId={props.documentId}
            placeholder="Reply..."
            rows={2}
            submitKey="ctrl+enter"
            disabled={props.isSubmitting || !newCommentContent().trim()}
            onSubmit={handleSubmit}
          />
        </div>
      </div>
    </div>
  );
}

// app/src/components/CommentThread.vue
<script setup lang="ts">
import { nextTick, ref, watch } from "vue";
import { useMembers } from "#composeables/useMembers.ts";
import { useUserProfile } from "#composeables/useUserProfile.ts";
import { renderMessageMarkdown } from "#utils/messageMarkdown.ts";
import { formatRelativeTime } from "#utils/utils.ts";
import { cancelIcon, confirmationIcon, deleteEntryIcon } from "~/src/assets/icons.ts";
import "./AvatarElement.ts";
import ButtonGhost from "./ButtonGhost.vue";
import MessageInput from "./MessageInput.vue";

export interface Comment {
  id: string;
  content: string;
  createdAt: string;
  createdBy: string;
  createdByUser?: {
    image?: string | null;
    name?: string | null;
  } | null;
  reference?: string;
  parentId?: string | null;
  resourceType?: string;
  resourceId?: string;
}

const props = defineProps<{
  spaceId: string;
  documentId: string;
  comments: Comment[];
  activeReference?: string | null;
  isSubmitting?: boolean;
  isDeletingComment?: boolean;
}>();

const emit = defineEmits<{
  (e: "clear-reference"): void;
  (e: "submit", payload: { content: string; reference: string | null }): void;
  (e: "delete", commentId: string): void;
  (e: "resolve"): void;
  (e: "close"): void;
}>();

const { members } = useMembers();
const currentUser = useUserProfile();

const newCommentContent = ref("");
const commentListRef = ref<HTMLElement | null>(null);

const getUser = (comment: Comment) => {
  return (
    comment.createdByUser ??
    members.value.find((member) => member.userId === comment.createdBy)?.user
  );
};

const getUserName = (comment: Comment): string => {
  const user = getUser(comment);
  return user?.name || comment.createdBy;
};

function getRelativeTime(dateString: string) {
  return formatRelativeTime(dateString, { style: "narrow" });
}

function handleSubmit() {
  if (!newCommentContent.value.trim()) return;

  emit("submit", {
    content: newCommentContent.value,
    reference: props.activeReference || null,
  });

  newCommentContent.value = "";
}

function handleDeleteComment(commentId: string) {
  if (confirm("Are you sure you want to delete this comment?")) {
    emit("delete", commentId);
  }
}

watch(
  () => props.comments.length,
  () => {
    nextTick(() => {
      if (commentListRef.value) {
        commentListRef.value.scrollTop = commentListRef.value.scrollHeight;
      }
    });
  },
);
</script>

<template>
  <div
    class="flex flex-col h-full bg-background rounded-lg shadow-xl border border-neutral-100 w-80 max-h-[600px]"
  >
    <!-- Header -->
    <div
      class="flex items-center justify-between p-3 border-b border-neutral-100 bg-neutral-50/80 rounded-t-lg backdrop-blur-sm"
    >
      <div class="flex items-center gap-2">
        <h3 class="font-semibold text-neutral-800 text-size-medium">Thread</h3>
        <span
          v-if="comments.length > 0"
          class="text-[10px] font-medium text-neutral-500 bg-neutral-200/50 px-1.5 py-0.5 rounded-full"
        >
          {{ comments.length }}
        </span>
      </div>
      <div class="flex items-center gap-1">
        <ButtonGhost
          v-if="comments.length > 0"
          @click="emit('resolve')"
          class="p-1 text-neutral-400 hover:text-green-600 w-6 h-6"
          title="Resolve thread"
        >
          <div class="svg-icon w-4 h-4" v-html="confirmationIcon" />
        </ButtonGhost>
        <ButtonGhost
          @click="emit('close')"
          class="p-1 -mr-1 text-neutral-400 hover:text-neutral-700 w-6 h-6"
        >
          <div class="svg-icon w-4 h-4" v-html="cancelIcon" />
        </ButtonGhost>
      </div>
    </div>

    <!-- Comments List -->
    <div ref="commentListRef" class="flex-1 p-3 overflow-y-auto space-y-4">
      <div
        v-if="comments.length === 0"
        class="flex flex-col items-center justify-center h-24 text-center text-neutral-400"
      >
        <p class="text-size-medium font-medium text-neutral-500">No comments yet</p>
        <p class="text-size-small opacity-75">Start the conversation!</p>
      </div>

      <div v-for="comment in comments" :key="comment.id" class="flex gap-2 group">
        <vektor-avatar
          size="24"
          :user-id="comment.createdBy"
          :user="getUser(comment)"
          class="shrink-0 mt-0.5"
        />

        <div class="flex-1 min-w-0">
          <div class="flex items-baseline gap-2 mb-0.5">
            <span class="text-size-small font-semibold text-neutral-900 truncate">
              {{ getUserName(comment) }}
            </span>
            <span class="text-[10px] text-neutral-400 whitespace-nowrap">
              {{ getRelativeTime(comment.createdAt) }}
            </span>
            <ButtonGhost
              v-if="currentUser?.id === comment.createdBy"
              @click="handleDeleteComment(comment.id)"
              :disabled="isDeletingComment"
              class="ml-auto p-0.5 text-neutral-400 hover:text-red-600 opacity-0 group-hover:opacity-100 transition-opacity w-5 h-5"
              title="Delete comment"
            >
              <div class="svg-icon w-3 h-3" v-html="deleteEntryIcon" />
            </ButtonGhost>
          </div>

          <div
            class="comment-markdown text-size-medium text-neutral-700 leading-relaxed break-words"
            v-html="renderMessageMarkdown(comment.content)"
          />
        </div>
      </div>
    </div>

    <!-- Input Area -->
    <div class="p-5xs">
      <div class="px-3 py-2 bg-neutral-50 border border-neutral-100 rounded-lg">
        <MessageInput
          v-model="newCommentContent"
          mentions
          :space-id="spaceId"
          :document-id="documentId"
          placeholder="Reply..."
          :rows="2"
          submit-key="ctrl+enter"
          :disabled="isSubmitting || !newCommentContent.trim()"
          :loading="isSubmitting"
          @submit="handleSubmit"
        />
      </div>
    </div>
  </div>
</template>

<style scoped>
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(p) {
  margin: 0.2rem 0;
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(ul) {
  list-style: disc;
  padding-left: 1.1rem;
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(ol) {
  list-style: decimal;
  padding-left: 1.1rem;
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(strong) {
  font-weight: 600;
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(em) {
  font-style: italic;
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(a) {
  color: var(--color-primary-600);
  text-decoration: underline;
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(document-mention),
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(a[href*="/doc/"]) {
  background: var(--color-neutral-50);
  border: 1px solid var(--color-neutral-200);
  border-radius: 0.375rem;
  color: var(--color-primary-700);
  cursor: default;
  font-weight: 500;
  padding: 0.0625rem 0.3125rem;
  text-decoration: none;
  white-space: nowrap;
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(document-mention:hover),
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(a[href*="/doc/"]:hover) {
  background: var(--color-primary-50);
  border-color: var(--color-primary-200);
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(user-mention) {
  display: inline-flex;
  align-items: center;
  padding: 0 0.25rem;
  border-radius: 0.125rem;
  font-weight: 500;
  transition-property: color, background-color, border-color;
  background: var(--color-primary-50);
  border: 1px solid var(--color-primary-200);
  color: var(--color-primary-700);
  cursor: pointer;
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(user-mention:hover) {
  background: var(--color-primary-100);
  border-color: var(--color-primary-300);
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(user-mention[data-self-mention="true"]) {
  background: var(--color-primary-100);
  border-color: var(--color-primary-300);
  color: var(--color-primary-800);
}
/* biome-ignore lint/correctness/noUnknownPseudoClass: Vue scoped-style selector is handled by the Vue compiler. */
.comment-markdown :deep(user-mention[data-self-mention="true"]:hover) {
  background: var(--color-primary-200);
  border-color: var(--color-primary-400);
}
</style>
