// app/src/components/ContextMenu.tsx
import type { JSX } from "solid-js";
import { t } from "#utils/lang.ts";
import { Button } from "./Button.tsx";
import { Icon } from "./Icon.tsx";
import "@atrium-ui/elements/popover";
import "@atrium-ui/elements/list";

interface Props {
  children?: JSX.Element;
}

export function ContextMenu(props: Props) {
  function handleSubmit(event: Event) {
    const detail = (event as CustomEvent<{ selected?: HTMLElement }>).detail;
    detail?.selected?.querySelector("button")?.click();
  }

  return (
    <a-popover-trigger class="group relative z-10 flex-none">
      <Button
        variant="secondary"
        slot="trigger"
        ariaLabel={t("Document actions")}
        class="px-4xs"
      >
        <Icon name="context-menu-more" />
      </Button>

      <a-popover class="group" placements="bottom-end">
        <div class="w-max py-2 opacity-0 transition-opacity duration-100 group-[&[enabled]]:opacity-100">
          <div class="min-w-[100px] origin-top-right scale-95 rounded-lg border border-neutral-100 bg-background p-5xs shadow-large transition-all duration-150 group-[&[enabled]]:scale-100">
            <a-list
              on:change={handleSubmit}
              class="max-h-screen w-full min-w-[150px] space-y-5xs overflow-auto text-interactive outline-none"
            >
              {props.children}
            </a-list>
          </div>
        </div>
      </a-popover>
    </a-popover-trigger>
  );
}

// app/src/components/ContextMenu.vue
<script setup lang="ts">
import { t } from "#utils/lang.ts";
import ButtonSecondary from "./ButtonSecondary.vue";
import Icon from "./Icon.vue";
import "@atrium-ui/elements/popover";
import "@atrium-ui/elements/list";

function handleSubmit(e: CustomEvent<{ detail: { selected: HTMLElement } }>) {
  e.detail.selected?.querySelector("button")?.click();
}
</script>

<template>
  <a-popover-trigger class="group relative z-10 flex-none">
    <ButtonSecondary slot="trigger" :aria-label="t('Document actions')">
      <Icon name="more" />
    </ButtonSecondary>

    <a-popover class="group" placements="bottom-end">
      <div
        class="w-max py-2 opacity-0 transition-opacity duration-100 group-[&[enabled]]:opacity-100"
      >
        <div
          class="min-w-[100px] bg-background border border-neutral-100 rounded-lg p-5xs origin-top-right scale-95 transition-all shadow-large duration-150 group-[&[enabled]]:scale-100"
        >
          <a-list
            @change="handleSubmit"
            class="max-h-screen min-w-[150px] w-full overflow-auto text-interactive outline-none space-y-5xs"
          >
            <slot></slot>
          </a-list>
        </div>
      </div>
    </a-popover>
  </a-popover-trigger>
</template>
