// server/src/components/DockedPanel.tsx
import {
  createEffect,
  createMemo,
  createSignal,
  type JSX,
  on,
  onCleanup,
  onMount,
  Show,
} from "solid-js";
import {
  type DockedWindowState,
  useDockedWindows,
} from "#composeables/useDockedWindows.ts";
import { useIsDesktop } from "#composeables/useIsDesktop.ts";
import { useTranslation } from "#composeables/useTranslation.ts";
import {
  useVisualViewport,
  viewportLayerStyle,
} from "#composeables/useVisualViewport.ts";
import { getInsets, type Insets, onInsets } from "#utils/insets.ts";
import { Dialog } from "./Dialog.tsx";
import { Icon } from "./Icon.tsx";
import { IconButton } from "./IconButton.tsx";
import { SwipeDrawer } from "./SwipeDrawer.tsx";

interface Props {
  id: string;
  title: string;
  defaultSide?: "left" | "right";
  defaultWidth?: number;
  defaultMode?: "docked" | "floating";
  /** On mobile, render as a drawer on the right edge that a left swipe anywhere opens. */
  swipeToOpen?: boolean;
  children?: JSX.Element;
}

const DOCK_THRESHOLD = 100;
const DOCK_MARGIN = 6;
const MIN_WIDTH = 280;
const MIN_HEIGHT = 200;

export function DockedPanel(props: Props) {
  const t = useTranslation();

  const {
    register,
    deregister,
    open,
    close,
    dock,
    undock,
    setWidth,
    setPosition,
    windows,
    leftWindows,
    rightWindows,
  } = useDockedWindows();

  const state = createMemo<DockedWindowState | undefined>(() => windows().get(props.id));
  const isOpen = createMemo(() => state()?.open ?? false);
  const mode = createMemo(() => state()?.mode ?? "docked");
  const side = createMemo(() => state()?.side ?? props.defaultSide ?? "right");
  const width = createMemo(() => state()?.width ?? props.defaultWidth ?? 380);

  const [floatX, setFloatX] = createSignal(100);
  const [floatY, setFloatY] = createSignal(100);
  const [floatW, setFloatW] = createSignal(props.defaultWidth ?? 380);
  const [floatH, setFloatH] = createSignal(600);

  const [insets, setInsets] = createSignal<Insets>(getInsets());

  const isDesktop = useIsDesktop();
  const viewport = useVisualViewport();

  function sidebarOffset(): number {
    return isDesktop() ? insets().sidebar : 0;
  }

  function precedingWidth(): number {
    const list = side() === "left" ? leftWindows() : rightWindows();
    const idx = list.findIndex((w) => w.id === props.id);
    return list.slice(0, Math.max(0, idx)).reduce((sum, w) => sum + w.width, 0);
  }

  function dockedLeft(): number {
    if (side() === "left") return sidebarOffset() + precedingWidth();
    return viewport().width - DOCK_MARGIN - precedingWidth() - width();
  }

  const overlayStyle = createMemo<JSX.CSSProperties>(() => {
    if (mode() === "docked") {
      const base = {
        top: `${viewport().offsetTop + DOCK_MARGIN}px`,
        width: `${width()}px`,
        height: `${viewport().height - DOCK_MARGIN * 2}px`,
      };
      return side() === "left"
        ? { ...base, left: `${sidebarOffset() + precedingWidth()}px` }
        : { ...base, right: `${DOCK_MARGIN + precedingWidth()}px` };
    }
    return {
      left: `${viewport().offsetLeft + floatX()}px`,
      top: `${viewport().offsetTop + floatY()}px`,
      width: `${floatW()}px`,
      height: `${floatH()}px`,
    };
  });

  createEffect(
    on(state, (s) => {
      if (!s || s.mode !== "floating") return;
      if (s.x != null) setFloatX(s.x);
      if (s.y != null) setFloatY(s.y);
      if (s.height != null) setFloatH(s.height);
      setFloatW(s.width);
    }),
  );

  let dragging = false;
  let dragStartX = 0;
  let dragStartY = 0;
  let windowStartX = 0;
  let windowStartY = 0;

  function onDragStart(e: MouseEvent) {
    if ((e.target as HTMLElement).closest(".panel-close")) return;
    dragging = true;
    dragStartX = e.clientX;
    dragStartY = e.clientY;

    if (mode() === "docked") {
      windowStartX = dockedLeft();
      windowStartY = DOCK_MARGIN;
      setFloatX(windowStartX);
      setFloatY(windowStartY);
      setFloatW(width());
      setFloatH(viewport().height - DOCK_MARGIN * 2);
    } else {
      windowStartX = floatX();
      windowStartY = floatY();
    }
    e.preventDefault();
  }

  let resizing = false;
  let resizeStartX = 0;
  let resizeStartY = 0;
  let resizeStartW = 0;
  let resizeStartH = 0;
  let resizeEdge: "inner" | "corner" = "corner";

  function onResizeEdgeStart(e: MouseEvent) {
    resizing = true;
    resizeEdge = "inner";
    resizeStartX = e.clientX;
    resizeStartY = e.clientY;
    resizeStartW = width();
    resizeStartH = floatH();
    e.preventDefault();
    e.stopPropagation();
  }

  function onResizeCornerStart(e: MouseEvent) {
    resizing = true;
    resizeEdge = "corner";
    resizeStartX = e.clientX;
    resizeStartY = e.clientY;
    resizeStartW = mode() === "floating" ? floatW() : width();
    resizeStartH = floatH();
    e.preventDefault();
    e.stopPropagation();
  }

  function onMouseMove(e: MouseEvent) {
    if (dragging) {
      const newX = Math.max(0, windowStartX + (e.clientX - dragStartX));
      const newY = Math.max(0, windowStartY + (e.clientY - dragStartY));

      if (mode() === "docked") {
        const threshold =
          side() === "left"
            ? sidebarOffset() + precedingWidth() + DOCK_THRESHOLD
            : viewport().width - DOCK_MARGIN - width() - DOCK_THRESHOLD;
        const movedAway = side() === "left" ? newX > threshold : newX < threshold;

        if (movedAway) {
          undock(props.id);
          setFloatX(newX);
          setFloatY(newY);
        }
      } else {
        setFloatX(newX);
        setFloatY(newY);
      }
    } else if (resizing) {
      if (mode() === "docked") {
        const dx = e.clientX - resizeStartX;
        const dir = side() === "right" ? -1 : 1;
        const newW = Math.max(MIN_WIDTH, resizeStartW + dx * dir);
        setWidth(props.id, newW);
      } else {
        setFloatW(Math.max(MIN_WIDTH, resizeStartW + (e.clientX - resizeStartX)));
        if (resizeEdge === "corner") {
          setFloatH(Math.max(MIN_HEIGHT, resizeStartH + (e.clientY - resizeStartY)));
        }
      }
    }
  }

  function onMouseUp() {
    if (dragging) {
      if (mode() === "floating") {
        const sidebar = sidebarOffset();
        const nearLeft = floatX() < sidebar + DOCK_THRESHOLD;
        const nearRight = floatX() + floatW() > viewport().width - DOCK_THRESHOLD;

        if (nearLeft) {
          dock(props.id, "left");
        } else if (nearRight) {
          dock(props.id, "right");
        } else {
          setPosition(props.id, floatX(), floatY(), floatW(), floatH());
        }
      }
      dragging = false;
    } else if (resizing) {
      if (mode() === "floating") {
        setPosition(props.id, floatX(), floatY(), floatW(), floatH());
      }
      resizing = false;
    }
  }

  // Keeps a floating panel inside the on-screen area when it shrinks — a window
  // resize, or a keyboard covering the lower part of the viewport.
  function clampFloating() {
    if (mode() !== "floating") return;
    const maxX = viewport().width - floatW() - DOCK_MARGIN;
    if (floatX() > maxX) setFloatX(Math.max(0, maxX));
    setFloatH(
      Math.min(floatH(), Math.max(MIN_HEIGHT, viewport().height - DOCK_MARGIN * 2)),
    );
    const maxY = viewport().height - floatH() - DOCK_MARGIN;
    if (floatY() > maxY) setFloatY(Math.max(0, maxY));
  }

  createEffect(on(viewport, clampFloating, { defer: true }));

  function onClose() {
    close(props.id);
  }

  onMount(() => {
    register(props.id, {
      mode: props.defaultMode ?? "docked",
      side: props.defaultSide ?? "right",
      width: props.defaultWidth ?? 380,
    });

    const stopInsets = onInsets(setInsets);

    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", onMouseUp);

    onCleanup(() => {
      deregister(props.id);
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("mouseup", onMouseUp);
      stopInsets?.();
    });
  });

  return (
    <Show
      when={isDesktop()}
      fallback={
        <Show
          when={props.swipeToOpen}
          fallback={
            <Dialog
              show={isOpen()}
              title={props.title}
              expand
              bodyClass="p-0 flex flex-col min-h-0 overflow-hidden"
              onUpdateShow={(v) => {
                if (!v) onClose();
              }}
            >
              {props.children}
            </Dialog>
          }
        >
          <SwipeDrawer
            title={props.title}
            open={isOpen()}
            onUpdateOpen={(v) => (v ? open(props.id) : onClose())}
          >
            {props.children}
          </SwipeDrawer>
        </Show>
      }
    >
      <Show when={isOpen()}>
        <div
          class="docked-panel fixed z-50 flex flex-col overflow-hidden rounded-lg border border-neutral-100 bg-neutral-10 shadow-xl"
          style={overlayStyle()}
        >
          {/* biome-ignore lint/a11y/noStaticElementInteractions: the header is the drag surface; the close button inside it is the control. */}
          <div
            class="flex shrink-0 cursor-move select-none items-center gap-2 border-neutral-100 border-b bg-neutral-10 px-3 py-2.5"
            onMouseDown={onDragStart}
          >
            <Icon class="h-3.5 w-3.5 shrink-0 text-neutral-400" name="drag-dots" />
            <span class="flex-1 font-semibold text-neutral-800 text-size-medium">
              {props.title}
            </span>
            <div class="panel-close flex items-center gap-0.5">
              <IconButton icon="cancel" label={t("Close")} onClick={onClose} />
            </div>
          </div>

          <div class="min-h-0 flex-1 overflow-hidden">{props.children}</div>

          <Show
            when={mode() === "docked"}
            fallback={
              // biome-ignore lint/a11y/noStaticElementInteractions: a pointer-only resize affordance; keyboard resizing has no equivalent here.
              <div
                class="absolute right-0 bottom-0 h-4 w-4 cursor-se-resize"
                onMouseDown={onResizeCornerStart}
              >
                <Icon class="h-4 w-4 text-neutral-400" name="resize-handle" />
              </div>
            }
          >
            {/* biome-ignore lint/a11y/noStaticElementInteractions: a pointer-only resize affordance; keyboard resizing has no equivalent here. */}
            <div
              class="absolute top-0 h-full w-1.5 cursor-ew-resize transition-colors hover:bg-primary-200/30"
              classList={{ "left-0": side() === "right", "right-0": side() !== "right" }}
              onMouseDown={onResizeEdgeStart}
            />
          </Show>
        </div>
      </Show>
    </Show>
  );
}

// app/src/components/DockedPanel.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import {
  type DockedWindowState,
  useDockedWindows,
} from "#composeables/useDockedWindows.ts";
import { useIsDesktop } from "#composeables/useIsDesktop.ts";
import { getInsets, type Insets, onInsets } from "#utils/insets.ts";
import {
  closeXIcon,
  dragDotsIcon,
  panelRightIcon,
  resizeHandleIcon,
  windowRestoreIcon,
} from "~/src/assets/icons.ts";
import Dialog from "./Dialog.vue";

const props = defineProps<{
  id: string;
  title: string;
  defaultSide?: "left" | "right";
  defaultWidth?: number;
  defaultMode?: "docked" | "floating";
}>();

const DOCK_THRESHOLD = 100;
const DOCK_MARGIN = 6;
const MIN_WIDTH = 280;
const MIN_HEIGHT = 200;

const {
  register,
  deregister,
  close,
  dock,
  undock,
  setWidth,
  setPosition,
  windows,
  leftWindows,
  rightWindows,
} = useDockedWindows();

// Reactive window state derived from composable
const state = computed<DockedWindowState | undefined>(() => windows.value.get(props.id));
const isOpen = computed(() => state.value?.open ?? false);
const mode = computed(() => state.value?.mode ?? "docked");
const side = computed(() => state.value?.side ?? props.defaultSide ?? "right");
const width = computed(() => state.value?.width ?? props.defaultWidth ?? 380);

// Floating position refs (used during drag/resize, synced to composable on end)
const floatX = ref(100);
const floatY = ref(100);
const floatW = ref(props.defaultWidth ?? 380);
const floatH = ref(600);

// Layout insets (sidebar + docked panels), kept in sync via the inset subscriber.
const insets = ref<Insets>(getInsets());
let stopInsets: (() => void) | null = null;

// Track the md breakpoint reactively so docked positioning recomputes when the
// sidebar collapses to an overlay below it, and so the panel becomes a bottom
// drawer on mobile.
const isDesktop = useIsDesktop();

function sidebarOffset(): number {
  return isDesktop.value ? insets.value.sidebar : 0;
}

// Sum of same-side docked panel widths stacked before this one.
function precedingWidth(): number {
  const list = side.value === "left" ? leftWindows.value : rightWindows.value;
  const idx = list.findIndex((w) => w.id === props.id);
  return list.slice(0, Math.max(0, idx)).reduce((sum, w) => sum + w.width, 0);
}

// Left edge (viewport px) of this panel when docked.
function dockedLeft(): number {
  if (side.value === "left") return sidebarOffset() + precedingWidth();
  return window.innerWidth - precedingWidth() - width.value;
}

// Computed style for the fixed overlay. Docked panels derive their position
// from the inset system rather than a measured placeholder, anchoring to the
// relevant edge so no viewport math is needed: left panels sit past the sidebar
// (and any panels stacked before them), right panels stack in from the right.
const overlayStyle = computed(() => {
  if (mode.value === "docked") {
    const base = {
      top: `${DOCK_MARGIN}px`,
      width: `${width.value}px`,
      height: `calc(100vh - ${DOCK_MARGIN * 2}px)`,
    };
    return side.value === "left"
      ? { ...base, left: `${sidebarOffset() + precedingWidth()}px` }
      : { ...base, right: `${precedingWidth()}px` };
  }
  return {
    left: `${floatX.value}px`,
    top: `${floatY.value}px`,
    width: `${floatW.value}px`,
    height: `${floatH.value}px`,
  };
});

// Sync floating refs from composable state
watch(
  state,
  (s) => {
    if (!s) return;
    if (s.mode === "floating") {
      if (s.x != null) floatX.value = s.x;
      if (s.y != null) floatY.value = s.y;
      if (s.height != null) floatH.value = s.height;
      floatW.value = s.width;
    }
  },
  { immediate: true },
);

// ── Drag ──────────────────────────────────────────────────────────────────────

let dragging = false;
let dragStartX = 0;
let dragStartY = 0;
let windowStartX = 0;
let windowStartY = 0;

function onDragStart(e: MouseEvent) {
  if ((e.target as HTMLElement).closest(".panel-close")) return;
  dragging = true;
  dragStartX = e.clientX;
  dragStartY = e.clientY;

  if (mode.value === "docked") {
    // Start from docked position so the panel tracks the cursor
    windowStartX = dockedLeft();
    windowStartY = DOCK_MARGIN;
    floatX.value = windowStartX;
    floatY.value = windowStartY;
    floatW.value = width.value;
    floatH.value = window.innerHeight - DOCK_MARGIN * 2;
  } else {
    windowStartX = floatX.value;
    windowStartY = floatY.value;
  }
  e.preventDefault();
}

// ── Resize ────────────────────────────────────────────────────────────────────

let resizing = false;
let resizeStartX = 0;
let resizeStartY = 0;
let resizeStartW = 0;
let resizeStartH = 0;
let resizeEdge: "inner" | "corner" = "corner";

function onResizeEdgeStart(e: MouseEvent) {
  resizing = true;
  resizeEdge = "inner";
  resizeStartX = e.clientX;
  resizeStartY = e.clientY;
  resizeStartW = width.value;
  resizeStartH = floatH.value;
  e.preventDefault();
  e.stopPropagation();
}

function onResizeCornerStart(e: MouseEvent) {
  resizing = true;
  resizeEdge = "corner";
  resizeStartX = e.clientX;
  resizeStartY = e.clientY;
  resizeStartW = mode.value === "floating" ? floatW.value : width.value;
  resizeStartH = floatH.value;
  e.preventDefault();
  e.stopPropagation();
}

// ── Mouse event handlers (global) ─────────────────────────────────────────────

function onMouseMove(e: MouseEvent) {
  if (dragging) {
    const newX = Math.max(0, windowStartX + (e.clientX - dragStartX));
    const newY = Math.max(0, windowStartY + (e.clientY - dragStartY));

    // If docked and dragged far enough, undock
    if (mode.value === "docked") {
      const threshold =
        side.value === "left"
          ? sidebarOffset() + precedingWidth() + DOCK_THRESHOLD
          : window.innerWidth - width.value - DOCK_THRESHOLD;
      const movedAway = side.value === "left" ? newX > threshold : newX < threshold;

      if (movedAway) {
        undock(props.id);
        floatX.value = newX;
        floatY.value = newY;
      }
    } else {
      floatX.value = newX;
      floatY.value = newY;
    }
  } else if (resizing) {
    if (mode.value === "docked") {
      // Width-only resize for docked panels — the overlay repositions reactively
      // through the inset system as the width changes.
      const dx = e.clientX - resizeStartX;
      const dir = side.value === "right" ? -1 : 1;
      const newW = Math.max(MIN_WIDTH, resizeStartW + dx * dir);
      setWidth(props.id, newW);
    } else {
      // Free resize for floating
      floatW.value = Math.max(MIN_WIDTH, resizeStartW + (e.clientX - resizeStartX));
      if (resizeEdge === "corner") {
        floatH.value = Math.max(MIN_HEIGHT, resizeStartH + (e.clientY - resizeStartY));
      }
    }
  }
}

function onMouseUp() {
  if (dragging) {
    // Snap-to-dock if near edges
    if (mode.value === "floating") {
      const sidebar = sidebarOffset();
      const nearLeft = floatX.value < sidebar + DOCK_THRESHOLD;
      const nearRight = floatX.value + floatW.value > window.innerWidth - DOCK_THRESHOLD;

      if (nearLeft) {
        dock(props.id, "left");
      } else if (nearRight) {
        dock(props.id, "right");
      } else {
        setPosition(props.id, floatX.value, floatY.value, floatW.value, floatH.value);
      }
    }
    dragging = false;
  } else if (resizing) {
    if (mode.value === "floating") {
      setPosition(props.id, floatX.value, floatY.value, floatW.value, floatH.value);
    }
    resizing = false;
  }
}

function onWindowResize() {
  if (mode.value === "floating") {
    // Clamp floating position
    const maxX = window.innerWidth - floatW.value - DOCK_MARGIN;
    if (floatX.value > maxX) floatX.value = Math.max(0, maxX);
    const maxY = window.innerHeight - floatH.value - DOCK_MARGIN;
    if (floatY.value > maxY) floatY.value = Math.max(0, maxY);
  }
}

// ── Actions ───────────────────────────────────────────────────────────────────

function onClose() {
  close(props.id);
}

function onDock() {
  dock(props.id, side.value);
}

function onUndock() {
  // Position floating window roughly where the docked one was
  floatX.value = dockedLeft() + 20;
  floatY.value = 40;
  floatW.value = width.value;
  floatH.value = window.innerHeight - 80;
  undock(props.id);
  setPosition(props.id, floatX.value, floatY.value, floatW.value, floatH.value);
}

// ── Lifecycle ─────────────────────────────────────────────────────────────────

onMounted(() => {
  register(props.id, {
    mode: props.defaultMode ?? "docked",
    side: props.defaultSide ?? "right",
    width: props.defaultWidth ?? 380,
  });

  stopInsets = onInsets((s) => {
    insets.value = s;
  });

  window.addEventListener("mousemove", onMouseMove);
  window.addEventListener("mouseup", onMouseUp);
  window.addEventListener("resize", onWindowResize);
});

onUnmounted(() => {
  deregister(props.id);
  window.removeEventListener("mousemove", onMouseMove);
  window.removeEventListener("mouseup", onMouseUp);
  window.removeEventListener("resize", onWindowResize);
  stopInsets?.();
});
</script>

<template>
  <!-- Mobile: render as a bottom-drawer dialog instead of a docked/floating panel. -->
  <Dialog
    v-if="!isDesktop"
    :show="isOpen"
    :title="title"
    expand
    body-class="p-0 flex flex-col min-h-0 overflow-hidden"
    @update:show="(v) => { if (!v) onClose(); }"
  >
    <slot />
  </Dialog>

  <!-- Desktop: docked / floating overlay. -->
  <div
    v-else-if="isOpen"
    class="fixed z-50 flex flex-col bg-neutral-10 border border-neutral-100 rounded-md overflow-hidden shadow-xl"
    :style="overlayStyle"
  >
    <!-- Header / drag handle -->
    <!-- biome-ignore lint/a11y/noStaticElementInteractions: The handler forwards pointer events within this Vue component; the element is not a standalone control. -->
    <div
      class="flex items-center gap-2 px-3 py-2.5 bg-neutral-10 border-b border-neutral-100 cursor-move select-none shrink-0"
      @mousedown="onDragStart"
    >
      <!-- Drag dots -->
      <div class="svg-icon w-3.5 h-3.5 text-neutral-400 shrink-0" v-html="dragDotsIcon" />
      <span class="text-size-medium text-neutral-800 font-semibold flex-1"
        >{{ title }}</span
      >
      <!-- Right controls -->
      <div class="panel-close flex items-center gap-0.5">
        <!-- Dock/undock toggle -->
        <button
          type="button"
          v-if="mode === 'floating'"
          class="p-1 text-neutral-500 hover:text-neutral-800 rounded-sm transition-colors"
          title="Dock panel"
          @click="onDock"
        >
          <div class="svg-icon w-3.5 h-3.5" v-html="panelRightIcon" />
        </button>
        <button
          type="button"
          v-else
          class="p-1 text-neutral-500 hover:text-neutral-800 rounded-sm transition-colors"
          title="Undock panel"
          @click="onUndock"
        >
          <div class="svg-icon w-3.5 h-3.5" v-html="windowRestoreIcon" />
        </button>
        <!-- Close -->
        <button
          type="button"
          class="p-1 text-neutral-500 hover:text-neutral-800 rounded-sm transition-colors"
          @click="onClose"
        >
          <div class="svg-icon w-3.5 h-3.5" v-html="closeXIcon" />
        </button>
      </div>
    </div>

    <!-- Content -->
    <div class="flex-1 min-h-0 overflow-hidden">
      <slot />
    </div>

    <!-- Resize handle: inner edge for docked, corner for floating -->
    <!-- biome-ignore lint/a11y/noStaticElementInteractions: The handler forwards pointer events within this Vue component; the element is not a standalone control. -->
    <div
      v-if="mode === 'docked'"
      class="absolute top-0 h-full w-1.5 cursor-ew-resize hover:bg-primary-200/30 transition-colors"
      :class="side === 'right' ? 'left-0' : 'right-0'"
      @mousedown="onResizeEdgeStart"
    />
    <!-- biome-ignore lint/a11y/noStaticElementInteractions: The handler forwards pointer events within this Vue component; the element is not a standalone control. -->
    <div
      v-else
      class="absolute bottom-0 right-0 w-4 h-4 cursor-se-resize"
      @mousedown="onResizeCornerStart"
    >
      <div class="svg-icon w-4 h-4 text-neutral-400" v-html="resizeHandleIcon" />
    </div>
  </div>
</template>
