// app/src/components/DocumentExtensionViews.vue
<script setup lang="ts">
import type { ExtensionRoute } from "#api/client.ts";
import ExtensionView from "#components/ExtensionView.vue";

defineProps<{
  spaceId: string;
  views: Array<{ extensionId: string; route: ExtensionRoute }>;
}>();
</script>

<template>
  <aside v-if="views.length > 0" class="hidden min-w-0 space-y-4 lg:block">
    <ExtensionView
      v-for="{ extensionId, route } in views"
      :key="`${extensionId}-${route.path}`"
      :extensionId="extensionId"
      :routePath="route.path"
      :spaceId="spaceId"
    />
  </aside>
</template>

// app/src/components/DocumentExtensionViews.tsx
import { For, Show } from "solid-js";
import type { ExtensionRoute } from "#api/client.ts";
import { ExtensionView } from "#components/ExtensionView.tsx";

interface Props {
  spaceId: string;
  views: Array<{ extensionId: string; route: ExtensionRoute }>;
}

export function DocumentExtensionViews(props: Props) {
  return (
    <Show when={props.views.length > 0}>
      <aside class="hidden min-w-0 space-y-4 lg:block">
        <For each={props.views}>
          {({ extensionId, route }) => (
            <ExtensionView
              extensionId={extensionId}
              routePath={route.path}
              spaceId={props.spaceId}
            />
          )}
        </For>
      </aside>
    </Show>
  );
}
