// app/src/components/DocumentGroupedList.tsx
import "@atrium-ui/elements/calendar";
import "@atrium-ui/elements/popover";
import {
  createEffect,
  createMemo,
  createSignal,
  For,
  type JSX,
  on,
  onMount,
  Show,
} from "solid-js";
import type { Category, DocumentWithProperties } from "#api/client.ts";
import {
  activityIcon,
  cancelIcon,
  chevronDownIcon,
  dateIcon,
  documentIcon,
} from "#assets/icons.ts";
import { useSpace } from "#composeables/useSpace.solid.ts";
import { propertyValueToScalar, propertyValueToText } from "#documents/properties.ts";
import { formatDate } from "#utils/datetime.ts";
import { currentLang, t } from "#utils/lang.ts";
import { normalizeTimestamp, spacePath } from "#utils/utils.ts";
import { SearchSnippet } from "./SearchSnippet.tsx";

type DocumentListItem = DocumentWithProperties & {
  snippet?: string;
};

interface Props {
  items: DocumentListItem[];
  categories?: Category[];
  emptyText?: string;
  showToolbar?: boolean;
  preserveOrder?: boolean;
  /** Vue's scoped slots; a render prop is Solid's spelling of the same thing. */
  batchActions?: (selectedIds: Set<string>, deselectAll: () => void) => JSX.Element;
  rowActions?: (doc: DocumentWithProperties) => JSX.Element;
}

// ── Time grouping ────────────────────────────────────────────────────────────

const GROUP_ORDER = [
  "today",
  "yesterday",
  "earlier-this-week",
  "earlier-this-month",
  "older",
] as const;

type TimeGroup = (typeof GROUP_ORDER)[number];

function getTimeGroup(date: Date | string | number): TimeGroup {
  const d = normalizeTimestamp(date);
  const now = new Date();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const yesterdayStart = new Date(todayStart);
  yesterdayStart.setDate(yesterdayStart.getDate() - 1);
  const weekStart = new Date(todayStart);
  weekStart.setDate(weekStart.getDate() - 7);
  const monthStart = new Date(todayStart);
  monthStart.setDate(monthStart.getDate() - 30);

  if (d >= todayStart) return "today";
  if (d >= yesterdayStart) return "yesterday";
  if (d >= weekStart) return "earlier-this-week";
  if (d >= monthStart) return "earlier-this-month";
  return "older";
}

export function DocumentGroupedList(props: Props) {
  const { currentSpace } = useSpace();

  onMount(() => {
    import("#editor/elements/page-target.ts");
  });

  // ── Category lookup ────────────────────────────────────────────────────────

  const categoryBySlug = createMemo(() => {
    const map = new Map<string, Category>();
    for (const c of props.categories ?? []) map.set(c.slug, c);
    return map;
  });

  // ── Filters & sort ─────────────────────────────────────────────────────────

  const [dateRangeStart, setDateRangeStart] = createSignal<Date | null>(null);
  const [dateRangeEnd, setDateRangeEnd] = createSignal<Date | null>(null);

  const dateRangeLabel = createMemo(() => {
    const start = dateRangeStart();
    const end = dateRangeEnd();
    if (!start && !end) return null;
    const fmt = (d: Date) =>
      d.toLocaleDateString(currentLang(), {
        month: "short",
        day: "numeric",
        year: "numeric",
      });
    if (start && end) return `${fmt(start)} – ${fmt(end)}`;
    const single = start ?? end;
    return single ? fmt(single) : null;
  });

  function onCalendarChange(e: Event) {
    const value = (e.target as HTMLElement & { value?: string }).value ?? "";
    if (!value) {
      setDateRangeStart(null);
      setDateRangeEnd(null);
      return;
    }
    const [start, end] = value.split("/");
    setDateRangeStart(start ? new Date(start) : null);
    setDateRangeEnd(end ? new Date(end) : null);
  }

  function clearDateRange() {
    setDateRangeStart(null);
    setDateRangeEnd(null);
  }

  const filtered = createMemo(() => {
    let docs = props.items;
    const rangeStart = dateRangeStart();
    const rangeEnd = dateRangeEnd();
    if (rangeStart) {
      const start = rangeStart.getTime();
      docs = docs.filter((d) => normalizeTimestamp(d.updatedAt).getTime() >= start);
    }
    if (rangeEnd) {
      // include the full end day
      const end = new Date(rangeEnd);
      end.setDate(end.getDate() + 1);
      docs = docs.filter(
        (d) => normalizeTimestamp(d.updatedAt).getTime() < end.getTime(),
      );
    }
    if (props.preserveOrder) return [...docs];

    return [...docs].sort(
      (a, b) =>
        normalizeTimestamp(b.updatedAt).getTime() -
        normalizeTimestamp(a.updatedAt).getTime(),
    );
  });

  const groups = createMemo(() => {
    const map = new Map<TimeGroup, DocumentListItem[]>();
    for (const doc of filtered()) {
      const g = getTimeGroup(doc.updatedAt);
      if (!map.has(g)) map.set(g, []);
      map.get(g)?.push(doc);
    }
    return GROUP_ORDER.filter((g) => map.has(g)).map((g) => ({
      id: g,
      label: {
        today: t("Today"),
        yesterday: t("Yesterday"),
        "earlier-this-week": t("Earlier this week"),
        "earlier-this-month": t("Earlier this month"),
        older: t("Older"),
      }[g],
      docs: map.get(g) ?? [],
    }));
  });

  // ── Selection ──────────────────────────────────────────────────────────────

  const [selectedIds, setSelectedIds] = createSignal(new Set<string>());
  const allIds = createMemo(() => filtered().map((d) => d.id));
  const allSelected = createMemo(
    () => allIds().length > 0 && allIds().every((id) => selectedIds().has(id)),
  );

  let lastClickedId: string | null = null;

  function toggleSelect(id: string, event: MouseEvent) {
    const next = new Set(selectedIds());

    if (event.shiftKey && lastClickedId && lastClickedId !== id) {
      const ids = allIds();
      const from = ids.indexOf(lastClickedId);
      const to = ids.indexOf(id);
      if (from !== -1 && to !== -1) {
        const [start, end] = from < to ? [from, to] : [to, from];
        for (let i = start; i <= end; i++) next.add(ids[i]);
        setSelectedIds(next);
        return;
      }
    }

    if (next.has(id)) next.delete(id);
    else next.add(id);
    setSelectedIds(next);
    lastClickedId = id;
  }

  function deselectAll() {
    setSelectedIds(new Set<string>());
  }

  // Drop any selected id that's no longer in `items` (e.g. after paging) so
  // stale ids from a previous page never reach batch actions.
  createEffect(
    on(
      () => props.items,
      () => {
        const availableIds = new Set(allIds());
        const next = new Set<string>(
          [...selectedIds()].filter((id) => availableIds.has(id)),
        );
        if (next.size !== selectedIds().size) setSelectedIds(next);
      },
      { defer: true },
    ),
  );

  // ── Collapsed groups ───────────────────────────────────────────────────────

  const [collapsed, setCollapsed] = createSignal(new Set<TimeGroup>());
  function toggleCollapse(groupId: TimeGroup) {
    const next = new Set(collapsed());
    if (next.has(groupId)) next.delete(groupId);
    else next.add(groupId);
    setCollapsed(next);
  }

  // ── Helpers ────────────────────────────────────────────────────────────────

  function docTitle(doc: DocumentListItem) {
    const title = doc.properties?.title ?? doc.properties?.name;
    return title ? propertyValueToText(title) : t("Untitled");
  }

  function docCategoryName(doc: DocumentListItem): string | null {
    const category = doc.properties?.category;
    const slug = propertyValueToScalar(category) ?? "";
    if (!slug) return null;
    return categoryBySlug().get(slug)?.name ?? slug;
  }

  const selectionBar = () => (
    <Show when={selectedIds().size > 0}>
      <span class="text-neutral-500 text-size-small">
        {selectedIds().size} {t("selected")}
      </span>
      <button
        type="button"
        onClick={deselectAll}
        class="rounded p-1 text-neutral-400 transition-colors hover:bg-neutral-100 hover:text-neutral-700"
        title={t("Deselect all")}
      >
        <div class="svg-icon h-3.5 w-3.5" innerHTML={cancelIcon} />
      </button>
      {props.batchActions?.(selectedIds(), deselectAll)}
    </Show>
  );

  return (
    <div>
      {/* Toolbar */}
      <Show when={props.showToolbar !== false}>
        <div class="mb-4 flex items-center gap-2">
          {/* Date range picker */}
          <a-popover-trigger>
            <button
              slot="trigger"
              type="button"
              class="flex items-center gap-1.5 rounded-md border bg-background px-2.5 py-1.5 text-size-small transition-colors focus:outline-none focus:ring-1 focus:ring-primary-300"
              classList={{
                "border-primary-300 text-primary-700": !!dateRangeLabel(),
                "border-neutral-200 text-neutral-700": !dateRangeLabel(),
              }}
            >
              <div class="svg-icon h-3.5 w-3.5" innerHTML={dateIcon} />
              <span>{dateRangeLabel() ?? t("Date range")}</span>
              <Show when={dateRangeLabel()}>
                {/* biome-ignore lint/a11y/useFocusableInteractive: a nested control inside the popover trigger; the trigger itself takes the focus. */}
                {/* biome-ignore lint/a11y/useSemanticElements: a <button> here would nest inside the trigger <button>, which is invalid HTML. */}
                <span
                  role="button"
                  onClick={(event) => {
                    event.stopPropagation();
                    clearDateRange();
                  }}
                  onKeyDown={(event) => {
                    if (event.key !== "Enter" && event.key !== " ") return;
                    event.stopPropagation();
                    clearDateRange();
                  }}
                  class="ml-0.5 text-primary-400 hover:text-primary-700"
                >
                  <div class="svg-icon h-3 w-3" innerHTML={cancelIcon} />
                </span>
              </Show>
            </button>
            <a-popover placements="bottom-start">
              <div class="mt-1 rounded-lg border border-neutral-100 bg-background p-3 shadow-lg">
                <a-calendar
                  mode="range"
                  week-start="1"
                  attr:value={
                    dateRangeStart() && dateRangeEnd()
                      ? `${dateRangeStart()?.toISOString().slice(0, 10)}/${dateRangeEnd()?.toISOString().slice(0, 10)}`
                      : undefined
                  }
                  on:change={onCalendarChange}
                  style={{
                    "--calendar-selected-bg": "var(--color-primary-500)",
                    "--calendar-selected-color": "white",
                    "--calendar-range-bg": "var(--color-primary-100)",
                    "--calendar-hover-bg": "var(--color-neutral-100)",
                  }}
                />
              </div>
            </a-popover>
          </a-popover-trigger>

          <div class="flex-1" />

          {selectionBar()}
        </div>
      </Show>

      {/* Deselect + batch actions (outside toolbar, when toolbar hidden) */}
      <Show when={props.showToolbar === false}>
        <div class="mb-4 flex min-h-[32px] items-center justify-end gap-2">
          {selectionBar()}
        </div>
      </Show>

      <Show
        when={filtered().length > 0}
        fallback={
          <div class="py-12 text-center text-neutral-400 text-size-small">
            {props.items.length === 0
              ? (props.emptyText ?? t("No documents"))
              : t("No documents in the selected date range")}
          </div>
        }
      >
        <div class="space-y-4">
          <For each={groups()}>
            {(group) => (
              <div>
                {/* Group header */}
                <button
                  type="button"
                  class="mb-2 flex w-full items-center gap-2 text-left"
                  onClick={() => toggleCollapse(group.id)}
                >
                  <div
                    class="svg-icon h-3.5 w-3.5 text-neutral-400"
                    innerHTML={activityIcon}
                  />
                  <span class="font-semibold text-neutral-700 text-size-small">
                    {group.label}
                  </span>
                  <span class="rounded-full bg-neutral-100 px-1.5 py-0.5 font-medium text-[11px] text-neutral-500 tabular-nums">
                    {group.docs.length}
                  </span>
                  <div class="flex-1" />
                  <div
                    class="svg-icon h-4 w-4 text-neutral-400 transition-transform"
                    classList={{ "-rotate-90": collapsed().has(group.id) }}
                    innerHTML={chevronDownIcon}
                  />
                </button>

                {/* Group rows */}
                <a-expandable
                  attr:opened={collapsed().has(group.id) ? undefined : ""}
                  inert={collapsed().has(group.id)}
                  class="overflow-hidden rounded-lg border border-neutral-100"
                >
                  <For each={group.docs}>
                    {(doc, idx) => (
                      <page-target
                        data-document-id={doc.id}
                        data-document-type={doc.type ?? undefined}
                        data-space-id={currentSpace()?.id}
                        data-document-url={spacePath(
                          currentSpace()?.slug,
                          `/doc/${doc.slug}`,
                        )}
                        class="group/row relative flex items-center hover:bg-neutral-50 [&[data-dragging]]:opacity-50"
                        classList={{
                          "border-neutral-100 border-t": idx() !== 0,
                          "bg-primary-50 hover:bg-primary-50": selectedIds().has(doc.id),
                        }}
                      >
                        {/* Checkbox */}
                        {/* biome-ignore lint/a11y/noStaticElementInteractions: the wrapper only stops the row's click from reaching the link; the checkbox is the control. */}
                        {/* biome-ignore lint/a11y/useKeyWithClickEvents: nothing is activated here, so there is no keyboard equivalent to add. */}
                        <div
                          class="flex shrink-0 items-center self-stretch pl-3"
                          onClick={(event) => event.stopPropagation()}
                        >
                          <input
                            type="checkbox"
                            checked={selectedIds().has(doc.id)}
                            onClick={(event) => toggleSelect(doc.id, event)}
                            class="h-3.5 w-3.5 cursor-pointer accent-primary-500 opacity-0 transition-opacity group-focus-within/row:opacity-100 group-hover/row:opacity-100"
                            classList={{ "!opacity-100": selectedIds().has(doc.id) }}
                          />
                        </div>

                        {/* Link: doc icon + title + meta + badge + date */}
                        <a
                          href={
                            doc.fileUrl ??
                            spacePath(currentSpace()?.slug, `/doc/${doc.slug}`)
                          }
                          target={doc.fileUrl ? "_blank" : undefined}
                          rel={doc.fileUrl ? "noopener noreferrer" : undefined}
                          class="flex min-w-0 flex-1 items-center gap-3 px-3 py-2.5"
                        >
                          <div
                            class="svg-icon h-4 w-4 shrink-0 text-neutral-300"
                            innerHTML={documentIcon}
                          />

                          <div class="min-w-0 flex-1">
                            <p class="truncate font-medium text-neutral-800 text-size-medium">
                              {docTitle(doc)}
                            </p>
                            <p class="truncate text-[11px] text-neutral-400">
                              <Show when={docCategoryName(doc)}>
                                <span>{docCategoryName(doc)} • </span>
                              </Show>
                              <span class="capitalize">{doc.type || t("Document")}</span>
                            </p>
                            {/* Snippets are document HTML, so they render behind the
                                document-view shadow boundary and cannot style the shell. */}
                            <Show when={doc.snippet}>
                              {(snippet) => (
                                <SearchSnippet html={snippet()} class="mt-1" />
                              )}
                            </Show>
                          </div>

                          <Show when={docCategoryName(doc)}>
                            <span class="shrink-0 rounded-full bg-neutral-100 px-2 py-0.5 font-medium text-[11px] text-neutral-600">
                              {docCategoryName(doc)}
                            </span>
                          </Show>

                          <span class="w-20 shrink-0 text-right text-[11px] text-neutral-400 tabular-nums">
                            {formatDate(doc.updatedAt)}
                          </span>
                        </a>

                        {/* Row actions */}
                        {/* biome-ignore lint/a11y/noStaticElementInteractions: the wrapper only stops the row's click from reaching the link; the actions are the controls. */}
                        {/* biome-ignore lint/a11y/useKeyWithClickEvents: nothing is activated here, so there is no keyboard equivalent to add. */}
                        <div
                          class="flex shrink-0 items-center gap-1 pr-3 opacity-0 transition-opacity group-hover/row:opacity-100"
                          onClick={(event) => event.stopPropagation()}
                        >
                          {props.rowActions?.(doc)}
                        </div>
                      </page-target>
                    )}
                  </For>
                </a-expandable>
              </div>
            )}
          </For>
        </div>
      </Show>
    </div>
  );
}

// app/src/components/DocumentGroupedList.vue
<script setup lang="ts">
import "@atrium-ui/elements/calendar";
import "@atrium-ui/elements/popover";
import { computed, onMounted, ref, watch } from "vue";
import type { Category, DocumentWithProperties } from "#api/client.ts";
import {
  activityIcon,
  cancelIcon,
  chevronDownIcon,
  dateIcon,
  documentIcon,
} from "#assets/icons.ts";
import { useSpace } from "#composeables/useSpace.ts";
import { propertyValueToScalar, propertyValueToText } from "#documents/properties.ts";
import { formatDate } from "#utils/datetime.ts";
import { currentLang, t } from "#utils/lang.ts";
import { normalizeTimestamp, spacePath } from "#utils/utils.ts";
import SearchSnippet from "./SearchSnippet.vue";

type DocumentListItem = DocumentWithProperties & {
  snippet?: string;
};

const props = defineProps<{
  items: DocumentListItem[];
  categories?: Category[];
  emptyText?: string;
  showToolbar?: boolean;
  preserveOrder?: boolean;
}>();

const { currentSpace } = useSpace();

defineSlots<{
  "batch-actions"(props: { selectedIds: Set<string>; deselectAll: () => void }): unknown;
  "row-actions"(props: { doc: DocumentWithProperties }): unknown;
}>();

onMounted(() => {
  import("#editor/elements/page-target.ts");
});

// ── Category lookup ──────────────────────────────────────────────────────────

const categoryBySlug = computed(() => {
  const map = new Map<string, Category>();
  for (const c of props.categories ?? []) map.set(c.slug, c);
  return map;
});

// ── Filters & sort ───────────────────────────────────────────────────────────

const dateRangeStart = ref<Date | null>(null);
const dateRangeEnd = ref<Date | null>(null);

const dateRangeLabel = computed(() => {
  if (!dateRangeStart.value && !dateRangeEnd.value) return null;
  const fmt = (d: Date) =>
    d.toLocaleDateString(currentLang(), {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  if (dateRangeStart.value && dateRangeEnd.value) {
    return `${fmt(dateRangeStart.value)} – ${fmt(dateRangeEnd.value)}`;
  }
  return fmt((dateRangeStart.value ?? dateRangeEnd.value)!);
});

function onCalendarChange(e: Event) {
  const value = (e.target as HTMLElement & { value?: string }).value ?? "";
  if (!value) {
    dateRangeStart.value = null;
    dateRangeEnd.value = null;
    return;
  }
  const [start, end] = value.split("/");
  dateRangeStart.value = start ? new Date(start) : null;
  dateRangeEnd.value = end ? new Date(end) : null;
}

function clearDateRange() {
  dateRangeStart.value = null;
  dateRangeEnd.value = null;
}

const filtered = computed(() => {
  let docs = props.items;
  if (dateRangeStart.value) {
    const start = dateRangeStart.value.getTime();
    docs = docs.filter((d) => normalizeTimestamp(d.updatedAt).getTime() >= start);
  }
  if (dateRangeEnd.value) {
    // include the full end day
    const end = new Date(dateRangeEnd.value);
    end.setDate(end.getDate() + 1);
    docs = docs.filter((d) => normalizeTimestamp(d.updatedAt).getTime() < end.getTime());
  }
  if (props.preserveOrder) return [...docs];

  return [...docs].sort(
    (a, b) =>
      normalizeTimestamp(b.updatedAt).getTime() -
      normalizeTimestamp(a.updatedAt).getTime(),
  );
});

// ── Time grouping ────────────────────────────────────────────────────────────

const GROUP_ORDER = [
  "today",
  "yesterday",
  "earlier-this-week",
  "earlier-this-month",
  "older",
] as const;

type TimeGroup = (typeof GROUP_ORDER)[number];

function getTimeGroup(date: Date | string | number): TimeGroup {
  const d = normalizeTimestamp(date);
  const now = new Date();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const yesterdayStart = new Date(todayStart);
  yesterdayStart.setDate(yesterdayStart.getDate() - 1);
  const weekStart = new Date(todayStart);
  weekStart.setDate(weekStart.getDate() - 7);
  const monthStart = new Date(todayStart);
  monthStart.setDate(monthStart.getDate() - 30);

  if (d >= todayStart) return "today";
  if (d >= yesterdayStart) return "yesterday";
  if (d >= weekStart) return "earlier-this-week";
  if (d >= monthStart) return "earlier-this-month";
  return "older";
}

const groups = computed(() => {
  const map = new Map<TimeGroup, DocumentListItem[]>();
  for (const doc of filtered.value) {
    const g = getTimeGroup(doc.updatedAt);
    if (!map.has(g)) map.set(g, []);
    map.get(g)?.push(doc);
  }
  return GROUP_ORDER.filter((g) => map.has(g)).map((g) => ({
    id: g,
    label: {
      today: t("Today"),
      yesterday: t("Yesterday"),
      "earlier-this-week": t("Earlier this week"),
      "earlier-this-month": t("Earlier this month"),
      older: t("Older"),
    }[g],
    docs: map.get(g)!,
  }));
});

// ── Selection ────────────────────────────────────────────────────────────────

const selectedIds = ref(new Set<string>());
const allIds = computed(() => filtered.value.map((d) => d.id));
const allSelected = computed(
  () => allIds.value.length > 0 && allIds.value.every((id) => selectedIds.value.has(id)),
);

function toggleSelectAll() {
  selectedIds.value = allSelected.value ? new Set() : new Set(allIds.value);
}

const lastClickedId = ref<string | null>(null);

function toggleSelect(id: string, event: MouseEvent) {
  const next = new Set(selectedIds.value);

  if (event.shiftKey && lastClickedId.value && lastClickedId.value !== id) {
    const ids = allIds.value;
    const from = ids.indexOf(lastClickedId.value);
    const to = ids.indexOf(id);
    if (from !== -1 && to !== -1) {
      const [start, end] = from < to ? [from, to] : [to, from];
      for (let i = start; i <= end; i++) next.add(ids[i]);
      selectedIds.value = next;
      return;
    }
  }

  if (next.has(id)) next.delete(id);
  else next.add(id);
  selectedIds.value = next;
  lastClickedId.value = id;
}

function deselectAll() {
  selectedIds.value = new Set();
}

// Drop any selected id that's no longer in `items` (e.g. after paging) so
// stale ids from a previous page never reach batch actions.
watch(
  () => props.items,
  () => {
    const availableIds = new Set(allIds.value);
    const next = new Set([...selectedIds.value].filter((id) => availableIds.has(id)));
    if (next.size !== selectedIds.value.size) {
      selectedIds.value = next;
    }
  },
);

// ── Collapsed groups ─────────────────────────────────────────────────────────

const collapsed = ref(new Set<TimeGroup>());
function toggleCollapse(groupId: TimeGroup) {
  const next = new Set(collapsed.value);
  if (next.has(groupId)) next.delete(groupId);
  else next.add(groupId);
  collapsed.value = next;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function docTitle(doc: DocumentListItem) {
  const title = doc.properties?.title ?? doc.properties?.name;
  return title ? propertyValueToText(title) : t("Untitled");
}

function docCategoryName(doc: DocumentListItem): string | null {
  const category = doc.properties?.category;
  const slug = propertyValueToScalar(category) ?? "";
  if (!slug) return null;
  return categoryBySlug.value.get(slug)?.name ?? slug;
}
</script>

<template>
  <div>
    <!-- Toolbar -->
    <div v-if="showToolbar !== false" class="flex items-center gap-2 mb-4">
      <!-- Date range picker -->
      <a-popover-trigger>
        <button
          slot="trigger"
          type="button"
          class="flex items-center gap-1.5 px-2.5 py-1.5 text-size-small border rounded-md bg-background focus:outline-none focus:ring-1 focus:ring-primary-300 transition-colors"
          :class="dateRangeLabel ? 'border-primary-300 text-primary-700' : 'border-neutral-200 text-neutral-700'"
        >
          <div class="svg-icon w-3.5 h-3.5" v-html="dateIcon" />
          <span>{{ dateRangeLabel ?? t("Date range") }}</span>
          <button
            v-if="dateRangeLabel"
            type="button"
            @click.stop="clearDateRange"
            class="ml-0.5 text-primary-400 hover:text-primary-700"
          >
            <div class="svg-icon w-3 h-3" v-html="cancelIcon" />
          </button>
        </button>
        <a-popover placements="bottom-start">
          <div
            class="bg-background border border-neutral-100 rounded-lg shadow-lg p-3 mt-1"
          >
            <a-calendar
              mode="range"
              week-start="1"
              :value="dateRangeStart && dateRangeEnd
                ? `${dateRangeStart.toISOString().slice(0,10)}/${dateRangeEnd.toISOString().slice(0,10)}`
                : undefined"
              @change="onCalendarChange"
              style="
                --calendar-selected-bg: var(--color-primary-500);
                --calendar-selected-color: white;
                --calendar-range-bg: var(--color-primary-100);
                --calendar-hover-bg: var(--color-neutral-100);
              "
            />
          </div>
        </a-popover>
      </a-popover-trigger>

      <div class="flex-1" />

      <!-- Deselect + batch actions (inside toolbar) -->
      <template v-if="selectedIds.size > 0">
        <span class="text-size-small text-neutral-500"
          >{{ selectedIds.size }}
          {{ t("selected") }}</span
        >
        <button
          type="button"
          @click="deselectAll"
          class="p-1 text-neutral-400 hover:text-neutral-700 hover:bg-neutral-100 rounded transition-colors"
          :title="t('Deselect all')"
        >
          <div class="svg-icon w-3.5 h-3.5" v-html="cancelIcon" />
        </button>
        <slot
          name="batch-actions"
          :selected-ids="selectedIds"
          :deselect-all="deselectAll"
        />
      </template>
    </div>

    <!-- Deselect + batch actions (outside toolbar, when toolbar hidden) -->
    <div
      v-if="showToolbar === false"
      class="flex items-center justify-end gap-2 mb-4 min-h-[32px]"
    >
      <template v-if="selectedIds.size > 0">
        <span class="text-size-small text-neutral-500"
          >{{ selectedIds.size }}
          {{ t("selected") }}</span
        >
        <button
          type="button"
          @click="deselectAll"
          class="p-1 text-neutral-400 hover:text-neutral-700 hover:bg-neutral-100 rounded transition-colors"
          :title="t('Deselect all')"
        >
          <div class="svg-icon w-3.5 h-3.5" v-html="cancelIcon" />
        </button>
        <slot
          name="batch-actions"
          :selected-ids="selectedIds"
          :deselect-all="deselectAll"
        />
      </template>
    </div>

    <!-- Empty state -->
    <div
      v-if="filtered.length === 0"
      class="py-12 text-center text-size-small text-neutral-400"
    >
      {{ items.length === 0
          ? (emptyText ?? t("No documents"))
          : t("No documents in the selected date range") }}
    </div>

    <!-- Groups -->
    <div v-else class="space-y-4">
      <div v-for="group in groups" :key="group.id">
        <!-- Group header -->
        <button
          type="button"
          class="flex items-center gap-2 w-full text-left mb-2"
          @click="toggleCollapse(group.id)"
        >
          <div class="svg-icon w-3.5 h-3.5 text-neutral-400" v-html="activityIcon" />
          <span class="text-size-small font-semibold text-neutral-700"
            >{{ group.label }}</span
          >
          <span
            class="px-1.5 py-0.5 rounded-full bg-neutral-100 text-neutral-500 text-[11px] font-medium tabular-nums"
          >
            {{ group.docs.length }}
          </span>
          <div class="flex-1" />
          <div
            class="svg-icon w-4 h-4 text-neutral-400 transition-transform"
            :class="collapsed.has(group.id) ? '-rotate-90' : ''"
            v-html="chevronDownIcon"
          />
        </button>

        <!-- Group rows -->
        <a-expandable
          :opened="!collapsed.has(group.id)"
          :inert="collapsed.has(group.id)"
          class="border border-neutral-100 rounded-lg overflow-hidden"
        >
          <page-target
            v-for="(doc, idx) in group.docs"
            :key="doc.id"
            :data-document-id="doc.id"
            :data-document-type="doc.type ?? undefined"
            :data-space-id="currentSpace?.id"
            :data-document-url="spacePath(currentSpace?.slug, `/doc/${doc.slug}`)"
            class="relative flex items-center group/row hover:bg-neutral-50 [&[data-dragging]]:opacity-50"
            :class="[
              idx !== 0 ? 'border-t border-neutral-100' : '',
              selectedIds.has(doc.id) ? 'bg-primary-50 hover:bg-primary-50' : '',
            ]"
          >
            <!-- Checkbox -->
            <!-- biome-ignore lint/a11y/noStaticElementInteractions: The handler forwards pointer events within this Vue component; the element is not a standalone control. -->
            <!-- biome-ignore lint/a11y/useKeyWithClickEvents: This Vue event handler is supplemental to the component's keyboard interaction model. -->
            <div class="flex items-center pl-3 shrink-0 self-stretch" @click.stop>
              <input
                type="checkbox"
                :checked="selectedIds.has(doc.id)"
                @click="toggleSelect(doc.id, $event)"
                class="w-3.5 h-3.5 accent-primary-500 cursor-pointer opacity-0 group-hover/row:opacity-100 group-focus-within/row:opacity-100 transition-opacity"
                :class="selectedIds.has(doc.id) ? '!opacity-100' : ''"
              >
            </div>

            <!-- Link: doc icon + title + meta + badge + date -->
            <!-- biome-ignore lint/a11y/useValidAnchor: href is supplied by Vue's dynamic binding. -->
            <a
              :href="doc.fileUrl ?? spacePath(currentSpace?.slug, `/doc/${doc.slug}`)"
              :target="doc.fileUrl ? '_blank' : undefined"
              :rel="doc.fileUrl ? 'noopener noreferrer' : undefined"
              class="flex flex-1 items-center gap-3 px-3 py-2.5 min-w-0"
            >
              <div
                class="svg-icon w-4 h-4 shrink-0 text-neutral-300"
                v-html="documentIcon"
              />

              <div class="flex-1 min-w-0">
                <p class="text-size-medium font-medium text-neutral-800 truncate">
                  {{ docTitle(doc) }}
                </p>
                <p class="text-[11px] text-neutral-400 truncate">
                  <span v-if="docCategoryName(doc)">{{ docCategoryName(doc) }} • </span>
                  <span class="capitalize">{{ doc.type || t("Document") }}</span>
                </p>
                <!-- Snippets are document HTML, so they render behind the
                     document-view shadow boundary and cannot style the shell. -->
                <SearchSnippet v-if="doc.snippet" :html="doc.snippet" class="mt-1" />
              </div>

              <span
                v-if="docCategoryName(doc)"
                class="shrink-0 px-2 py-0.5 rounded-full bg-neutral-100 text-neutral-600 text-[11px] font-medium"
              >
                {{ docCategoryName(doc) }}
              </span>

              <span
                class="shrink-0 text-[11px] text-neutral-400 tabular-nums w-20 text-right"
              >
                {{ formatDate(doc.updatedAt) }}
              </span>
            </a>

            <!-- Row actions slot -->
            <!-- biome-ignore lint/a11y/noStaticElementInteractions: The handler forwards pointer events within this Vue component; the element is not a standalone control. -->
            <!-- biome-ignore lint/a11y/useKeyWithClickEvents: This Vue event handler is supplemental to the component's keyboard interaction model. -->
            <div
              class="flex items-center gap-1 pr-3 shrink-0 opacity-0 group-hover/row:opacity-100 transition-opacity"
              @click.stop
            >
              <slot name="row-actions" :doc="doc" />
            </div>
          </page-target>
        </a-expandable>
      </div>
    </div>
  </div>
</template>
