// server/src/components/FormField.tsx
import { type JSX, mergeProps } from "solid-js";

interface Props {
  label?: string;
  children?: JSX.Element;
}

export function FormField(props: Props) {
  const merged = mergeProps({ label: "Field Label" }, props);

  return (
    <div class="flex flex-1 flex-col gap-[4px]">
      {/* biome-ignore lint/a11y/noLabelWithoutControl: the control is supplied by the caller as children. */}
      <label class="font-medium text-neutral-800 text-size-small leading-[1.5em]">
        {merged.label}
      </label>
      {merged.children}
    </div>
  );
}

// app/src/components/FormField.vue
<script setup lang="ts">
interface Props {
  label?: string;
}

const props = withDefaults(defineProps<Props>(), {
  label: "Field Label",
});
</script>

<template>
  <div class="flex flex-col gap-[4px] flex-1">
    <!-- biome-ignore lint/a11y/noLabelWithoutControl: The Vue template control association is resolved by the rendered component. -->
    <label class="text-[12px] font-medium leading-[1.5em] text-neutral-800">
      {{ label }}
    </label>
    <slot />
  </div>
</template>
