// app/src/components/HeaderImageDialog.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import "@atrium-ui/elements/popover";
import { t } from "#utils/lang.ts";
import { Icon } from "~/src/components/index.ts";
import FileDrop from "./FileDrop.vue";

const HEADER_IMAGE_ACCEPT = "image/png,image/jpeg,image/gif,image/webp,image/svg+xml";

const props = defineProps<{ show?: boolean }>();

const emit = defineEmits<{
  "update:show": [value: boolean];
  select: [file: File];
}>();

const triggerRef = ref<HTMLButtonElement | null>(null);

watch(
  () => props.show,
  (val) => {
    if (val) triggerRef.value?.click();
  },
);

const cancelRef = ref<HTMLButtonElement | null>(null);

function close() {
  cancelRef.value?.dispatchEvent(new CustomEvent("exit", { bubbles: true }));
}

function onExit() {
  emit("update:show", false);
}

function onSelect(file: File) {
  emit("select", file);
  close();
}
</script>

<template>
  <a-popover-trigger class="group absolute left-0 top-0 w-0 h-0 overflow-hidden">
    <!-- Zero-size anchor; clicked programmatically to open the popover -->
    <button
      ref="triggerRef"
      slot="trigger"
      type="button"
      class="w-0 h-0 block overflow-hidden"
      aria-hidden="true"
      tabindex="-1"
    />

    <a-popover class="group" placements="bottom-end" @exit="onExit">
      <div
        class="w-max opacity-0 transition-opacity duration-100 group-[&[enabled]]:opacity-100"
      >
        <div
          class="bg-background border border-neutral-100 rounded-2xl shadow-large w-[400px] p-m origin-top-right scale-95 transition-all duration-150 group-[&[enabled]]:scale-100"
        >
          <div class="flex flex-col gap-s">
            <div class="flex flex-col items-center gap-5xs text-center">
              <h2 class="text-size-large font-semibold text-neutral-900">
                {{ t("Header image") }}
              </h2>
              <p class="text-small text-neutral-400">
                {{ t("Upload an image for this document") }}
              </p>
            </div>

            <FileDrop
              :accept="HEADER_IMAGE_ACCEPT"
              hint="PNG · JPEG · GIF · WebP · SVG"
              listen-paste
              @select="onSelect"
            >
              <template #default="{ isDragging, openPicker }">
                <div
                  class="flex items-center justify-center w-14 h-14 rounded-full transition-colors"
                  :class="isDragging ? 'bg-primary-100' : 'bg-primary-50'"
                >
                  <Icon name="upload" class="w-7 h-7 text-primary-500" />
                </div>

                <p class="text-size-normal text-neutral-700 text-center">
                  {{ t("Drag & drop here or") }}
                  <button
                    type="button"
                    class="text-primary-500 hover:text-primary-600 font-medium hover:underline underline-offset-2 cursor-pointer"
                    @click.stop="openPicker"
                  >
                    {{ t("choose file") }}
                  </button>
                </p>

                <p class="text-small text-neutral-400 text-center -mt-1">
                  PNG · JPEG · GIF · WebP · SVG
                </p>
              </template>
            </FileDrop>

            <button
              ref="cancelRef"
              type="button"
              class="text-small text-neutral-400 hover:text-neutral-600 text-center transition-colors"
              @click="close"
            >
              {{ t("Cancel") }}
            </button>
          </div>
        </div>
      </div>
    </a-popover>
  </a-popover-trigger>
</template>

// app/src/components/HeaderImageDialog.tsx
import { createEffect } from "solid-js";
import "@atrium-ui/elements/popover";
import { t } from "#utils/lang.ts";
import { FileDrop } from "./FileDrop.tsx";
import { Icon } from "./Icon.tsx";

const HEADER_IMAGE_ACCEPT = "image/png,image/jpeg,image/gif,image/webp,image/svg+xml";

interface Props {
  show?: boolean;
  onUpdateShow?: (value: boolean) => void;
  onSelect?: (file: File) => void;
}

export function HeaderImageDialog(props: Props) {
  let triggerRef: HTMLButtonElement | undefined;
  let cancelRef: HTMLButtonElement | undefined;

  createEffect(() => {
    if (props.show) triggerRef?.click();
  });

  function close() {
    cancelRef?.dispatchEvent(new CustomEvent("exit", { bubbles: true }));
  }

  function onSelect(file: File) {
    props.onSelect?.(file);
    close();
  }

  return (
    <a-popover-trigger class="group absolute top-0 left-0 h-0 w-0 overflow-hidden">
      {/* Zero-size anchor; clicked programmatically to open the popover */}
      <button
        ref={triggerRef}
        slot="trigger"
        type="button"
        class="block h-0 w-0 overflow-hidden"
        tabindex="-1"
      />

      <a-popover
        class="group"
        placements="bottom-end"
        on:exit={() => props.onUpdateShow?.(false)}
      >
        <div class="w-max opacity-0 transition-opacity duration-100 group-[&[enabled]]:opacity-100">
          <div class="w-[400px] origin-top-right scale-95 rounded-2xl border border-neutral-100 bg-background p-m shadow-large transition-all duration-150 group-[&[enabled]]:scale-100">
            <div class="flex flex-col gap-s">
              <div class="flex flex-col items-center gap-5xs text-center">
                <h2 class="font-semibold text-neutral-900 text-size-large">
                  {t("Header image")}
                </h2>
                <p class="text-neutral-400 text-small">
                  {t("Upload an image for this document")}
                </p>
              </div>

              <FileDrop
                accept={HEADER_IMAGE_ACCEPT}
                hint="PNG · JPEG · GIF · WebP · SVG"
                onSelect={onSelect}
              >
                {({ isDragging, openPicker }) => (
                  <>
                    <div
                      class="flex h-14 w-14 items-center justify-center rounded-full transition-colors"
                      classList={{
                        "bg-neutral-200": isDragging(),
                        "bg-neutral-100": !isDragging(),
                      }}
                    >
                      <Icon name="upload-file" class="h-7 w-7 text-neutral-500" />
                    </div>

                    <p class="text-center text-neutral-700 text-size-normal">
                      {t("Drag & drop here or")}{" "}
                      <button
                        type="button"
                        class="cursor-pointer font-medium text-neutral-700 underline-offset-2 hover:text-neutral-900 hover:underline"
                        onClick={(event) => {
                          event.stopPropagation();
                          openPicker();
                        }}
                      >
                        {t("choose file")}
                      </button>
                    </p>

                    <p class="-mt-1 text-center text-neutral-400 text-small">
                      PNG · JPEG · GIF · WebP · SVG
                    </p>
                  </>
                )}
              </FileDrop>

              <button
                ref={cancelRef}
                type="button"
                class="text-center text-neutral-400 text-small transition-colors hover:text-neutral-600"
                onClick={close}
              >
                {t("Cancel")}
              </button>
            </div>
          </div>
        </div>
      </a-popover>
    </a-popover-trigger>
  );
}
