// app/src/components/Input.vue
<script setup lang="ts">
import { ref } from "vue";

interface Props {
  placeholder?: string;
  modelValue?: string;
  type?: string;
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: "Placeholder",
  modelValue: "",
  type: "text",
  disabled: false,
});

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const isFocused = ref(false);

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit("update:modelValue", target.value);
};

const handleFocus = () => {
  isFocused.value = true;
};

const handleBlur = () => {
  isFocused.value = false;
};
</script>

<template>
  <div class="inline-flex p-[4px] bg-neutral-100 rounded-md w-full">
    <div
      class="relative flex items-center h-[36px] px-xs bg-background border rounded-sm transition-colors w-full"
      :class="{
        'border-black/15': !isFocused,
        'border-primary-500': isFocused
      }"
    >
      <input
        :value="modelValue"
        :placeholder="placeholder"
        :type="type"
        :disabled="disabled"
        @input="handleInput"
        @focus="handleFocus"
        @blur="handleBlur"
        class="w-full bg-transparent text-[14px] outline-none placeholder:opacity-30 font-normal disabled:opacity-50 disabled:cursor-not-allowed"
      />
    </div>
  </div>
</template>

// app/src/components/Input.tsx
import { createSignal, mergeProps } from "solid-js";

interface Props {
  placeholder?: string;
  /** Two-way bound value. */
  value?: string;
  type?: string;
  disabled?: boolean;
  onInput?: (value: string) => void;
}

export function Input(props: Props) {
  const merged = mergeProps(
    { placeholder: "Placeholder", value: "", type: "text", disabled: false },
    props,
  );
  const [isFocused, setIsFocused] = createSignal(false);

  return (
    <div class="inline-flex w-full rounded-md bg-neutral-100 p-[4px]">
      <div
        class="relative flex h-[36px] w-full items-center rounded-sm border bg-background px-xs transition-colors"
        classList={{
          "border-black/15": !isFocused(),
          "border-primary-500": isFocused(),
        }}
      >
        <input
          value={merged.value}
          placeholder={merged.placeholder}
          type={merged.type}
          disabled={merged.disabled}
          onInput={(event) => merged.onInput?.(event.currentTarget.value)}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setIsFocused(false)}
          class="w-full bg-transparent font-normal text-[14px] outline-none placeholder:opacity-30 disabled:cursor-not-allowed disabled:opacity-50"
        />
      </div>
    </div>
  );
}
