// app/src/components/Navigation.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, Teleport } from "vue";
import { useRouter } from "vue-router";
import { canAccessSettings, canEdit } from "#composeables/usePermissions.ts";
import { useRoute } from "#composeables/useRoute.ts";
import { type Space as ApiSpace, useSpace } from "#composeables/useSpace.ts";
import { extensions } from "#extensions/manager.ts";
import { Actions } from "#utils/actions.ts";
import { t } from "#utils/lang.ts";
import { spacePath } from "#utils/utils.ts";
import {
  commandPaletteIcon,
  extensionIcon,
  homeIcon,
  searchIcon,
  settingsIcon,
} from "~/src/assets/icons.ts";
import { MenuLink, SpaceSelector } from "~/src/components/index.ts";
import CreateSpaceDialog from "./CreateSpaceDialog.vue";
import DocumentTree from "./DocumentTree.vue";
import UserProfile from "./UserProfile.vue";

// UI-specific Space interface for the selector component
interface UiSpace {
  id: string;
  name: string;
  members?: number;
  color?: string;
  logoSvg?: string;
}

const router = useRouter();
const { pathname } = useRoute();

const { currentSpace, spaces, createSpace, isLoading: spaceIsLoading } = useSpace();

const showCreateDialog = ref(false);
const documentTree = ref<InstanceType<typeof DocumentTree> | null>(null);

const activeRoute = computed(() => {
  let activeRoute = "";

  // Determine active route
  if (pathname.value.includes("/search")) {
    activeRoute = "search";
  } else if (pathname.value.includes("/x/")) {
    // Extension route - extract the path after /x/
    const match = pathname.value.match(/\/x\/(.+)/);
    activeRoute = match ? `x/${match[1]}` : "";
  } else if (pathname.value.includes("/settings")) {
    activeRoute = "settings";
  } else if (
    pathname.value === "/" ||
    pathname.value.split("/").filter(Boolean).length === 0
  ) {
    activeRoute = "home";
  }

  return activeRoute;
});

// Extension menu links (from routes with menuItem defined)
const extensionMenuLinks = ref<
  Array<{ extensionId: string; route: string; title: string; icon?: string }>
>([]);

function updateExtensionMenuLinks() {
  extensionMenuLinks.value = extensions.getMenuLinks();
}

const isLoading = computed(() => {
  return !pathname.value || spaceIsLoading.value;
});

onMounted(() => {
  // Update menu links when extensions finish loading
  updateExtensionMenuLinks();

  // Listen for extension changes
  window.addEventListener("extensions:loaded", updateExtensionMenuLinks);
});

onUnmounted(() => {
  window.removeEventListener("extensions:loaded", updateExtensionMenuLinks);
});

// Transform app spaces to UI library Space format
const uiSpaces = computed<UiSpace[]>(() => {
  if (!spaces.value) return [];

  return spaces.value.map((space: ApiSpace) => ({
    id: space.id,
    name: space.name,
    members: space.memberCount,
    color: space.preferences?.brandColor,
    logoSvg: space.preferences?.logoSvg,
  }));
});

// Check if current user can access settings
const userCanAccessSettings = computed(() => {
  if (isLoading.value) return false;
  return canAccessSettings(currentSpace.value?.userRole);
});

// Check if current user can edit
const userCanEdit = computed(() => {
  if (isLoading.value) {
    return false;
  }
  return canEdit(currentSpace.value?.userRole);
});

const handleSpaceSelect = (space: UiSpace) => {
  const fullSpace = spaces.value?.find((s: ApiSpace) => s.id === space.id);
  if (fullSpace) {
    window.location.href = `/${fullSpace.slug}/`;
  }
};

const handleCreateClick = () => {
  showCreateDialog.value = true;
};

const handleCreateSpace = async (data: {
  name: string;
  slug: string;
  brandColor: string;
}) => {
  try {
    const newSpace = await createSpace(data.name, data.slug, {
      brandColor: data.brandColor,
    });
    window.location.href = `/${newSpace.slug}/`;
  } catch (err) {
    console.error("Failed to create space:", err);
  }
};

const handleCreateDoc = () => {
  Actions.run("document:create");
};

Actions.register("document:create", {
  title: t("Create Document"),
  description: t("Create a new document"),
  run: async () => {
    if (currentSpace.value) {
      router.push("/new");
    }
  },
});

Actions.register("find:open", {
  title: t("Find"),
  description: t("Open find document dialog"),
  run: async () => {
    if (currentSpace.value) {
      router.push("/search");
    }
  },
});

Actions.mapShortcut("meta-shift-f", "find:open");
</script>

<template>
  <div class="z-1 flex flex-col h-full">
    <!-- Space Selector -->
    <div class="px-5xs py-5xs flex-none sticky top-0 z-10 rounded-t-md flex-none">
      <CreateSpaceDialog v-model:show="showCreateDialog" @create="handleCreateSpace" />
      <SpaceSelector
        :spaces="uiSpaces"
        :model-value="currentSpace?.id"
        :can-create-docs="userCanEdit"
        :loading="isLoading"
        @select="handleSpaceSelect"
        @create="handleCreateClick"
        @create-doc="handleCreateDoc"
      />
    </div>

    <wiki-scroll
      name="navigation"
      class="flex-1 overflow-y-auto overflow-x-hidden min-w-[60px]"
    >
      <nav class="@container flex flex-col gap-3xs">
        <div class="px-3xs flex-none flex flex-col gap-0.5 pt-5xs">
          <div class="flex items-center gap-px">
            <MenuLink
              class="flex-1"
              :icon="homeIcon"
              :text="t('Home')"
              :href="spacePath(currentSpace?.slug, '/')"
              :is-active="activeRoute === 'home'"
            />
            <button
              type="button"
              class="@max-sm:hidden inline-flex items-center justify-center rounded-md text-neutral-800 transition-colors hover:transition-none hover:bg-primary-50 active:bg-primary-100 cursor-pointer flex-none w-8 min-h-[32px]"
              :title="t('Command Palette')"
              @click="Actions.run('ui:toggle:palatte')"
            >
              <span v-html="commandPaletteIcon" class="icon inline flex-none" />
            </button>
          </div>
          <MenuLink
            v-if="userCanAccessSettings"
            :icon="settingsIcon"
            :text="t('Settings')"
            :href="spacePath(currentSpace?.slug, '/settings')"
            :is-active="activeRoute === 'settings'"
          />
          <MenuLink
            :icon="searchIcon"
            :text="t('Find')"
            :href="spacePath(currentSpace?.slug, '/search')"
            :is-active="activeRoute === 'search'"
          >
            <a-shortcut
              class="ml-6 flex-none @max-xs:hidden!"
              data-shortcut="cmd-shift-f"
            ></a-shortcut>
          </MenuLink>
        </div>

        <!-- Extension Menu Links -->
        <div
          v-if="extensionMenuLinks.length > 0 && !isLoading"
          class="px-3xs flex-none flex flex-col gap-0.5"
        >
          <MenuLink
            v-for="link in extensionMenuLinks"
            :key="`${link.extensionId}-${link.route}`"
            :icon="link.icon || extensionIcon"
            :text="link.title"
            :href="spacePath(currentSpace?.slug, `/x/${link.route}`)"
            :is-active="activeRoute === `x/${link.route}`"
          />
        </div>

        <!-- Document Tree -->
        <div class="@max-xs:hidden px-5xs py-s">
          <div class="flex items-center justify-between gap-3xs px-5xs mb-1 min-h-[20px]">
            <h3
              class="text-size-extra-small font-medium text-neutral-900 uppercase tracking-wider opacity-50"
            >
              {{ t('Categories') }}
            </h3>
            <button
              type="button"
              v-if="documentTree?.isEditMode"
              @click="documentTree?.toggleEditMode()"
              class="px-1 py-0.5 text-size-extra-small font-medium text-blue-600 hover:text-blue-700 rounded-sm transition-colors"
              :title="t('Done rearranging')"
            >
              {{ t('Done') }}
            </button>
          </div>

          <DocumentTree ref="documentTree" />
        </div>
      </nav>
    </wiki-scroll>

    <!-- Bottom Actions -->
    <div class="flex-none px-1 py-3 relative flex items-center">
      <!-- User Profile -->
      <UserProfile />
    </div>
  </div>
</template>

// app/src/components/Navigation.tsx
import { useNavigate } from "@solidjs/router";
import { createMemo, createSignal, For, onCleanup, onMount, Show } from "solid-js";
import {
  commandPaletteIcon,
  extensionIcon,
  homeIcon,
  searchIcon,
  settingsIcon,
} from "#assets/icons.ts";
import { canAccessSettings, canEdit } from "#composeables/usePermissions.ts";
import { useRoute } from "#composeables/useRoute.solid.ts";
import { type Space as ApiSpace, useSpace } from "#composeables/useSpace.solid.ts";
import { extensions } from "#extensions/manager.ts";
import { Actions } from "#utils/actions.ts";
import { t } from "#utils/lang.ts";
import { spacePath } from "#utils/utils.ts";
import { CreateSpaceDialog } from "./CreateSpaceDialog.tsx";
import { DocumentTree, type DocumentTreeHandle } from "./DocumentTree.tsx";
import { MenuLink } from "./MenuLink.tsx";
import { SpaceSelector } from "./SpaceSelector.tsx";
import { UserProfile } from "./UserProfile.tsx";

export function Navigation() {
  const navigate = useNavigate();
  // The tree owns rearrange mode; the header button reads and toggles it
  // through the handle, which is Solid's spelling of Vue's template ref.
  const [documentTree, setDocumentTree] = createSignal<DocumentTreeHandle | null>(null);
  const { pathname } = useRoute();
  const { currentSpace, spaces, createSpace, isLoading: spaceIsLoading } = useSpace();

  const [showCreateDialog, setShowCreateDialog] = createSignal(false);
  const [extensionMenuLinks, setExtensionMenuLinks] = createSignal<
    Array<{ extensionId: string; route: string; title: string; icon?: string }>
  >([]);

  const activeRoute = createMemo(() => {
    const path = pathname();
    if (path.includes("/search")) return "search";
    if (path.includes("/x/")) {
      const match = path.match(/\/x\/(.+)/);
      return match ? `x/${match[1]}` : "";
    }
    if (path.includes("/settings")) return "settings";
    if (path === "/" || path.split("/").filter(Boolean).length === 0) return "home";
    return "";
  });

  const isLoading = createMemo(() => !pathname() || spaceIsLoading());

  const uiSpaces = createMemo(() =>
    (spaces() ?? []).map((space: ApiSpace) => ({
      id: space.id,
      name: space.name,
      members: space.memberCount,
      color: space.preferences?.brandColor,
      logoSvg: space.preferences?.logoSvg,
    })),
  );

  const userCanAccessSettings = createMemo(
    () => !isLoading() && canAccessSettings(currentSpace()?.userRole),
  );
  const userCanEdit = createMemo(() => !isLoading() && canEdit(currentSpace()?.userRole));

  function updateExtensionMenuLinks() {
    setExtensionMenuLinks(extensions.getMenuLinks());
  }

  onMount(() => {
    updateExtensionMenuLinks();
    window.addEventListener("extensions:loaded", updateExtensionMenuLinks);
    onCleanup(() =>
      window.removeEventListener("extensions:loaded", updateExtensionMenuLinks),
    );
  });

  Actions.register("document:create", {
    title: t("Create Document"),
    description: t("Create a new document"),
    run: async () => {
      if (currentSpace()) navigate("/new");
    },
  });

  Actions.register("find:open", {
    title: t("Find"),
    description: t("Open find document dialog"),
    run: async () => {
      if (currentSpace()) navigate("/search");
    },
  });

  Actions.mapShortcut("meta-shift-f", "find:open");

  return (
    <div class="z-1 flex h-full flex-col">
      <div class="sticky top-0 z-10 flex-none rounded-t-md px-5xs py-5xs">
        <CreateSpaceDialog
          show={showCreateDialog()}
          onUpdateShow={setShowCreateDialog}
          onCreate={async (data) => {
            try {
              const newSpace = await createSpace(data.name, data.slug, {
                brandColor: data.brandColor,
                logoSvg: data.logoSvg,
              });
              window.location.href = `/${newSpace.slug}/`;
            } catch (err) {
              console.error("Failed to create space:", err);
            }
          }}
        />
        <SpaceSelector
          spaces={uiSpaces()}
          value={currentSpace()?.id}
          canCreateDocs={userCanEdit()}
          loading={isLoading()}
          onSelect={(space) => {
            const full = spaces()?.find((s: ApiSpace) => s.id === space.id);
            if (full) window.location.href = `/${full.slug}/`;
          }}
          onCreate={() => setShowCreateDialog(true)}
          onCreateDoc={() => Actions.run("document:create")}
        />
      </div>

      <wiki-scroll
        name="navigation"
        class="min-w-[60px] flex-1 overflow-y-auto overflow-x-hidden"
      >
        <nav class="@container flex flex-col gap-3xs">
          <div class="flex flex-none flex-col gap-0.5 px-3xs pt-5xs">
            <div class="flex items-center gap-px">
              <MenuLink
                class="flex-1"
                icon={homeIcon}
                text={t("Home")}
                href={spacePath(currentSpace()?.slug, "/")}
                isActive={activeRoute() === "home"}
              />
              <button
                type="button"
                class="inline-flex @max-sm:hidden min-h-[32px] w-8 flex-none cursor-pointer items-center justify-center rounded-md text-neutral-800 transition-colors hover:bg-primary-50 hover:transition-none active:bg-primary-100"
                title={t("Command Palette")}
                onClick={() => Actions.run("ui:toggle:palatte")}
              >
                <span innerHTML={commandPaletteIcon} class="icon inline flex-none" />
              </button>
            </div>
            <Show when={userCanAccessSettings()}>
              <MenuLink
                icon={settingsIcon}
                text={t("Settings")}
                href={spacePath(currentSpace()?.slug, "/settings")}
                isActive={activeRoute() === "settings"}
              />
            </Show>
            <MenuLink
              icon={searchIcon}
              text={t("Find")}
              href={spacePath(currentSpace()?.slug, "/search")}
              isActive={activeRoute() === "search"}
            >
              <a-shortcut
                class="@max-xs:hidden! ml-6 flex-none"
                data-shortcut="cmd-shift-f"
              />
            </MenuLink>
          </div>

          <Show when={extensionMenuLinks().length > 0 && !isLoading()}>
            <div class="flex flex-none flex-col gap-0.5 px-3xs">
              <For each={extensionMenuLinks()}>
                {(link) => (
                  <MenuLink
                    icon={link.icon || extensionIcon}
                    text={link.title}
                    href={spacePath(currentSpace()?.slug, `/x/${link.route}`)}
                    isActive={activeRoute() === `x/${link.route}`}
                  />
                )}
              </For>
            </div>
          </Show>

          <div class="@max-xs:hidden px-5xs py-s">
            <div class="mb-1 flex min-h-[20px] items-center justify-between gap-3xs px-5xs">
              <h3 class="font-medium text-neutral-900 text-size-extra-small uppercase tracking-wider opacity-50">
                {t("Categories")}
              </h3>
              <Show when={documentTree()?.isEditMode()}>
                <button
                  type="button"
                  onClick={() => documentTree()?.toggleEditMode()}
                  class="rounded-sm px-1 py-0.5 font-medium text-blue-600 text-size-extra-small transition-colors hover:text-blue-700"
                  title={t("Done rearranging")}
                >
                  {t("Done")}
                </button>
              </Show>
            </div>

            <DocumentTree ref={setDocumentTree} />
          </div>
        </nav>
      </wiki-scroll>

      <div class="relative flex flex-none items-center px-1 py-3">
        <UserProfile />
      </div>
    </div>
  );
}
