// app/src/components/PagerCursor.tsx
import { Show } from "solid-js";

interface Props {
  hasPrevPage: boolean;
  hasNextPage: boolean;
  disabled?: boolean;
  /** Keep the (disabled) buttons visible when there is only one page. */
  alwaysVisible?: boolean;
  class?: string;
  onPrev?: () => void;
  onNext?: () => void;
}

export function PagerCursor(props: Props) {
  return (
    <Show when={props.alwaysVisible || props.hasPrevPage || props.hasNextPage}>
      <div
        class={`flex items-center justify-between border-neutral-100 border-t ${props.class ?? ""}`}
      >
        <button
          type="button"
          disabled={props.disabled || !props.hasPrevPage}
          class="rounded-md border border-neutral-200 px-2.5 py-1 font-medium text-size-small transition-colors hover:bg-neutral-50 disabled:cursor-not-allowed disabled:opacity-40"
          onClick={() => props.onPrev?.()}
        >
          Previous
        </button>
        <button
          type="button"
          disabled={props.disabled || !props.hasNextPage}
          class="rounded-md border border-neutral-200 px-2.5 py-1 font-medium text-size-small transition-colors hover:bg-neutral-50 disabled:cursor-not-allowed disabled:opacity-40"
          onClick={() => props.onNext?.()}
        >
          Next
        </button>
      </div>
    </Show>
  );
}

// app/src/components/PagerCursor.vue
<script setup lang="ts">
defineProps<{
  hasPrevPage: boolean;
  hasNextPage: boolean;
  disabled?: boolean;
  /** Keep the (disabled) buttons visible when there is only one page. */
  alwaysVisible?: boolean;
}>();

const emit = defineEmits<{
  prev: [];
  next: [];
}>();
</script>

<template>
  <div
    v-if="alwaysVisible || hasPrevPage || hasNextPage"
    class="flex items-center justify-between border-t border-neutral-100"
  >
    <button
      type="button"
      :disabled="disabled || !hasPrevPage"
      class="px-2.5 py-1 text-size-small font-medium border border-neutral-200 rounded-md hover:bg-neutral-50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
      @click="emit('prev')"
    >
      Previous
    </button>
    <button
      type="button"
      :disabled="disabled || !hasNextPage"
      class="px-2.5 py-1 text-size-small font-medium border border-neutral-200 rounded-md hover:bg-neutral-50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
      @click="emit('next')"
    >
      Next
    </button>
  </div>
</template>
