// server/src/components/RestoreButton.tsx
import { createSignal } from "solid-js";
import { api } from "#api/client.ts";
import { useSpace } from "#composeables/useSpace.ts";

interface Props {
  documentId: string;
}

export function RestoreButton(props: Props) {
  const [isLoading, setIsLoading] = createSignal(false);
  const { currentSpaceId } = useSpace();

  async function handleRestore() {
    if (!confirm("Are you sure you want to restore this document?")) return;

    const spaceId = currentSpaceId();
    if (!spaceId) {
      alert("No space selected");
      return;
    }

    setIsLoading(true);
    try {
      await api.document.restore(spaceId, props.documentId);
      window.location.reload();
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to restore document");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <button
      type="button"
      onClick={handleRestore}
      disabled={isLoading()}
      class="whitespace-nowrap rounded-sm bg-green-600 px-3 py-1 font-medium text-size-medium text-white hover:bg-green-700 disabled:cursor-not-allowed disabled:opacity-50"
    >
      {isLoading() ? "Restoring..." : "Restore"}
    </button>
  );
}

// app/src/components/RestoreButton.vue
<script setup lang="ts">
import { ref } from "vue";
import { api } from "#api/client.ts";
import { useSpace } from "#composeables/useSpace.ts";

const props = defineProps<{
  documentId: string;
}>();

const isLoading = ref(false);
const { currentSpaceId } = useSpace();

const handleRestore = async () => {
  if (!confirm("Are you sure you want to restore this document?")) {
    return;
  }

  if (!currentSpaceId.value) {
    alert("No space selected");
    return;
  }

  isLoading.value = true;

  try {
    await api.document.restore(currentSpaceId.value, props.documentId);

    // Reload the page to update the UI
    window.location.reload();
  } catch (err) {
    alert(err instanceof Error ? err.message : "Failed to restore document");
  } finally {
    isLoading.value = false;
  }
};
</script>

<template>
  <button
    type="button"
    @click="handleRestore"
    :disabled="isLoading"
    class="px-3 py-1 text-size-medium font-medium text-white bg-green-600 rounded-sm hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap"
  >
    {{ isLoading ? "Restoring..." : "Restore" }}
  </button>
</template>
