// app/src/components/RevisionsSidebar.tsx
import { useLocation, useNavigate } from "@solidjs/router";
import {
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
  onMount,
  Show,
} from "solid-js";
import type { AuditLog } from "#api/client.ts";
import {
  activityIcon,
  contextMenuMoreIcon,
  copyIcon,
  eyeIcon,
  pasteIcon,
  publishIcon,
  refreshIcon,
} from "#assets/icons.ts";
import { useAuditLogs } from "#composeables/useAuditLogs.ts";
import { useRevisions } from "#composeables/useRevisions.ts";
import { useSpace } from "#composeables/useSpace.ts";
import { Actions } from "#utils/actions.ts";
import { t } from "#utils/lang.ts";
import { findMemberUser, userDisplayName } from "#utils/userDisplay.ts";
import { normalizeTimestamp } from "#utils/utils.ts";
import { DockedPanel } from "./DockedPanel.tsx";
import { DocumentActivityFeed } from "./DocumentActivityFeed.tsx";
import { PagerCursor } from "./PagerCursor.tsx";
import "@atrium-ui/elements/popover";
import { useDockedWindows } from "#composeables/useDockedWindows.ts";
import { useMembers } from "#composeables/useMembers.ts";
import { useSync } from "#composeables/useSync.ts";
import { realtimeTopics } from "#realtime/protocol.ts";

interface Props {
  documentId: string;
}

const MENU_ITEM_CLASS =
  "flex w-full items-center gap-2.5 rounded-md px-3xs py-5xs text-left text-neutral-900 text-size-normal transition-colors hover:bg-primary-50 active:bg-primary-100";

function dispatchWindowEvent(event: Event) {
  if (typeof window === "undefined") return;
  window.dispatchEvent(event);
}

export function RevisionsSidebar(props: Props) {
  const {
    revisions,
    getRevision,
    publishRevision,
    fetchHistory,
    isLoading: isLoadingHistory,
  } = useRevisions(props.documentId);

  const {
    auditLogs,
    isLoading: isLoadingAudit,
    isFetching: isFetchingAudit,
    error: auditError,
    fetchAuditLogs,
    hasPrevPage: hasPrevAuditPage,
    hasNextPage: hasNextAuditPage,
    nextPage: nextAuditPage,
    prevPage: prevAuditPage,
  } = useAuditLogs(props.documentId);

  const { currentSpaceId } = useSpace();
  const navigate = useNavigate();
  const location = useLocation();
  const { members } = useMembers();

  const [publishedRev, setPublishedRev] = createSignal<number | null>(null);
  const [isPublishing, setIsPublishing] = createSignal(false);
  // Tracked but not rendered here: RevisionView owns the banner. Kept so the
  // close handler can clear it.
  const [, setSelectedRevisionNumber] = createSignal<number | null>(null);

  const { toggle: toggleWindow, windows } = useDockedWindows();
  const isOpen = createMemo(() => windows().get("revisions")?.open ?? false);

  /** Sorted audit log entries, newest first. */
  const sortedEntries = createMemo(() =>
    [...auditLogs()].sort(
      (a, b) =>
        normalizeTimestamp(b.createdAt).getTime() -
        normalizeTimestamp(a.createdAt).getTime(),
    ),
  );

  const revisionsByNumber = createMemo(() => new Map(revisions().map((r) => [r.rev, r])));

  // ── User resolver passed to DocumentActivityFeed ────────────────────────────

  function getUser(userId?: string | null) {
    return findMemberUser(members(), userId);
  }

  function getUserName(userId?: string | null): string {
    return userDisplayName(getUser(userId), userId);
  }

  // ── Per-entry helpers used in the action slot ───────────────────────────────

  function isPublishedEntry(entry: AuditLog): boolean {
    return !!entry.revisionId && entry.revisionId === publishedRev();
  }

  function isSuggestionEntry(entry: AuditLog): boolean {
    if (!entry.revisionId) return false;
    const revision = revisionsByNumber().get(entry.revisionId);
    return revision != null && revision.status !== null;
  }

  function revisionStatusOf(entry: AuditLog): string | null {
    if (!entry.revisionId) return null;
    return revisionsByNumber().get(entry.revisionId)?.status ?? null;
  }

  /** The most recent entry in a group that has a revision (used for the header action). */
  function primaryRevisionEntry(items: AuditLog[]): AuditLog | undefined {
    return items.find((i) => !!i.revisionId);
  }

  // ── Data fetching ───────────────────────────────────────────────────────────

  async function fetchPublishedRev() {
    const spaceId = currentSpaceId();
    if (!spaceId) return;
    try {
      const response = await fetch(
        `/api/v1/spaces/${spaceId}/documents/${props.documentId}`,
      );
      if (response.ok) {
        const data = await response.json();
        setPublishedRev(data.document?.publishedRev || null);
      }
    } catch (err) {
      console.error("Failed to fetch published revision:", err);
    }
  }

  async function refresh() {
    await Promise.all([fetchAuditLogs(), fetchPublishedRev(), fetchHistory()]);
  }

  // ── Revision actions ────────────────────────────────────────────────────────

  function withRevisionQuery(revisionId: number): string {
    const query = new URLSearchParams(location.search);
    query.set("revision", String(revisionId));
    return `${location.pathname}?${query.toString()}`;
  }

  async function viewRevision(revisionId: number | null | undefined) {
    if (!revisionId) return;
    const revision = await getRevision(revisionId);
    if (!revision) return;

    setSelectedRevisionNumber(revisionId);
    navigate(withRevisionQuery(revisionId), { replace: true });

    dispatchWindowEvent(
      new CustomEvent("revision:view", {
        detail: {
          revision: revisionId,
          content: revision.content,
          isSuggestion: revision.status !== null,
        },
        bubbles: true,
        composed: true,
      }),
    );
  }

  async function publishRevisionAction(revisionId: number | null | undefined) {
    if (!revisionId) return;
    setIsPublishing(true);
    try {
      const success = await publishRevision(revisionId);
      if (success) {
        setPublishedRev(revisionId);
        await refresh();
      }
    } finally {
      setIsPublishing(false);
    }
  }

  function copyRevisionLink(revisionId: number | null | undefined) {
    if (!revisionId) return;
    navigator.clipboard.writeText(
      new URL(withRevisionQuery(revisionId), window.location.origin).href,
    );
  }

  function showDiff(entry: AuditLog) {
    if (!entry.revisionId) return;
    const revision = revisionsByNumber().get(entry.revisionId);
    dispatchWindowEvent(
      new CustomEvent("revision:diff", {
        detail: { revision: entry.revisionId, isSuggestion: revision?.status !== null },
        bubbles: true,
        composed: true,
      }),
    );
  }

  function exitPopover(e: Event) {
    (e.target as Element | null)?.dispatchEvent(
      new CustomEvent("exit", { bubbles: true }),
    );
  }

  // ── Lifecycle / panel watcher ───────────────────────────────────────────────

  Actions.register("revisions:toggle", {
    title: t("Activity"),
    icon: () => "history",
    description: t("Open or close the document activity"),
    group: "document",
    run: async () => {
      toggleWindow("revisions", { side: "right", width: 420 });
    },
  });

  function onRevisionClose() {
    setSelectedRevisionNumber(null);
    const query = new URLSearchParams(location.search);
    query.delete("revision");
    const search = query.toString();
    navigate(`${location.pathname}${search ? `?${search}` : ""}`, { replace: true });
  }

  // A `?revision=` in the URL opens that revision once the space is known. On a
  // cold load the space resolves asynchronously, so this watches rather than
  // reading once — and latches, so a later space change cannot reopen it.
  let pendingUrlRevision: number | null = null;
  let urlRevisionOpened = false;

  createEffect(() => {
    if (urlRevisionOpened || pendingUrlRevision === null) return;
    if (!currentSpaceId()) return;
    urlRevisionOpened = true;
    void viewRevision(pendingUrlRevision);
  });

  onMount(() => {
    const url = new URL(window.location.href);
    const revision = url.searchParams.get("revision");

    if (revision) {
      const rev = Number.parseInt(revision, 10);
      if (!Number.isNaN(rev)) pendingUrlRevision = rev;
    }

    window.addEventListener("revision:close", onRevisionClose);
    onCleanup(() => window.removeEventListener("revision:close", onRevisionClose));
  });

  let previousOpen: boolean | undefined;
  createEffect(() => {
    const open = isOpen();
    const spaceId = currentSpaceId();
    if (open && spaceId) void refresh();
    if (open !== previousOpen) {
      previousOpen = open;
      dispatchWindowEvent(
        new CustomEvent("revisions:toggled", {
          detail: { isOpen: open },
          bubbles: true,
          composed: true,
        }),
      );
    }
  });

  useSync(
    currentSpaceId,
    () => [realtimeTopics.document(props.documentId)],
    (scopes) => {
      if (!scopes.includes(realtimeTopics.document(props.documentId))) return;

      if (isOpen()) void refresh();
      else void fetchPublishedRev();
    },
  );

  return (
    <DockedPanel
      id="revisions"
      title="Document Activity"
      defaultSide="right"
      defaultWidth={420}
    >
      <div class="relative flex h-full flex-col">
        <Show when={auditError()}>
          <div class="mx-4 mt-4 rounded-sm border border-red-200 bg-red-50 p-3 text-red-700 text-size-medium">
            {auditError()}
          </div>
        </Show>

        <Show
          when={
            !((isLoadingHistory() || isLoadingAudit()) && sortedEntries().length === 0)
          }
          fallback={
            <div class="flex flex-1 items-center justify-center">
              <div class="text-center">
                <div
                  class="svg-icon mx-auto mb-2 h-8 w-8 animate-spin text-neutral-400"
                  innerHTML={refreshIcon}
                />
                <p class="text-neutral-600 text-size-medium">Loading history...</p>
              </div>
            </div>
          }
        >
          <Show
            when={sortedEntries().length > 0}
            fallback={
              <div class="flex flex-1 items-center justify-center">
                <div class="px-4 text-center">
                  <div
                    class="svg-icon mx-auto mb-3 h-12 w-12 text-neutral-300"
                    innerHTML={activityIcon}
                  />
                  <p class="font-medium text-neutral-600">No activity yet</p>
                  <p class="mt-1 text-neutral-500 text-size-medium">
                    Activity will appear here as you work
                  </p>
                </div>
              </div>
            }
          >
            <wiki-scroll class="flex-1 overflow-y-auto" data-scroll-container>
              <div class="px-2 py-2">
                <DocumentActivityFeed
                  entries={sortedEntries()}
                  getUserName={getUserName}
                  getUser={getUser}
                  headerActions={(items) => {
                    const primary = primaryRevisionEntry(items);
                    if (!primary) return null;
                    return (
                      <div class="shrink-0">
                        <a-popover-trigger showdelay="0" hidedelay="100">
                          <button
                            type="button"
                            slot="trigger"
                            class="inline-flex h-7 w-7 items-center justify-center rounded-sm transition-colors hover:bg-neutral-200"
                            title="Revision actions"
                          >
                            <div
                              class="svg-icon h-[18px] w-[12px] text-neutral-500"
                              innerHTML={contextMenuMoreIcon}
                            />
                          </button>

                          <a-popover class="group" placements="bottom-end">
                            <div class="revision-context-menu w-max py-1 opacity-0 transition-opacity duration-100 group-[&[enabled]]:opacity-100">
                              <div class="revision-context-panel min-w-[224px] origin-top-right scale-95 rounded-lg border border-neutral-100 bg-background p-5xs shadow-large transition-transform duration-150 group-[&[enabled]]:scale-100">
                                <button
                                  type="button"
                                  onClick={(e) => {
                                    exitPopover(e);
                                    void viewRevision(primary.revisionId);
                                  }}
                                  class={MENU_ITEM_CLASS}
                                >
                                  <div
                                    class="svg-icon h-4 w-4 flex-none"
                                    innerHTML={eyeIcon}
                                  />
                                  View Revision
                                </button>
                                <button
                                  type="button"
                                  onClick={(e) => {
                                    exitPopover(e);
                                    showDiff(primary);
                                  }}
                                  class={MENU_ITEM_CLASS}
                                >
                                  <div
                                    class="svg-icon h-4 w-4 flex-none"
                                    innerHTML={pasteIcon}
                                  />
                                  Show Diff
                                </button>
                                <button
                                  type="button"
                                  onClick={(e) => {
                                    exitPopover(e);
                                    copyRevisionLink(primary.revisionId);
                                  }}
                                  class={MENU_ITEM_CLASS}
                                >
                                  <div
                                    class="svg-icon h-4 w-4 flex-none"
                                    innerHTML={copyIcon}
                                  />
                                  Copy Link
                                </button>
                                <Show
                                  when={
                                    !isPublishedEntry(primary) &&
                                    !isSuggestionEntry(primary)
                                  }
                                >
                                  <button
                                    type="button"
                                    onClick={(e) => {
                                      exitPopover(e);
                                      void publishRevisionAction(primary.revisionId);
                                    }}
                                    class={`${MENU_ITEM_CLASS} disabled:cursor-not-allowed disabled:opacity-50`}
                                    disabled={isPublishing()}
                                  >
                                    <div
                                      class="svg-icon h-4 w-4 flex-none"
                                      innerHTML={publishIcon}
                                    />
                                    Publish Revision
                                  </button>
                                </Show>
                              </div>
                            </div>
                          </a-popover>
                        </a-popover-trigger>
                      </div>
                    );
                  }}
                  entryActions={(entry) => (
                    <Show
                      when={isPublishedEntry(entry)}
                      fallback={
                        <Show when={isSuggestionEntry(entry)}>
                          <span class="shrink-0 self-center rounded-sm border border-amber-200 bg-amber-50 px-1.5 py-px font-medium text-[10px] text-amber-600 uppercase tracking-wide">
                            {revisionStatusOf(entry) === "applied"
                              ? "Applied"
                              : "Suggestion"}
                          </span>
                        </Show>
                      }
                    >
                      <span class="shrink-0 self-center rounded-sm border border-blue-200 bg-blue-50 px-1.5 py-px font-medium text-[10px] text-blue-600 uppercase tracking-wide">
                        Published
                      </span>
                    </Show>
                  )}
                />
              </div>
            </wiki-scroll>
          </Show>
        </Show>

        <PagerCursor
          class="shrink-0 px-3 py-2"
          hasPrevPage={hasPrevAuditPage()}
          hasNextPage={hasNextAuditPage()}
          disabled={isFetchingAudit()}
          onPrev={prevAuditPage}
          onNext={nextAuditPage}
        />
      </div>
    </DockedPanel>
  );
}

// app/src/components/RevisionsSidebar.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import {
  clipboardIcon,
  clockIcon,
  copyIcon,
  dotsVerticalIcon,
  eyeIcon,
  publishIcon,
  refreshIcon,
  timelineNowDotIcon,
} from "~/src/assets/icons.ts";
import type { AuditLog } from "../api/client.ts";
import { useAuditLogs } from "../composeables/useAuditLogs.ts";
import { useRevisions } from "../composeables/useRevisions.ts";
import { useRoute } from "../composeables/useRoute.ts";
import { useSpace } from "../composeables/useSpace.ts";
import { Actions } from "../utils/actions.ts";
import { replaceBrowserUrl } from "../utils/browserHistory.ts";
import { t } from "../utils/lang.ts";
import { normalizeTimestamp } from "../utils/utils.ts";
import ActivityFeed from "./ActivityFeed.vue";
import DockedPanel from "./DockedPanel.vue";
import Pager from "./Pager.vue";
import "@atrium-ui/elements/popover";
import { useDockedWindows } from "../composeables/useDockedWindows.ts";
import { useMembers } from "../composeables/useMembers.ts";
import { useSync } from "../composeables/useSync.ts";
import { realtimeTopics } from "../utils/realtime.ts";

const props = defineProps({
  documentId: {
    type: String,
    required: true,
  },
});

const {
  revisions,
  getRevision,
  publishRevision,
  fetchHistory,
  isLoading: isLoadingHistory,
} = useRevisions(props.documentId);

const {
  auditLogs,
  isLoading: isLoadingAudit,
  isFetching: isFetchingAudit,
  error: auditError,
  fetchAuditLogs,
  page,
  totalPages,
  goToPage,
} = useAuditLogs(props.documentId);

const { currentSpaceId } = useSpace();
const { spaceSlug } = useRoute();
const { members } = useMembers();

const publishedRev = ref<number | null>(null);
const isPublishing = ref(false);
const selectedRevisionNumber = ref<number | null>(null);

const { toggle: toggleWindow, windows } = useDockedWindows();
const isOpen = computed(() => windows.value.get("revisions")?.open ?? false);

function dispatchWindowEvent(event: Event) {
  if (typeof window === "undefined") return;
  window.dispatchEvent(event);
}

/** Sorted audit log entries, newest first. */
const sortedEntries = computed(() =>
  [...auditLogs.value].sort((a, b) => {
    return (
      normalizeTimestamp(b.createdAt).getTime() -
      normalizeTimestamp(a.createdAt).getTime()
    );
  }),
);

const revisionsByNumber = computed(() => new Map(revisions.value.map((r) => [r.rev, r])));

// ---------------------------------------------------------------------------
// User / document resolvers passed to ActivityFeed
// ---------------------------------------------------------------------------

function getUserName(userId?: string | null): string {
  if (!userId) return "Unknown user";
  const member = members.value?.find((m) => m.userId === userId);
  return member?.user?.name || member?.user?.email || userId;
}

function getUser(userId?: string | null) {
  if (!userId) return undefined;
  return members.value?.find((m) => m.userId === userId)?.user ?? undefined;
}

// ---------------------------------------------------------------------------
// Per-entry helpers used in the action slot
// ---------------------------------------------------------------------------

function isPublishedEntry(entry: AuditLog): boolean {
  return !!entry.revisionId && entry.revisionId === publishedRev.value;
}

function isSuggestionEntry(entry: AuditLog): boolean {
  if (!entry.revisionId) return false;
  const revision = revisionsByNumber.value.get(entry.revisionId);
  return revision != null && revision.status !== null;
}

function revisionStatusOf(entry: AuditLog): string | null {
  if (!entry.revisionId) return null;
  return revisionsByNumber.value.get(entry.revisionId)?.status ?? null;
}

/** The most recent entry in a group that has a revision (used for the header action). */
function primaryRevisionEntry(items: AuditLog[]): AuditLog | undefined {
  return items.find((i) => !!i.revisionId);
}

// ---------------------------------------------------------------------------
// Data fetching
// ---------------------------------------------------------------------------

async function fetchPublishedRev() {
  if (!currentSpaceId.value) return;
  try {
    const response = await fetch(
      `/api/v1/spaces/${currentSpaceId.value}/documents/${props.documentId}`,
    );
    if (response.ok) {
      const data = await response.json();
      publishedRev.value = data.document?.publishedRev || null;
    }
  } catch (err) {
    console.error("Failed to fetch published revision:", err);
  }
}

async function refresh() {
  await Promise.all([fetchAuditLogs(), fetchPublishedRev(), fetchHistory()]);
}

// ---------------------------------------------------------------------------
// Revision actions
// ---------------------------------------------------------------------------

async function viewRevision(revisionId: number | null | undefined) {
  if (!revisionId) return;
  const revision = await getRevision(revisionId);
  if (revision) {
    selectedRevisionNumber.value = revisionId;

    const url = new URL(window.location.href);
    url.searchParams.set("revision", revisionId.toString());
    replaceBrowserUrl(url);

    dispatchWindowEvent(
      new CustomEvent("revision:view", {
        detail: {
          revision: revisionId,
          content: revision.content,
          isSuggestion: revision.status !== null,
        },
        bubbles: true,
        composed: true,
      }),
    );
  }
}

async function publishRevisionAction(revisionId: number | null | undefined) {
  if (!revisionId) return;
  isPublishing.value = true;
  try {
    const success = await publishRevision(revisionId);
    if (success) {
      publishedRev.value = revisionId;
      await refresh();
    }
  } finally {
    isPublishing.value = false;
  }
}

function copyRevisionLink(entryId: string) {
  if (!spaceSlug.value) return;
  const url = `${window.location.origin}/${spaceSlug.value}/rev/${entryId}`;
  navigator.clipboard.writeText(url);
}

function showDiff(entry: AuditLog) {
  if (!entry.revisionId) return;
  const revision = revisionsByNumber.value.get(entry.revisionId);
  dispatchWindowEvent(
    new CustomEvent("revision:diff", {
      detail: { revision: entry.revisionId, isSuggestion: revision?.status !== null },
      bubbles: true,
      composed: true,
    }),
  );
}

function exitPopover(e: Event) {
  e.target?.dispatchEvent(new CustomEvent("exit", { bubbles: true }));
}

// ---------------------------------------------------------------------------
// Lifecycle / panel watcher
// ---------------------------------------------------------------------------

Actions.register("revisions:toggle", {
  title: t("Activity"),
  icon: () => "history",
  description: t("Open or close the document activity"),
  group: "document",
  run: async () => {
    toggleWindow("revisions", { side: "right", width: 420 });
  },
});

onMounted(() => {
  const url = new URL(window.location.href);
  const revision = url.searchParams.get("revision");

  if (revision) {
    const rev = parseInt(revision, 10);
    if (!Number.isNaN(rev)) {
      if (currentSpaceId.value) {
        viewRevision(rev);
      } else {
        const unwatch = watch(currentSpaceId, (id) => {
          if (id) {
            viewRevision(rev);
            unwatch();
          }
        });
      }
    }
  }

  window.addEventListener("revision:close", onRevisionClose);
});

onUnmounted(() => {
  window.removeEventListener("revision:close", onRevisionClose);
});

function onRevisionClose() {
  selectedRevisionNumber.value = null;
  const url = new URL(window.location.href);
  url.searchParams.delete("revision");
  replaceBrowserUrl(url);
}

watch(
  [isOpen, currentSpaceId],
  ([open, spaceId], prev) => {
    if (open && spaceId) {
      refresh();
    }
    const prevOpen = prev?.[0];
    if (open !== prevOpen) {
      dispatchWindowEvent(
        new CustomEvent("revisions:toggled", {
          detail: { isOpen: open },
          bubbles: true,
          composed: true,
        }),
      );
    }
  },
  { immediate: true },
);

useSync(
  currentSpaceId,
  () => [realtimeTopics.document(props.documentId)],
  (scopes) => {
    if (!scopes.includes(realtimeTopics.document(props.documentId))) return;

    if (isOpen.value) {
      refresh();
    } else {
      fetchPublishedRev();
    }
  },
);
</script>

<template>
  <DockedPanel id="revisions" title="Document History" default-side="right" :default-width="420">
    <div class="relative flex flex-col h-full">

      <!-- Error State -->
      <div v-if="auditError" class="mx-4 mt-4 p-3 text-size-medium text-red-700 bg-red-50 border border-red-200 rounded-sm">
        {{ auditError }}
      </div>

      <!-- Loading State -->
      <div
        v-if="(isLoadingHistory || isLoadingAudit) && sortedEntries.length === 0"
        class="flex-1 flex items-center justify-center"
      >
        <div class="text-center">
          <div class="svg-icon w-8 h-8 mx-auto mb-2 text-neutral-400 animate-spin" v-html="refreshIcon" />
          <p class="text-size-medium text-neutral-600">Loading history...</p>
        </div>
      </div>

      <!-- Empty State -->
      <div v-else-if="sortedEntries.length === 0" class="flex-1 flex items-center justify-center">
        <div class="text-center px-4">
          <div class="svg-icon w-12 h-12 mx-auto mb-3 text-neutral-300" v-html="clockIcon" />
          <p class="font-medium text-neutral-600">No activity yet</p>
          <p class="text-size-medium text-neutral-500 mt-1">Activity will appear here as you work</p>
        </div>
      </div>

      <!-- Activity Feed -->
      <wiki-scroll v-else class="flex-1 overflow-y-auto" data-scroll-container>
        <div class="py-2 px-2">
          <ActivityFeed
            :entries="sortedEntries"
            :get-user-name="getUserName"
            :get-user="getUser"
          >
            <!-- ⋯ button in the header row, acting on the most recent revision in the group -->
            <template #header-actions="{ items }">
              <div v-if="primaryRevisionEntry(items)" class="shrink-0">
                <a-popover-trigger :showdelay="0" :hidedelay="100">
                  <button
                    slot="trigger"
                    class="inline-flex items-center justify-center w-7 h-7 rounded-sm hover:bg-neutral-200 transition-colors"
                    title="Revision actions"
                  >
                    <div class="svg-icon w-[12px] h-[18px] text-neutral-500" v-html="dotsVerticalIcon" />
                  </button>

                  <a-popover @exit="console.error" class="group" placements="bottom-end">
                    <div class="w-max py-2 opacity-0 transition-opacity duration-100 group-[[enabled]]:opacity-100">
                      <div class="bg-background border border-neutral-100 rounded-lg origin-top-right scale-95 transition-all shadow-large duration-150 group-[[enabled]]:scale-100 min-w-[160px]">
                        <button
                          @click="e => { exitPopover(e); viewRevision(primaryRevisionEntry(items)!.revisionId); }"
                          class="w-full px-4 py-2 text-left text-size-medium text-neutral-800 hover:bg-neutral-100 flex items-center gap-2 transition-colors"
                        >
                          <div class="svg-icon w-4 h-4" v-html="eyeIcon" />
                          View Revision
                        </button>
                        <button
                          @click="e => { exitPopover(e); showDiff(primaryRevisionEntry(items)!); }"
                          class="w-full px-4 py-2 text-left text-size-medium text-neutral-800 hover:bg-neutral-100 flex items-center gap-2 transition-colors"
                        >
                          <div class="svg-icon w-4 h-4" v-html="clipboardIcon" />
                          Show Diff
                        </button>
                        <button
                          @click="e => { exitPopover(e); copyRevisionLink(primaryRevisionEntry(items)!.id); }"
                          class="w-full px-4 py-2 text-left text-size-medium text-neutral-800 hover:bg-neutral-100 flex items-center gap-2 transition-colors"
                        >
                          <div class="svg-icon w-4 h-4" v-html="copyIcon" />
                          Copy Link
                        </button>
                        <button
                          v-if="!isPublishedEntry(primaryRevisionEntry(items)!) && !isSuggestionEntry(primaryRevisionEntry(items)!)"
                          @click="e => { exitPopover(e); publishRevisionAction(primaryRevisionEntry(items)!.revisionId); }"
                          class="w-full px-4 py-2 text-left text-size-medium text-neutral-800 hover:bg-neutral-100 flex items-center gap-2 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                          :disabled="isPublishing"
                        >
                          <div class="svg-icon w-4 h-4" v-html="publishIcon" />
                          Publish Revision
                        </button>
                      </div>
                    </div>
                  </a-popover>
                </a-popover-trigger>
              </div>
            </template>

            <!-- Published / Suggestion badge per entry -->
            <template #entry-actions="{ entry }">
              <span
                v-if="isPublishedEntry(entry)"
                class="shrink-0 self-center px-1.5 py-px text-[10px] font-medium uppercase tracking-wide rounded-sm border border-blue-200 text-blue-600 bg-blue-50"
              >Published</span>
              <span
                v-else-if="isSuggestionEntry(entry)"
                class="shrink-0 self-center px-1.5 py-px text-[10px] font-medium uppercase tracking-wide rounded-sm border border-amber-200 text-amber-600 bg-amber-50"
              >{{ revisionStatusOf(entry) === "applied" ? "Applied" : "Suggestion" }}</span>
            </template>
          </ActivityFeed>
        </div>
      </wiki-scroll>

      <!-- Pager -->
      <Pager
        class="shrink-0 px-3 py-2"
        :page="page"
        :total-pages="totalPages"
        :disabled="isFetchingAudit"
        @change="goToPage"
      />
    </div>
  </DockedPanel>
</template>
