// app/src/components/SelectMenu.tsx
import { For, mergeProps } from "solid-js";
import type { IconName } from "./Icon.tsx";
import { SelectItem } from "./SelectItem.tsx";

export interface SelectMenuItem {
  id: string;
  label: string;
  icon?: IconName;
  iconSvg?: string;
}

interface Props {
  items?: SelectMenuItem[];
  value?: string | string[] | null;
  onInput?: (value: string) => void;
  onSelect?: (item: SelectMenuItem) => void;
}

export function SelectMenu(props: Props) {
  const merged = mergeProps({ items: [] as SelectMenuItem[], value: null }, props);

  const isSelected = (id: string) =>
    Array.isArray(merged.value) ? merged.value.includes(id) : id === merged.value;

  return (
    <div class="flex max-h-[400px] w-full min-w-[180px] flex-col gap-[4px] overflow-y-auto py-[4px]">
      <For each={merged.items}>
        {(item) => (
          <SelectItem
            icon={item.icon}
            iconSvg={item.iconSvg}
            label={item.label}
            selected={isSelected(item.id)}
            onClick={() => {
              merged.onInput?.(item.id);
              merged.onSelect?.(item);
            }}
          />
        )}
      </For>
    </div>
  );
}

// app/src/components/SelectMenu.vue
<script setup lang="ts">
import SelectItem from "./SelectItem.vue";
export interface SelectMenuItem {
  id: string;
  label: string;
  icon?: string;
}

interface Props {
  items?: SelectMenuItem[];
  modelValue?: string | string[] | null;
}

const props = withDefaults(defineProps<Props>(), {
  items: () => [],
  modelValue: null,
});

const emit = defineEmits<{
  "update:modelValue": [value: string];
  select: [item: SelectMenuItem];
}>();

const handleItemClick = (item: SelectMenuItem) => {
  emit("update:modelValue", item.id);
  emit("select", item);
};
</script>

<template>
  <div
    class="flex flex-col gap-[4px] py-[4px] w-full min-w-[180px] max-h-[400px] overflow-y-auto"
  >
    <SelectItem
      v-for="item in items"
      :key="item.id"
      :icon="item.icon"
      :label="item.label"
      :selected="Array.isArray(modelValue) ? modelValue.includes(item.id) : item.id === modelValue"
      @click="handleItemClick(item)"
    />
  </div>
</template>
