// app/src/components/SpaceApp.vue
<script setup lang="ts">
import { getCurrentInstance, onMounted, onUnmounted, provide, ref, watch } from "vue";
import {
  createMemoryHistory,
  createRouter,
  createWebHistory,
  RouterView,
} from "vue-router";
import { api } from "#api/client.ts";
import { useQueryClient } from "#composeables/query.ts";
import { provideDocumentContext } from "#composeables/useDocument.ts";
import { useRoute } from "#composeables/useRoute.ts";
import { useSpace } from "#composeables/useSpace.ts";
import shortcuts from "#config/shortcuts.json";
import { Actions } from "#utils/actions.js";
import { extensions } from "#utils/extensions.ts";
import { history } from "#utils/history.ts";
import { parseSidebarWidth } from "#utils/sidebarState.ts";
import AIChatPanel from "./AIChatPanel.vue";
import CalDAVSetupDialog from "./CalDAVSetupDialog.vue";
import ClientOnly from "./ClientOnly.vue";
import CommandPalatte from "./CommandPalatte.vue";
import DockedWindowLayout from "./DockedWindowLayout.vue";
import DocumentOverlay from "./DocumentOverlay.vue";
import MobileHeader from "./MobileHeader.vue";
import Sidebar from "./Sidebar.vue";
import ToastContainer from "./ToastContainer.vue";
import DocumentPageView from "./views/DocumentPageView.vue";
import ExtensionRouteView from "./views/ExtensionRouteView.vue";
import NotFoundView from "./views/NotFoundView.vue";
import SpaceHomeView from "./views/SpaceHomeView.vue";
import SpaceSearchView from "./views/SpaceSearchView.vue";
import SpaceSettingsView from "./views/SpaceSettingsView.vue";
import "#utils/insets.ts";

type InitialSpace = Record<string, unknown> & {
  id?: string;
  slug?: string;
};

const props = defineProps<{
  url?: string;
  initialSpace?: InitialSpace;
  initialDocument?: Record<string, unknown>;
  initialSidebarWidth?: number;
  replicaScope?: string;
}>();

const isServer = typeof window === "undefined";

if (!isServer) {
  api.setReplicaScope(props.replicaScope);
}

const routerBase = props.initialSpace?.slug ? `/${props.initialSpace.slug}/` : "/";

const router = createRouter({
  history: isServer ? createMemoryHistory(routerBase) : createWebHistory(routerBase),
  routes: [
    { path: "/", component: SpaceHomeView },
    { path: "/search", component: SpaceSearchView },
    {
      path: "/new",
      component: DocumentPageView,
      props: (route) => ({
        draftType: (route.query.type as string) ?? "",
        draftCategory: (route.query.category as string) ?? "",
      }),
    },
    { path: "/settings", component: SpaceSettingsView },
    {
      path: "/doc/:documentSlug(.*)",
      component: DocumentPageView,
      props: (route) => ({ documentSlug: route.params.documentSlug }),
    },
    { path: "/x/:pathMatch(.*)*", component: ExtensionRouteView },
    { path: "/rev/:id", redirect: "/" },
    { path: "/:pathMatch(.*)*", component: NotFoundView },
  ],
});

if (!isServer) {
  router.afterEach((to) => {
    history.log(to.fullPath, document.title);
  });
}

function isInternalHref(href: string | null): href is string {
  if (!href) return false;
  if (!href.startsWith("/") || href.startsWith("//")) return false;
  if (href.startsWith("/api/") || href.startsWith("/_")) return false;
  return true;
}

function internalPathFromUrl(href: string): string | null {
  let url: URL;
  try {
    url = new URL(href, window.location.origin);
  } catch {
    return null;
  }

  if (url.origin !== window.location.origin) return null;

  const path = `${url.pathname}${url.search}${url.hash}`;
  return isInternalHref(path) ? path : null;
}

function handleDocumentClick(e: MouseEvent) {
  // Let the browser handle modifier-clicks (new tab/window) and middle-click
  // (new tab) instead of hijacking them into an SPA navigation.
  if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;

  const anchor = (e.target as Element).closest("a");
  if (!anchor) return;
  if (anchor.getAttribute("target") === "_blank") return;
  if (anchor.hasAttribute("download")) return;

  const path = internalPathFromUrl(anchor.getAttribute("href") ?? "");
  if (!path) return;

  e.preventDefault();
  // Anchors carry the full space-scoped URL (e.g. "/{spaceSlug}/doc/foo") so
  // middle-click / open-in-new-tab resolve on the server. Strip the router base
  // before pushing so the SPA matches the base-relative route records.
  router.push(stripRouterBase(path, routerBase));
}

const instance = getCurrentInstance();
if (instance) {
  instance.appContext.app.use(router);
}

function stripRouterBase(url: string, base: string) {
  if (base === "/") return url || "/";

  const normalizedBase = base.endsWith("/") ? base.slice(0, -1) : base;
  if (url === normalizedBase) return "/";
  if (url.startsWith(`${normalizedBase}/`)) {
    return url.slice(normalizedBase.length) || "/";
  }
  return url || "/";
}

// Strip the router base so the URL is relative to the base (e.g. "/test/doc/foo" -> "/doc/foo").
// createMemoryHistory(routerBase) and createWebHistory(routerBase) both expect base-relative paths.
const ssrRelativeUrl = (() => {
  const url = props.url ?? "/";
  return stripRouterBase(url, routerBase);
})();

if (isServer) {
  await router.push(ssrRelativeUrl);
}
await router.isReady();

// Provide initial URL so useRoute() can parse params before the router's
// async initial navigation completes.
provide("ssr:url", ssrRelativeUrl);
provide("ssr:now", Date.now());

// Provide the server-resolved space ID as the source of truth.
// useSpace() reads this instead of deriving the active space from the URL slug.
const activeSpaceId = ref<string | null>(props.initialSpace?.id ?? null);
provide("space:activeId", activeSpaceId);

// Seed the query cache with SSR-fetched data so child components render
// immediately without waiting for async queries.
const queryClient = useQueryClient();
if (props.initialSpace) {
  queryClient.setQueryData(["wiki_spaces"], [props.initialSpace], { stale: true });
}
if (props.initialSpace && props.initialDocument) {
  queryClient.setQueryData(
    ["wiki_document_slug", props.initialSpace.id, props.initialDocument.slug],
    props.initialDocument,
  );
}

const { pathname } = useRoute();
const { currentSpaceId, currentSpace, spaceNotFound } = useSpace();
const documentContext = provideDocumentContext();
const isMobileSidebarOpen = ref(false);

const initialSidebarWidth = parseSidebarWidth(props.initialSidebarWidth);
const initialLayoutStyle = {
  "--sidebar-width": `${initialSidebarWidth}px`,
  "--inset-left": `${initialSidebarWidth}px`,
};

// Lightweight custom elements the app chrome needs on every route: the sidebar
// document tree (category/page targets, scroller), keyboard-shortcut hints, and
// the mobile document drawer. Register these eagerly.
function registerShellElements() {
  return Promise.all([
    import("#editor/elements/scroll.ts"),
    import("#editor/elements/category-target.ts"),
    import("#editor/elements/page-target.ts"),
    import("#editor/elements/shortcut.ts"),
    import("#editor/elements/drawer.ts"),
  ]).catch(console.error);
}

// Heavy document/editor content elements — these pull in TipTap, CodeMirror,
// Yjs and embeds. They only ever render inside document content, so keep them
// off the initial-render/hydration critical path. Custom elements upgrade
// automatically once defined, and the document renderers (e.g. PinnedDocument)
// already tolerate late registration, so deferring is safe.
function registerDocumentElements() {
  return Promise.all([
    import("#editor/document.ts"), // also registers textarea + expression
    import("#editor/elements/figma-embed.ts"),
    import("#editor/elements/html-block.ts"),
    import("#editor/elements/ticket-link.ts"),
    import("#editor/elements/user-mention.ts"),
    import("#editor/elements/cake.ts"),
  ]).catch(console.error);
}

onMounted(() => {
  document.addEventListener("click", handleDocumentClick);

  registerShellElements();

  const idle = (
    window as unknown as {
      requestIdleCallback?: (cb: () => void, opts?: { timeout: number }) => void;
    }
  ).requestIdleCallback;
  if (idle) {
    idle(() => registerDocumentElements(), { timeout: 1500 });
  } else {
    setTimeout(() => registerDocumentElements(), 200);
  }

  navigator.serviceWorker.register("/sw.js").catch(console.error);

  for (const [shortcut, actions] of Object.entries(shortcuts)) {
    for (const action of Array.isArray(actions) ? actions : [actions]) {
      Actions.mapShortcut(shortcut, action);
    }
  }

  history.log(location.pathname, document.title);

  if (activeSpaceId.value) {
    extensions.init(activeSpaceId.value).catch(console.error);
  }
});

onUnmounted(() => {
  if (!isServer) {
    document.removeEventListener("click", handleDocumentClick);
  }
});
</script>

<template>
  <div
    id="root"
    class="mx-auto relative origin-top overflow-x-clip"
    :style="initialLayoutStyle"
  >
    <div
      :class="[
        'main-content min-h-screen h-full transition-transform md:transition-none relative',
        isMobileSidebarOpen ? 'translate-x-(--sidebar-width) md:translate-x-0' : '',
      ]"
    >
      <MobileHeader :spaceName="currentSpace?.name ?? ''" :pathname="pathname" />

      <DockedWindowLayout />

      <div
        v-if="spaceNotFound"
        class="flex flex-col items-center justify-center min-h-[60vh] gap-3 text-neutral-500"
      >
        <p class="text-2xl font-semibold text-neutral-800">404</p>
        <p>Space not found.</p>
        <a href="/" class="text-sm underline hover:text-neutral-800">Go home</a>
      </div>
      <RouterView v-else />
    </div>

    <Sidebar
      :initialWidth="initialSidebarWidth"
      @mobile-open-change="isMobileSidebarOpen = $event"
    />
  </div>

  <ClientOnly>
    <CalDAVSetupDialog />
    <ToastContainer />
    <DocumentOverlay />
    <AIChatPanel :documentId="documentContext.documentId ?? ''" />
    <CommandPalatte />
  </ClientOnly>
</template>

// app/src/components/SpaceApp.tsx
import { Route, Router } from "@solidjs/router";
import { createMemo, createSignal, onCleanup, onMount, Show } from "solid-js";
import { isServer } from "solid-js/web";
import { api } from "#api/client.ts";
import { commandPaletteIcon } from "#assets/icons.ts";
import shortcuts from "#assets/shortcuts.json";
import { useQueryClient } from "#composeables/query.solid.ts";
import { SsrUrlContext } from "#composeables/useRoute.solid.ts";
import { ActiveSpaceIdContext, useSpace } from "#composeables/useSpace.solid.ts";
import { useSync } from "#composeables/useSync.solid.ts";
import { extensions } from "#extensions/manager.ts";
import { realtimeTopics } from "#realtime/protocol.ts";
import { Actions } from "#utils/actions.js";
import { history } from "#utils/history.ts";
import { setClientLang } from "#utils/lang.ts";
import { DEFAULT_SIDEBAR_WIDTH, parseSidebarWidth } from "#utils/sidebarState.ts";
import { CommandPalatte } from "./CommandPalatte.tsx";
import { DockedWindowLayout } from "./DockedWindowLayout.tsx";
import { Sidebar } from "./Sidebar.tsx";
import { ToastContainer } from "./ToastContainer.tsx";
import { NotFoundView } from "./views/NotFoundView.tsx";
import "#utils/insets.ts";

type InitialSpace = Record<string, unknown> & { id?: string; slug?: string };

interface Props {
  url?: string;
  initialSpace?: InitialSpace;
  initialDocument?: Record<string, unknown>;
  initialSidebarWidth?: number;
  replicaScope?: string;
  lang?: string;
}

/**
 * Strips the router base so a URL is relative to it — "/test/doc/foo" becomes
 * "/doc/foo". Anchors carry the full space-scoped URL so middle-click and
 * open-in-new-tab resolve on the server, but the route records are
 * base-relative.
 */
function stripRouterBase(url: string, base: string) {
  if (base === "/") return url || "/";
  const normalized = base.endsWith("/") ? base.slice(0, -1) : base;
  if (url === normalized) return "/";
  if (url.startsWith(`${normalized}/`)) return url.slice(normalized.length) || "/";
  return url || "/";
}

/**
 * Placeholder for a route whose view lands in phase 5.
 *
 * Named rather than blank: phase 4's exit is "the app boots, most routes still
 * blank", and a route that renders nothing is indistinguishable from one that
 * failed to match.
 */
function PendingView(props: { name: string }) {
  return (
    <div class="flex min-h-[60vh] flex-col items-center justify-center gap-2 text-neutral-400">
      <p class="text-size-medium">{props.name}</p>
      <p class="text-size-small">This view lands in phase 5.</p>
    </div>
  );
}

export function SpaceApp(props: Props) {
  // The island root sets the document's locale rather than providing it: `t()`
  // is called from 427 sites, most of them plain modules with no component
  // context to read from. On the server the middleware scopes it per request.
  if (!isServer) {
    setClientLang(props.lang);
    api.setReplicaScope(props.replicaScope);
  }

  const routerBase = props.initialSpace?.slug ? `/${props.initialSpace.slug}/` : "/";
  const ssrRelativeUrl = stripRouterBase(props.url ?? "/", routerBase);

  const [activeSpaceId] = createSignal<string | null>(
    (props.initialSpace?.id as string | undefined) ?? null,
  );

  // Seed the query cache with SSR-fetched data so children render immediately
  // instead of waiting on their queries.
  const queryClient = useQueryClient();
  if (props.initialSpace) {
    queryClient.setQueryData(["wiki_spaces"], [props.initialSpace], { stale: true });
  }
  if (props.initialSpace && props.initialDocument) {
    queryClient.setQueryData(
      ["wiki_document_slug", props.initialSpace.id, props.initialDocument.slug],
      props.initialDocument,
    );
  }

  const { currentSpaceId, spaceNotFound } = useSpace(activeSpaceId);
  const initialSidebarWidth = parseSidebarWidth(props.initialSidebarWidth);
  const [hasMounted, setHasMounted] = createSignal(false);
  const [mobileSidebarOffset, setMobileSidebarOffset] = createSignal(0);
  const [isMobileSidebarDragging, setIsMobileSidebarDragging] = createSignal(false);

  const isMobileViewport = () => window.matchMedia("(max-width: 767px)").matches;

  function resetMobileDrawerOnDesktop() {
    if (isMobileViewport()) return;
    setIsMobileSidebarDragging(false);
    setMobileSidebarOffset(0);
  }

  useSync(currentSpaceId, [realtimeTopics.extensions], (topics) => {
    const spaceId = currentSpaceId();
    if (!topics.includes(realtimeTopics.extensions) || !spaceId) return;
    queryClient.invalidateQueries({ queryKey: ["extensions", spaceId] });
    void extensions.refresh(spaceId).catch(console.error);
  });

  /**
   * Lightweight chrome elements every route needs — the sidebar tree targets,
   * shortcut hints and the mobile drawer. Registered eagerly.
   */
  const registerShellElements = () =>
    Promise.all([
      import("#editor/elements/scroll.ts"),
      import("#editor/elements/category-target.ts"),
      import("#editor/elements/page-target.ts"),
      import("#editor/elements/shortcut.ts"),
      import("#editor/elements/drawer.ts"),
    ]).catch(console.error);

  /**
   * Heavy document/editor elements — these pull in TipTap, Yjs and embeds. They
   * only render inside document content, so they stay off the initial-render
   * path. Custom elements upgrade once defined and the renderers tolerate late
   * registration, so deferring is safe.
   */
  const registerDocumentElements = () =>
    Promise.all([
      import("#editor/document.ts"),
      import("#editor/elements/figma-embed.ts"),
      import("#editor/elements/html-block.ts"),
      import("#editor/elements/ticket-link.ts"),
      import("#editor/elements/user-mention.ts"),
      import("#editor/elements/cake.ts"),
    ]).catch(console.error);

  onMount(() => {
    setHasMounted(true);
    window.addEventListener("resize", resetMobileDrawerOnDesktop);
    void registerShellElements();

    const idle = (
      window as unknown as {
        requestIdleCallback?: (cb: () => void, opts?: { timeout: number }) => void;
      }
    ).requestIdleCallback;
    if (idle) idle(() => void registerDocumentElements(), { timeout: 1500 });
    else setTimeout(() => void registerDocumentElements(), 200);

    navigator.serviceWorker.register("/sw.js").catch(console.error);

    for (const [shortcut, actions] of Object.entries(shortcuts)) {
      for (const action of Array.isArray(actions) ? actions : [actions]) {
        Actions.mapShortcut(shortcut, action);
      }
    }

    void history.log(location.pathname, document.title);

    const spaceId = activeSpaceId();
    if (spaceId) extensions.init(spaceId).catch(console.error);

    onCleanup(() => window.removeEventListener("resize", resetMobileDrawerOnDesktop));
  });

  const layoutStyle = createMemo(() => ({
    "--sidebar-width": `${initialSidebarWidth}px`,
    "--mobile-sidebar-width": `${Math.max(initialSidebarWidth, DEFAULT_SIDEBAR_WIDTH)}px`,
    "--inset-left": `${initialSidebarWidth}px`,
  }));

  const Shell = (shellProps: { children?: unknown }) => (
    <>
      <div
        id="root"
        class="relative mx-auto origin-top overflow-x-clip"
        style={layoutStyle()}
      >
        <div
          class="main-content relative h-full min-h-screen transition-transform will-change-transform md:transition-none"
          style={{
            transform: `translateX(${mobileSidebarOffset()}px)`,
            transition: isMobileSidebarDragging() ? "none" : undefined,
          }}
        >
          <DockedWindowLayout />

          <Show
            when={!spaceNotFound()}
            fallback={
              <div class="flex min-h-[60vh] flex-col items-center justify-center gap-3 text-neutral-500">
                <p class="font-semibold text-2xl text-neutral-800">404</p>
                <p>Space not found.</p>
                <a href="/" class="text-sm underline hover:text-neutral-800">
                  Go home
                </a>
              </div>
            }
          >
            {shellProps.children as never}
          </Show>
        </div>

        <Sidebar
          initialWidth={initialSidebarWidth}
          onMobileDragChange={(offset) => {
            if (!isMobileViewport()) return;
            setIsMobileSidebarDragging(offset !== null);
            if (offset !== null) setMobileSidebarOffset(offset);
          }}
          onMobileOpenChange={(open, width) => {
            if (!isMobileViewport()) return;
            setMobileSidebarOffset(open ? width : 0);
          }}
        />
      </div>

      <button
        type="button"
        class="fixed right-xs bottom-s z-30 flex h-14 w-14 items-center justify-center rounded-full bg-primary-100 text-white shadow-lg transition-colors hover:bg-primary-200 active:bg-primary-300 md:hidden"
        aria-label="Open command palette"
        title="Open command palette"
        onClick={() => Actions.run("ui:toggle:palatte")}
      >
        <span class="svg-icon h-7 w-7" innerHTML={commandPaletteIcon} />
      </button>

      {/* A mounted flag, *not* `<Show when={!isServer}>`.
          
          `isServer` is false during hydration, so the client would render these
          on its first pass while the server rendered nothing — and Solid's
          hydration then fails outright with "Unable to find DOM nodes for
          hydration key", taking the whole island down. Measured: the toast
          container never appeared and the palette threw.
          
          This is the same conclusion as ticket 1380, and it holds on both
          sides: for *rendering* inside a hydrated island the guard has to be a
          post-hydration flag. `isServer` is for code paths that must not run on
          the server, not for withholding markup. */}
      <Show when={hasMounted()}>
        <ToastContainer />
        <CommandPalatte />
      </Show>
    </>
  );

  return (
    <ActiveSpaceIdContext.Provider value={activeSpaceId}>
      <SsrUrlContext.Provider value={ssrRelativeUrl}>
        <Router
          base={routerBase === "/" ? undefined : routerBase.replace(/\/$/, "")}
          root={Shell}
        >
          <Route path="/" component={() => <PendingView name="Space home" />} />
          <Route path="/search" component={() => <PendingView name="Search" />} />
          <Route path="/new" component={() => <PendingView name="New document" />} />
          <Route path="/settings" component={() => <PendingView name="Settings" />} />
          <Route
            path="/doc/*documentSlug"
            component={() => <PendingView name="Document" />}
          />
          <Route path="/x/*" component={() => <PendingView name="Extension" />} />
          <Route path="*" component={NotFoundView} />
        </Router>
      </SsrUrlContext.Provider>
    </ActiveSpaceIdContext.Provider>
  );
}
