// server/src/components/SpaceApp.tsx
import { Route, Router, useParams, useSearchParams } from "@solidjs/router";
import {
  createEffect,
  createMemo,
  createSignal,
  onCleanup,
  onMount,
  Show,
} from "solid-js";
import { isServer } from "solid-js/web";
import { canEdit } from "#acl/permissions.ts";
import { api } from "#api/client.ts";
import shortcuts from "#assets/shortcuts.json";
import { islandQueryClient } from "#composeables/islandQueryClient.ts";
import { QueryClientContext } from "#composeables/query.ts";
import { LocaleContext } from "#composeables/useTranslation.ts";
import {
  DocumentContextContext,
  provideDocumentContext,
} from "#composeables/useDocument.ts";
import { SsrUrlContext } from "#composeables/useRoute.ts";
import { ActiveSpaceIdContext, useSpace } from "#composeables/useSpace.ts";
import { useSync } from "#composeables/useSync.ts";
import { useToast } from "#composeables/useToast.ts";
import { extensions } from "#extensions/manager.ts";
import { realtimeTopics } from "#realtime/protocol.ts";
import { Actions } from "#utils/actions.js";
import { history } from "#utils/history.ts";
import { hasSeenOrganizationTour, markOrganizationTourSeen } from "#utils/onboarding.ts";
import { DEFAULT_SIDEBAR_WIDTH, parseSidebarWidth } from "#utils/sidebarState.ts";
import { AIChatPanel } from "./AIChatPanel.tsx";
import { CalDAVSetupDialog } from "./CalDAVSetupDialog.tsx";
import { CommandPalatte } from "./CommandPalatte.tsx";
import { DockedWindowLayout } from "./DockedWindowLayout.tsx";
import { DocumentOrganizationTour } from "./DocumentOrganizationTour.tsx";
import { Sidebar } from "./Sidebar.tsx";
import { ToastContainer } from "./ToastContainer.tsx";
import { DocumentPageView } from "./views/DocumentPageView.tsx";
import { ExtensionRouteView } from "./views/ExtensionRouteView.tsx";
import { NotFoundView } from "./views/NotFoundView.tsx";
import { SpaceHomeView } from "./views/SpaceHomeView.tsx";
import { SpaceSearchView } from "./views/SpaceSearchView.tsx";
import { SpaceSettingsView } from "./views/SpaceSettingsView.tsx";
import "#utils/insets.ts";
import { Icon } from "./Icon.tsx";

type InitialSpace = Record<string, unknown> & { id?: string; slug?: string };

interface Props {
  url?: string;
  initialSpace?: InitialSpace;
  initialDocument?: Record<string, unknown>;
  initialSidebarWidth?: number;
  replicaScope?: string;
  lang: string;
}

function stripRouterBase(url: string, base: string) {
  if (base === "/") return url || "/";
  const normalized = base.endsWith("/") ? base.slice(0, -1) : base;
  if (url === normalized) return "/";
  if (url.startsWith(`${normalized}/`)) return url.slice(normalized.length) || "/";
  return url || "/";
}

function DocumentRoute() {
  const params = useParams<{ documentSlug?: string }>();
  return <DocumentPageView documentSlug={params.documentSlug} />;
}

function NewDocumentRoute() {
  const [searchParams] = useSearchParams<{
    type?: string;
    category?: string;
    title?: string;
    parent?: string;
  }>();
  return (
    <DocumentPageView
      draftType={searchParams.type}
      draftCategory={searchParams.category}
      draftTitle={searchParams.title}
      draftParent={searchParams.parent}
    />
  );
}

export function SpaceApp(props: Props) {
  if (!isServer) {
    api.setReplicaScope(props.replicaScope);
  }

  const routerBase = props.initialSpace?.slug ? `/${props.initialSpace.slug}/` : "/";
  const ssrRelativeUrl = stripRouterBase(
    (props.url ?? "/").split("?")[0] || "/",
    routerBase,
  );

  const [activeSpaceId] = createSignal<string | null>(
    (props.initialSpace?.id as string | undefined) ?? null,
  );

  const queryClient = islandQueryClient();

  if (props.initialSpace) {
    queryClient.setQueryData(["wiki_spaces"], [props.initialSpace], { stale: true });
  }
  if (props.initialSpace && props.initialDocument) {
    queryClient.setQueryData(
      ["wiki_document_slug", props.initialSpace.id, props.initialDocument.slug],
      props.initialDocument,
    );
  }

  const { currentSpace, currentSpaceId, spaceNotFound } = useSpace(activeSpaceId);
  const toast = useToast();
  const initialSidebarWidth = parseSidebarWidth(props.initialSidebarWidth);
  const [hasMounted, setHasMounted] = createSignal(false);
  const [mobileSidebarOffset, setMobileSidebarOffset] = createSignal(0);
  const [isMobileSidebarDragging, setIsMobileSidebarDragging] = createSignal(false);

  const [showOrganizationTour, setShowOrganizationTour] = createSignal(false);

  /**
   * Offers the organizing tour the first time this browser can actually organize.
   *
   * An effect rather than a line in `onMount` because the role is not always known
   * at mount: without the SSR prop, or on a mid-session promotion, it arrives later.
   */
  let offeredOrganizationTour = false;
  createEffect(() => {
    if (offeredOrganizationTour || !hasMounted()) return;
    if (!canEdit(currentSpace()?.userRole) || hasSeenOrganizationTour()) return;
    offeredOrganizationTour = true;
    setShowOrganizationTour(true);
  });

  const isMobileViewport = () => window.matchMedia("(max-width: 767px)").matches;

  function resetMobileDrawerOnDesktop() {
    if (isMobileViewport()) return;
    setIsMobileSidebarDragging(false);
    setMobileSidebarOffset(0);
  }

  useSync(currentSpaceId, [realtimeTopics.extensions], (topics) => {
    const spaceId = currentSpaceId();
    if (!topics.includes(realtimeTopics.extensions) || !spaceId) return;
    queryClient.invalidateQueries({ queryKey: ["extensions", spaceId] });
    void extensions.refresh(spaceId).catch(console.error);
  });

  const registerShellElements = () =>
    Promise.all([
      import("#editor/elements/category-target.ts"),
      import("#editor/elements/page-target.ts"),
      import("#editor/elements/shortcut.ts"),
      import("#editor/elements/tooltip-layer.ts"),
    ]).catch(console.error);

  const registerDocumentElements = () =>
    Promise.all([
      import("#editor/document.ts"),
      import("#editor/elements/figma-embed.ts"),
      import("#editor/elements/html-block.ts"),
      import("#editor/elements/ticket-link.ts"),
      import("#editor/elements/user-mention.ts"),
      import("#editor/elements/cake.ts"),
    ]).catch(console.error);

  onMount(() => {
    setHasMounted(true);
    window.addEventListener("resize", resetMobileDrawerOnDesktop);
    void registerShellElements();

    const idle = (
      window as unknown as {
        requestIdleCallback?: (cb: () => void, opts?: { timeout: number }) => void;
      }
    ).requestIdleCallback;
    if (idle) idle(() => void registerDocumentElements(), { timeout: 1500 });
    else setTimeout(() => void registerDocumentElements(), 200);

    navigator.serviceWorker.register("/sw.js").catch(console.error);

    for (const [shortcut, actions] of Object.entries(shortcuts)) {
      for (const action of Array.isArray(actions) ? actions : [actions]) {
        Actions.mapShortcut(shortcut, action);
      }
    }

    void history.log(location.pathname, document.title);

    const spaceId = activeSpaceId();
    if (spaceId) extensions.init(spaceId).catch(console.error);

    let redirectingAfterRevocation = false;
    let accessRefresh = Promise.resolve();

    const handleRevocation = () => {
      if (redirectingAfterRevocation) return;
      redirectingAfterRevocation = true;
      toast.show("Your access to this space was revoked.", "error", 10_000);
      setTimeout(() => window.location.assign("/spaces"), 1200);
    };

    const refreshAccess = () => {
      accessRefresh = accessRefresh
        .then(async () => {
          const previousRole = currentSpace()?.userRole;
          const spaces = await api.spaces.get();
          const refreshedSpace = spaces.find((candidate) => candidate.id === spaceId);
          if (!refreshedSpace) {
            handleRevocation();
          } else if (refreshedSpace.userRole !== previousRole) {
            toast.show("Your permissions in this space changed.", "info");
          }
        })
        .catch(console.error);
    };

    const unsubscribeAccessChanges = api.subscribeToRealtimeAccessChanges((change) => {
      if (change.spaceId !== spaceId || change.scope !== "space") return;
      if (change.access === "none") handleRevocation();
      else if (change.access === "refresh") refreshAccess();
    });

    onCleanup(() => {
      unsubscribeAccessChanges();
      window.removeEventListener("resize", resetMobileDrawerOnDesktop);
    });
  });

  const layoutStyle = createMemo(() => ({
    "--sidebar-width": `${initialSidebarWidth}px`,
    "--mobile-sidebar-width": `${Math.max(initialSidebarWidth, DEFAULT_SIDEBAR_WIDTH)}px`,
    "--inset-left": `${initialSidebarWidth}px`,
  }));

  const documentContext = provideDocumentContext();

  const Shell = (shellProps: { children?: unknown }) => (
    <>
      <div
        id="root"
        class="relative mx-auto origin-top overflow-x-clip"
        style={layoutStyle()}
      >
        <div
          class="main-content relative h-full min-h-screen transition-transform md:transition-none"
          style={{
            transform:
              mobileSidebarOffset() === 0
                ? undefined
                : `translateX(${mobileSidebarOffset() / 6}px)`,
            "will-change": mobileSidebarOffset() === 0 ? undefined : "transform",
            transition: isMobileSidebarDragging() ? "none" : undefined,
          }}
        >
          <DockedWindowLayout />

          <Show
            when={!spaceNotFound()}
            fallback={
              <div class="flex min-h-[60vh] flex-col items-center justify-center gap-3 text-neutral-500">
                <p class="font-semibold text-2xl text-neutral-800">404</p>
                <p>Space not found.</p>
                <a href="/" class="text-sm underline hover:text-neutral-800">
                  Go home
                </a>
              </div>
            }
          >
            {shellProps.children as never}
          </Show>
        </div>

        <Sidebar
          initialWidth={initialSidebarWidth}
          onMobileDragChange={(offset) => {
            if (!isMobileViewport()) return;
            setIsMobileSidebarDragging(offset !== null);
            if (offset !== null) setMobileSidebarOffset(offset);
          }}
          onMobileOpenChange={(open, width) => {
            if (!isMobileViewport()) return;
            setMobileSidebarOffset(open ? width : 0);
          }}
        />
      </div>

      <button
        type="button"
        class="fixed right-xs bottom-s z-30 flex h-14 w-14 items-center justify-center rounded-full bg-primary-100 text-white shadow-lg transition-colors hover:bg-primary-200 active:bg-primary-300 md:hidden"
        aria-label="Open command palette"
        title="Open command palette"
        onClick={() => Actions.run("ui:toggle:palatte")}
      >
        <Icon class="h-7 w-7" name="command-palette" />
      </button>

      <Show when={hasMounted()}>
        <DocumentOrganizationTour
          show={showOrganizationTour()}
          onUpdateShow={(value) => {
            // Dismissal is the only way out, so this is where "seen" is recorded.
            if (!value) markOrganizationTourSeen();
            setShowOrganizationTour(value);
          }}
        />
        <CalDAVSetupDialog />
        <ToastContainer />
        <AIChatPanel documentId={documentContext[0]().documentId ?? ""} />
        <CommandPalatte />
      </Show>
    </>
  );

  return (
    <LocaleContext.Provider value={props.lang}>
      <QueryClientContext.Provider value={queryClient}>
        <ActiveSpaceIdContext.Provider value={activeSpaceId}>
          <SsrUrlContext.Provider value={ssrRelativeUrl}>
            <DocumentContextContext.Provider value={documentContext}>
              <Router
                url={props.url ?? "/"}
                base={routerBase === "/" ? undefined : routerBase.replace(/\/$/, "")}
                root={Shell}
              >
                <Route path="/" component={SpaceHomeView} />
                <Route path="/search" component={SpaceSearchView} />
                <Route path="/new" component={NewDocumentRoute} />
                <Route path="/settings" component={SpaceSettingsView} />
                <Route path="/doc/*documentSlug" component={DocumentRoute} />
                <Route path="/x/*extensionPath" component={ExtensionRouteView} />
                <Route path="*" component={NotFoundView} />
              </Router>
            </DocumentContextContext.Provider>
          </SsrUrlContext.Provider>
        </ActiveSpaceIdContext.Provider>
      </QueryClientContext.Provider>
    </LocaleContext.Provider>
  );
}

// app/src/components/SpaceApp.vue
<script setup lang="ts">
import { getCurrentInstance, onMounted, onUnmounted, provide, ref, watch } from "vue";
import {
  createMemoryHistory,
  createRouter,
  createWebHistory,
  RouterView,
} from "vue-router";
import { useQueryClient } from "#composeables/query.ts";
import { provideDocumentContext } from "#composeables/useDocument.ts";
import { useRoute } from "#composeables/useRoute.ts";
import { useSpace } from "#composeables/useSpace.ts";
import shortcuts from "#config/shortcuts.json";
import strings from "#config/strings.json";
import { Actions } from "#utils/actions.js";
import { extensions } from "#utils/extensions.ts";
import { history } from "#utils/history.ts";
import { parseSidebarWidth } from "#utils/sidebarState.ts";
import AIChatPanel from "./AIChatPanel.vue";
import CalDAVSetupDialog from "./CalDAVSetupDialog.vue";
import ClientOnly from "./ClientOnly.vue";
import CommandPalatte from "./CommandPalatte.vue";
import DockedWindowLayout from "./DockedWindowLayout.vue";
import DocumentOverlay from "./DocumentOverlay.vue";
import MobileHeader from "./MobileHeader.vue";
import Sidebar from "./Sidebar.vue";
import ToastContainer from "./ToastContainer.vue";
import DocumentPageView from "./views/DocumentPageView.vue";
import ExtensionRouteView from "./views/ExtensionRouteView.vue";
import NotFoundView from "./views/NotFoundView.vue";
import SpaceHomeView from "./views/SpaceHomeView.vue";
import SpaceSearchView from "./views/SpaceSearchView.vue";
import SpaceSettingsView from "./views/SpaceSettingsView.vue";
import "#utils/insets.ts";

type InitialSpace = Record<string, unknown> & {
  id?: string;
  slug?: string;
};

const props = defineProps<{
  url?: string;
  initialSpace?: InitialSpace;
  initialDocument?: Record<string, unknown>;
  initialSidebarWidth?: number;
}>();

const isServer = typeof window === "undefined";

const routerBase = props.initialSpace?.slug ? `/${props.initialSpace.slug}/` : "/";

const router = createRouter({
  history: isServer ? createMemoryHistory(routerBase) : createWebHistory(routerBase),
  routes: [
    { path: "/", component: SpaceHomeView },
    { path: "/search", component: SpaceSearchView },
    {
      path: "/new",
      component: DocumentPageView,
      props: (route) => ({
        draftType: (route.query.type as string) ?? "",
        draftCategory: (route.query.category as string) ?? "",
      }),
    },
    { path: "/settings", component: SpaceSettingsView },
    {
      path: "/doc/:documentSlug(.*)",
      component: DocumentPageView,
      props: (route) => ({ documentSlug: route.params.documentSlug }),
    },
    { path: "/x/:pathMatch(.*)*", component: ExtensionRouteView },
    { path: "/rev/:id", redirect: "/" },
    { path: "/:pathMatch(.*)*", component: NotFoundView },
  ],
});

if (!isServer) {
  router.afterEach((to) => {
    history.log(to.fullPath, document.title);
  });
}

function isInternalHref(href: string | null): href is string {
  if (!href) return false;
  if (!href.startsWith("/") || href.startsWith("//")) return false;
  if (href.startsWith("/api/") || href.startsWith("/_")) return false;
  return true;
}

function internalPathFromUrl(href: string): string | null {
  let url: URL;
  try {
    url = new URL(href, window.location.origin);
  } catch {
    return null;
  }

  if (url.origin !== window.location.origin) return null;

  const path = `${url.pathname}${url.search}${url.hash}`;
  return isInternalHref(path) ? path : null;
}

function handleDocumentClick(e: MouseEvent) {
  const anchor = (e.target as Element).closest("a");
  if (!anchor) return;
  if (anchor.getAttribute("target") === "_blank") return;
  if (anchor.hasAttribute("download")) return;

  const path = internalPathFromUrl(anchor.getAttribute("href") ?? "");
  if (!path) return;

  e.preventDefault();
  // Anchors carry the full space-scoped URL (e.g. "/{spaceSlug}/doc/foo") so
  // middle-click / open-in-new-tab resolve on the server. Strip the router base
  // before pushing so the SPA matches the base-relative route records.
  router.push(stripRouterBase(path, routerBase));
}

const instance = getCurrentInstance();
if (instance) {
  instance.appContext.app.use(router);
}

function stripRouterBase(url: string, base: string) {
  if (base === "/") return url || "/";

  const normalizedBase = base.endsWith("/") ? base.slice(0, -1) : base;
  if (url === normalizedBase) return "/";
  if (url.startsWith(`${normalizedBase}/`)) {
    return url.slice(normalizedBase.length) || "/";
  }
  return url || "/";
}

// Strip the router base so the URL is relative to the base (e.g. "/test/doc/foo" -> "/doc/foo").
// createMemoryHistory(routerBase) and createWebHistory(routerBase) both expect base-relative paths.
const ssrRelativeUrl = (() => {
  const url = props.url ?? "/";
  return stripRouterBase(url, routerBase);
})();

if (isServer) {
  await router.push(ssrRelativeUrl);
}
await router.isReady();

// Provide initial URL so useRoute() can parse params before the router's
// async initial navigation completes.
provide("ssr:url", ssrRelativeUrl);
provide("ssr:now", Date.now());

// Provide the server-resolved space ID as the source of truth.
// useSpace() reads this instead of deriving the active space from the URL slug.
const activeSpaceId = ref<string | null>(props.initialSpace?.id ?? null);
provide("space:activeId", activeSpaceId);

// Seed the query cache with SSR-fetched data so child components render
// immediately without waiting for async queries.
const queryClient = useQueryClient();
if (props.initialSpace) {
  queryClient.setQueryData(["wiki_spaces"], [props.initialSpace], { stale: true });
}
if (props.initialSpace && props.initialDocument) {
  queryClient.setQueryData(
    ["wiki_document_slug", props.initialSpace.id, props.initialDocument.slug],
    props.initialDocument,
  );
}

const { pathname } = useRoute();
const { currentSpaceId, currentSpace, spaceNotFound } = useSpace();
const documentContext = provideDocumentContext();
const isMobileSidebarOpen = ref(false);

const lang =
  typeof document !== "undefined" ? document.documentElement.lang || "en" : "en";
globalThis._translations = strings;

const initialSidebarWidth = parseSidebarWidth(props.initialSidebarWidth);
const initialLayoutStyle = {
  "--sidebar-width": `${initialSidebarWidth}px`,
  "--inset-left": `${initialSidebarWidth}px`,
};

onMounted(async () => {
  document.addEventListener("click", handleDocumentClick);

  await Promise.all([
    import("#editor/elements/textarea.ts"),
    import("#editor/elements/expression.ts"),
    import("#editor/document.ts"),
    import("#editor/elements/figma-embed.ts"),
    import("#editor/elements/html-block.ts"),
    import("#editor/elements/ticket-link.ts"),
    import("#editor/elements/user-mention.ts"),
    import("#editor/elements/scroll.ts"),
    import("#editor/elements/page-target.ts"),
    import("#editor/elements/category-target.ts"),
    import("#editor/elements/drawer.ts"),
    import("#editor/elements/shortcut.ts"),
    import("./document-statusbar.ts"),
    import("#editor/elements/table-view.ts"),
    import("#editor/elements/cake.ts"),
  ]);

  navigator.serviceWorker.register("/sw.js").catch(console.error);

  for (const [shortcut, actions] of Object.entries(shortcuts)) {
    for (const action of Array.isArray(actions) ? actions : [actions]) {
      Actions.mapShortcut(shortcut, action);
    }
  }

  history.log(location.pathname, document.title);

  if (activeSpaceId.value) {
    extensions.init(activeSpaceId.value).catch(console.error);
  }
});

onUnmounted(() => {
  if (!isServer) {
    document.removeEventListener("click", handleDocumentClick);
  }
});
</script>

<template>
  <div id="root" class="mx-auto relative origin-top" :style="initialLayoutStyle">
    <div
      :class="[
        'main-content min-h-screen h-full transition-transform md:transition-none relative',
        isMobileSidebarOpen ? 'translate-x-(--sidebar-width) md:translate-x-0' : '',
      ]"
    >
      <MobileHeader
        :spaceName="currentSpace?.name ?? ''"
        :pathname="pathname"
      />

      <DockedWindowLayout />

      <div v-if="spaceNotFound" class="flex flex-col items-center justify-center min-h-[60vh] gap-3 text-neutral-500">
        <p class="text-2xl font-semibold text-neutral-800">404</p>
        <p>Space not found.</p>
        <a href="/" class="text-sm underline hover:text-neutral-800">Go home</a>
      </div>
      <RouterView v-else />
    </div>

    <Sidebar
      :initialWidth="initialSidebarWidth"
      @mobile-open-change="isMobileSidebarOpen = $event"
    />
  </div>

  <ClientOnly>
    <CalDAVSetupDialog />
    <ToastContainer />
    <DocumentOverlay />
    <AIChatPanel :documentId="documentContext.documentId ?? ''" />
    <CommandPalatte />
  </ClientOnly>
</template>
