// app/src/components/TitleEditor.vue
<template>
  <div class="flex items-center gap-3 flex-1 -ml-1">
    <input
      ref="inputEl"
      v-if="isEditing"
      v-model="localTitle"
      type="text"
      placeholder="Untitled Document"
      class="pointer-events-auto text-size-display font-bold text-neutral-900 bg-neutral-50 focus:border-blue-500 outline-none focus:ring-0 flex-1 transition-colors px-1"
      @blur="updateTitle"
      @keydown.enter="updateTitle"
    >

    <div v-else :data-document-id="documentId" class="pointer-events-auto">
      <h1
        class="text-size-display font-bold text-neutral-900 flex items-center gap-3 px-1"
        :class="{ 'cursor-text hover:bg-neutral-50': canEdit, 'cursor-default': !canEdit }"
        @dblclick="canEdit && startEditing()"
      >
        {{ localTitle || 'Untitled Document' }}
      </h1>
    </div>
  </div>
</template>

<script setup lang="ts">
import { nextTick, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { api } from "#api/client.ts";

const router = useRouter();

const props = withDefaults(
  defineProps<{
    title: string;
    spaceId?: string;
    documentId?: string;
    initialEditMode?: boolean;
    canEdit?: boolean;
  }>(),
  {
    initialEditMode: false,
    canEdit: false,
  },
);

const emit = defineEmits<{
  "title-updated": [title: string];
}>();

const inputEl = ref<HTMLInputElement | null>(null);
const localTitle = ref(props.title);
const isEditing = ref(props.initialEditMode && props.canEdit);

async function startEditing() {
  if (!props.canEdit) return;
  isEditing.value = true;
  await nextTick();
  inputEl.value?.focus({ preventScroll: true });
}

watch(
  () => props.title,
  (newTitle) => {
    localTitle.value = newTitle;
  },
);

async function updateTitle() {
  if (localTitle.value !== props.title) {
    if (!props.canEdit) {
      localTitle.value = props.title;
      isEditing.value = false;
      return;
    }
    emit("title-updated", localTitle.value);
    window.dispatchEvent(
      new CustomEvent("title-changed", {
        detail: { title: localTitle.value },
      }),
    );

    if (!props.documentId) {
      window.dispatchEvent(
        new CustomEvent("pending-title-changed", {
          detail: { title: localTitle.value },
        }),
      );
      return;
    }

    try {
      if (!props.spaceId) throw new Error("No space selected");

      const data = await api.document.patch(props.spaceId, props.documentId, {
        properties: {
          title: {
            value: localTitle.value,
          },
        },
      });

      const newSlug = data.slug;
      if (newSlug) {
        const currentPath = window.location.pathname;
        if (/\/doc\/[^/]+/.test(currentPath)) {
          // Router paths are relative to its base ("/{spaceSlug}/"), so no
          // spacePath() prefix here.
          void router.replace(`/doc/${newSlug}`);
        }
      }
    } catch (error) {
      console.error("Error saving title:", error);
    }
  }
  isEditing.value = false;
}
</script>

<style scoped>
input::placeholder {
  color: #9ca3af;
}
</style>

// app/src/components/TitleEditor.tsx
import { useNavigate } from "@solidjs/router";
import { createEffect, createSignal, on, Show } from "solid-js";
import { api } from "#api/client.ts";

interface Props {
  title: string;
  spaceId?: string;
  documentId?: string;
  initialEditMode?: boolean;
  canEdit?: boolean;
  onTitleUpdated?: (title: string) => void;
}

export function TitleEditor(props: Props) {
  const navigate = useNavigate();
  const [localTitle, setLocalTitle] = createSignal(props.title);
  const [isEditing, setIsEditing] = createSignal(
    Boolean(props.initialEditMode && props.canEdit),
  );
  let inputEl: HTMLInputElement | undefined;

  createEffect(
    on(
      () => props.title,
      (next) => setLocalTitle(next),
      { defer: true },
    ),
  );

  function startEditing() {
    if (!props.canEdit) return;
    setIsEditing(true);
    // No `nextTick`: the signal write renders synchronously, so the input is
    // already in the document.
    inputEl?.focus({ preventScroll: true });
  }

  async function updateTitle() {
    if (localTitle() !== props.title) {
      if (!props.canEdit) {
        setLocalTitle(props.title);
        setIsEditing(false);
        return;
      }
      props.onTitleUpdated?.(localTitle());
      window.dispatchEvent(
        new CustomEvent("title-changed", { detail: { title: localTitle() } }),
      );

      if (!props.documentId) {
        window.dispatchEvent(
          new CustomEvent("pending-title-changed", { detail: { title: localTitle() } }),
        );
        return;
      }

      try {
        if (!props.spaceId) throw new Error("No space selected");

        const data = await api.document.patch(props.spaceId, props.documentId, {
          properties: { title: { value: localTitle() } },
        });

        if (data.slug && /\/doc\/[^/]+/.test(window.location.pathname)) {
          // Router paths are relative to its base ("/{spaceSlug}/"), so no
          // spacePath() prefix here.
          navigate(`/doc/${data.slug}`, { replace: true });
        }
      } catch (error) {
        console.error("Error saving title:", error);
      }
    }
    setIsEditing(false);
  }

  return (
    <div class="-ml-1 flex flex-1 items-center gap-3">
      <Show
        when={isEditing()}
        fallback={
          <div data-document-id={props.documentId} class="pointer-events-auto">
            <h1
              class="flex items-center gap-3 px-1 font-bold text-neutral-900 text-size-display"
              classList={{
                "cursor-text hover:bg-neutral-50": props.canEdit,
                "cursor-default": !props.canEdit,
              }}
              onDblClick={() => props.canEdit && startEditing()}
            >
              {localTitle() || "Untitled Document"}
            </h1>
          </div>
        }
      >
        <input
          ref={inputEl}
          type="text"
          placeholder="Untitled Document"
          class="pointer-events-auto flex-1 bg-neutral-50 px-1 font-bold text-neutral-900 text-size-display outline-none transition-colors placeholder:text-[#9ca3af] focus:border-blue-500 focus:ring-0"
          value={localTitle()}
          onInput={(event) => setLocalTitle(event.currentTarget.value)}
          onBlur={updateTitle}
          onKeyDown={(event) => {
            if (event.key === "Enter") void updateTitle();
          }}
        />
      </Show>
    </div>
  );
}
