// app/src/components/WorkflowEditorOverlay.vue
<script setup lang="ts">
import { onMounted, ref, toRef, watch } from "vue";
import "#editor/elements/code-editor.ts";
import type { CodeEditorElementApi } from "#editor/elements/code-editor.ts";
import { useCollaboration } from "#composeables/useCollaboration.ts";
import { useCosmetics } from "#composeables/useCosmetics.ts";
import {
  currentEditorPresenceState,
  type DocumentPresenceProfile,
  type DocumentPresenceState,
} from "#editor/collaboration.ts";
import DockedPanel from "./DockedPanel.vue";

const props = defineProps<{
  documentId: string;
  spaceId: string;
}>();

const codeEditor = ref<CodeEditorElementApi | null>(null);
const collaboration = useCollaboration<DocumentPresenceState>({
  spaceId: props.spaceId,
  documentId: toRef(props, "documentId"),
});
const { appearance } = useCosmetics();

function updatePresence() {
  collaboration.updatePresence(
    currentEditorPresenceState(codeEditor.value?.editorInstance),
  );
}

function updatePresenceSoon() {
  queueMicrotask(updatePresence);
}

function setupPresence() {
  collaboration.setPresenceState(
    currentEditorPresenceState(codeEditor.value?.editorInstance),
  );
  void collaboration.setupPresence();
}

watch(
  [codeEditor, collaboration.ydoc],
  ([editor, ydoc]) => {
    if (editor) editor.collaborationDocument = ydoc;
  },
  { immediate: true },
);

watch(
  [codeEditor, appearance],
  ([editor, currentAppearance]) => {
    if (editor) editor.appearance = currentAppearance;
  },
  { immediate: true },
);

watch(
  [codeEditor, collaboration.presenceProfiles],
  ([editor, profiles]) => {
    const editorProfiles = profiles.filter(
      (profile): profile is DocumentPresenceProfile => profile.state?.kind === "editor",
    );
    editor?.setPresenceProfiles(editorProfiles);
  },
  { immediate: true },
);

onMounted(async () => {
  await collaboration.joinUntilReady();
  setupPresence();
});
</script>

<template>
  <DockedPanel
    id="workflow-editor"
    title="Workflow Editor"
    default-side="right"
    :default-width="720"
    default-mode="floating"
  >
    <div class="flex flex-col h-full bg-background">
      <code-editor
        ref="codeEditor"
        class="flex-1 min-h-0"
        language="javascript"
        @presence-change="updatePresence"
        @selection-change="updatePresence"
        @editor-focus="updatePresenceSoon"
        @editor-blur="updatePresenceSoon"
      />
    </div>
  </DockedPanel>
</template>

// app/src/components/WorkflowEditorOverlay.tsx
import { createEffect, createSignal, on } from "solid-js";
import "#editor/elements/code-editor.ts";
import { useCollaboration } from "#composeables/useCollaboration.ts";
import { useCosmetics } from "#composeables/useCosmetics.ts";
import {
  currentEditorPresenceState,
  type DocumentPresenceProfile,
  type DocumentPresenceState,
} from "#editor/collaboration.ts";
import type { CodeEditorElementApi } from "#editor/elements/code-editor.ts";
import { DockedPanel } from "./DockedPanel.tsx";

interface Props {
  documentId: string;
  spaceId: string;
}

export function WorkflowEditorOverlay(props: Props) {
  const [codeEditor, setCodeEditor] = createSignal<CodeEditorElementApi | null>(null);
  const collaboration = useCollaboration<DocumentPresenceState>({
    spaceId: props.spaceId,
    documentId: () => props.documentId,
  });
  const { appearance } = useCosmetics();

  function updatePresence() {
    collaboration.updatePresence(
      currentEditorPresenceState(codeEditor()?.editorInstance),
    );
  }

  function updatePresenceSoon() {
    queueMicrotask(updatePresence);
  }

  createEffect(() => {
    const ydoc = collaboration.ydoc();
    const editor = codeEditor();
    if (editor) editor.collaborationDocument = ydoc;
  });

  createEffect(() => {
    const editor = codeEditor();
    if (editor) editor.appearance = appearance();
  });

  createEffect(() => {
    const editor = codeEditor();
    const editorProfiles = collaboration
      .presenceProfiles()
      .filter(
        (profile): profile is DocumentPresenceProfile => profile.state?.kind === "editor",
      );
    editor?.setPresenceProfiles(editorProfiles);
  });

  createEffect(
    on(
      () => props.documentId,
      async () => {
        await collaboration.joinUntilReady();
        collaboration.setPresenceState(
          currentEditorPresenceState(codeEditor()?.editorInstance),
        );
        void collaboration.setupPresence();
      },
    ),
  );

  return (
    <DockedPanel
      id="workflow-editor"
      title="Workflow Editor"
      defaultSide="right"
      defaultWidth={720}
      defaultMode="floating"
    >
      <div class="flex h-full flex-col bg-background">
        <code-editor
          ref={setCodeEditor as never}
          class="min-h-0 flex-1"
          language="javascript"
          on:presence-change={updatePresence}
          on:selection-change={updatePresence}
          on:editor-focus={updatePresenceSoon}
          on:editor-blur={updatePresenceSoon}
        />
      </div>
    </DockedPanel>
  );
}
