// app/src/components/views/SpaceSearchView.vue
<script setup lang="ts">
import Search from "#components/Search.vue";
import { useSpace } from "#composeables/useSpace.ts";

const { currentSpace } = useSpace();
</script>

<template>
  <inset-view v-if="currentSpace" class="block pt-m pb-20 lg:pb-8 h-full print:px-0 px-xs lg:px-xl md:ml-(--inset-left) md:mr-(--inset-right)">
    <Search :spaceId="currentSpace.id" />
  </inset-view>

</template>

// server/src/components/views/SpaceSearchView.tsx
import { Show } from "solid-js";
import { Search } from "#components/Search.tsx";
import { usePageTitle } from "#composeables/usePageTitle.ts";
import { useSpace } from "#composeables/useSpace.ts";

export function SpaceSearchView() {
  const { currentSpace } = useSpace();

  usePageTitle("Search");

  // No `pt-*` on the view: the sticky search bar carries the top gutter itself.
  return (
    <Show when={currentSpace()}>
      {(space) => (
        <inset-view class="block h-full page-spacing pb-20 md:mr-(--inset-right) md:ml-(--inset-left) lg:pb-8">
          <Search spaceId={space().id} />
        </inset-view>
      )}
    </Show>
  );
}
